-- Critical Event Trends by Diagnosis for Resource Allocation
-- Identifies which departments need more resources based on critical event patterns

WITH critical_events AS (
    SELECT 
        e.PATIENT_ID,
        e.HEART_RATE,
        e.OXYGEN_LEVEL,
        e.EVENT_TIMESTAMP,
        p.DIAGNOSIS,
        CASE 
            WHEN e.HEART_RATE > 120 AND e.OXYGEN_LEVEL < 90 THEN 'CRITICAL-BOTH'
            WHEN e.HEART_RATE > 120 THEN 'HIGH_HR'
            WHEN e.OXYGEN_LEVEL < 90 THEN 'LOW_O2'
        END AS ALERT_TYPE
    FROM RAW_DB.RAW_SCHEMA.ICU_EVENTS e
    JOIN RAW_DB.RAW_SCHEMA.PATIENT_RAW p ON e.PATIENT_ID = p.PATIENT_ID
    WHERE e.HEART_RATE > 120 OR e.OXYGEN_LEVEL < 90
),
diagnosis_summary AS (
    SELECT 
        DIAGNOSIS,
        COUNT(*) AS TOTAL_CRITICAL_EVENTS,
        COUNT(DISTINCT PATIENT_ID) AS UNIQUE_PATIENTS_AFFECTED,
        SUM(CASE WHEN ALERT_TYPE = 'CRITICAL-BOTH' THEN 1 ELSE 0 END) AS SEVERE_EVENTS,
        SUM(CASE WHEN ALERT_TYPE = 'HIGH_HR' THEN 1 ELSE 0 END) AS HIGH_HR_EVENTS,
        SUM(CASE WHEN ALERT_TYPE = 'LOW_O2' THEN 1 ELSE 0 END) AS LOW_O2_EVENTS,
        ROUND(AVG(HEART_RATE), 1) AS AVG_CRITICAL_HR,
        ROUND(AVG(OXYGEN_LEVEL), 1) AS AVG_CRITICAL_O2,
        MIN(EVENT_TIMESTAMP) AS FIRST_EVENT,
        MAX(EVENT_TIMESTAMP) AS LAST_EVENT
    FROM critical_events
    GROUP BY DIAGNOSIS
)
SELECT 
    DIAGNOSIS AS DEPARTMENT,
    TOTAL_CRITICAL_EVENTS,
    UNIQUE_PATIENTS_AFFECTED,
    ROUND(TOTAL_CRITICAL_EVENTS / NULLIF(UNIQUE_PATIENTS_AFFECTED, 0), 1) AS EVENTS_PER_PATIENT,
    SEVERE_EVENTS,
    HIGH_HR_EVENTS,
    LOW_O2_EVENTS,
    ROUND(100.0 * SEVERE_EVENTS / NULLIF(TOTAL_CRITICAL_EVENTS, 0), 1) AS SEVERE_PCT,
    AVG_CRITICAL_HR,
    AVG_CRITICAL_O2,
    FIRST_EVENT,
    LAST_EVENT
FROM diagnosis_summary
ORDER BY TOTAL_CRITICAL_EVENTS DESC;
