-- ============================================================================
-- ENTERPRISE HEALTHCARE DATA PLATFORM - DEPLOYMENT LOGGER
-- ============================================================================
-- File: 01_deployment_logger.sql
-- Purpose: Structured logging and deployment traceability
-- Version: 2.0.0
-- Dependencies: None (First to deploy)
-- ============================================================================

!SET variable_substitution=true;

USE ROLE ACCOUNTADMIN;

-- ============================================================================
-- STEP 1: CREATE OPERATIONS DATABASE (Environment-Agnostic)
-- ============================================================================

CREATE DATABASE IF NOT EXISTS OPS_DB
    DATA_RETENTION_TIME_IN_DAYS = 90
    COMMENT = 'Operations database for deployment tracking and observability';

CREATE SCHEMA IF NOT EXISTS OPS_DB.DEPLOYMENT
    COMMENT = 'Deployment logging and traceability';

CREATE SCHEMA IF NOT EXISTS OPS_DB.AUDIT
    COMMENT = 'Audit trail and compliance logging';

CREATE SCHEMA IF NOT EXISTS OPS_DB.MONITORING
    COMMENT = 'System monitoring and alerting';

USE DATABASE OPS_DB;
USE SCHEMA DEPLOYMENT;

-- ============================================================================
-- STEP 2: DEPLOYMENT LOG TABLE (Idempotent)
-- ============================================================================

CREATE TABLE IF NOT EXISTS DEPLOYMENT_LOG (
    -- Primary Key
    LOG_ID VARCHAR(36) NOT NULL DEFAULT UUID_STRING(),
    
    -- Deployment Context
    DEPLOYMENT_ID VARCHAR(36) NOT NULL,
    DEPLOYMENT_TIMESTAMP TIMESTAMP_NTZ NOT NULL DEFAULT CURRENT_TIMESTAMP(),
    ENVIRONMENT VARCHAR(10) NOT NULL,
    
    -- Execution Details
    SCRIPT_NAME VARCHAR(255) NOT NULL,
    SCRIPT_VERSION VARCHAR(20) DEFAULT '1.0.0',
    PHASE_NUMBER INTEGER,
    STEP_NUMBER INTEGER,
    STEP_DESCRIPTION VARCHAR(1000),
    
    -- Status
    STATUS VARCHAR(20) NOT NULL,  -- STARTED, SUCCESS, FAILED, SKIPPED, ROLLED_BACK
    ERROR_CODE VARCHAR(50),
    ERROR_MESSAGE VARCHAR(4000),
    
    -- Performance Metrics
    DURATION_MS INTEGER,
    ROWS_AFFECTED INTEGER,
    BYTES_SCANNED INTEGER,
    
    -- Traceability
    EXECUTED_BY VARCHAR(255) DEFAULT CURRENT_USER(),
    ROLE_USED VARCHAR(255) DEFAULT CURRENT_ROLE(),
    WAREHOUSE_USED VARCHAR(255) DEFAULT CURRENT_WAREHOUSE(),
    SESSION_ID VARCHAR(50) DEFAULT CURRENT_SESSION(),
    
    -- CI/CD Integration
    GIT_COMMIT_HASH VARCHAR(40),
    GIT_BRANCH VARCHAR(255),
    GIT_TAG VARCHAR(100),
    CI_PIPELINE_ID VARCHAR(100),
    CI_JOB_ID VARCHAR(100),
    
    -- Audit
    CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    
    CONSTRAINT PK_DEPLOYMENT_LOG PRIMARY KEY (LOG_ID)
);

-- Add indexes for query performance
CREATE OR REPLACE INDEX IDX_DEPLOYMENT_LOG_TIMESTAMP 
    ON DEPLOYMENT_LOG (DEPLOYMENT_TIMESTAMP DESC);
CREATE OR REPLACE INDEX IDX_DEPLOYMENT_LOG_STATUS 
    ON DEPLOYMENT_LOG (STATUS, ENVIRONMENT);

-- ============================================================================
-- STEP 3: OBJECT REGISTRY TABLE
-- ============================================================================

CREATE TABLE IF NOT EXISTS OBJECT_REGISTRY (
    REGISTRY_ID VARCHAR(36) NOT NULL DEFAULT UUID_STRING(),
    
    -- Object Identification
    OBJECT_TYPE VARCHAR(50) NOT NULL,  -- DATABASE, SCHEMA, TABLE, VIEW, PROCEDURE, etc.
    OBJECT_NAME VARCHAR(255) NOT NULL,
    FULLY_QUALIFIED_NAME VARCHAR(500) NOT NULL,
    
    -- Deployment Info
    DEPLOYMENT_ID VARCHAR(36),
    PHASE_NUMBER INTEGER,
    ENVIRONMENT VARCHAR(10) NOT NULL,
    
    -- Object Metadata
    OBJECT_OWNER VARCHAR(255),
    OBJECT_COMMENT VARCHAR(2000),
    DEPENDENCIES VARCHAR(4000),  -- JSON array of dependent objects
    
    -- Versioning
    VERSION VARCHAR(20) DEFAULT '1.0.0',
    PREVIOUS_VERSION VARCHAR(20),
    
    -- Status
    STATUS VARCHAR(20) DEFAULT 'ACTIVE',  -- ACTIVE, DEPRECATED, DELETED
    CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    UPDATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    CREATED_BY VARCHAR(255) DEFAULT CURRENT_USER(),
    
    CONSTRAINT PK_OBJECT_REGISTRY PRIMARY KEY (REGISTRY_ID),
    CONSTRAINT UQ_OBJECT_REGISTRY UNIQUE (FULLY_QUALIFIED_NAME, ENVIRONMENT)
);

-- ============================================================================
-- STEP 4: LOGGING PROCEDURES
-- ============================================================================

-- Procedure: Log deployment start
CREATE OR REPLACE PROCEDURE SP_LOG_DEPLOYMENT_START(
    P_DEPLOYMENT_ID VARCHAR,
    P_ENVIRONMENT VARCHAR,
    P_SCRIPT_NAME VARCHAR,
    P_PHASE_NUMBER INTEGER,
    P_GIT_COMMIT VARCHAR DEFAULT NULL,
    P_GIT_BRANCH VARCHAR DEFAULT 'main'
)
RETURNS VARCHAR
LANGUAGE SQL
AS
$$
BEGIN
    INSERT INTO OPS_DB.DEPLOYMENT.DEPLOYMENT_LOG (
        DEPLOYMENT_ID, ENVIRONMENT, SCRIPT_NAME, PHASE_NUMBER,
        STATUS, GIT_COMMIT_HASH, GIT_BRANCH
    ) VALUES (
        P_DEPLOYMENT_ID, P_ENVIRONMENT, P_SCRIPT_NAME, P_PHASE_NUMBER,
        'STARTED', P_GIT_COMMIT, P_GIT_BRANCH
    );
    RETURN 'Deployment started: ' || P_SCRIPT_NAME;
END;
$$;

-- Procedure: Log deployment step
CREATE OR REPLACE PROCEDURE SP_LOG_STEP(
    P_DEPLOYMENT_ID VARCHAR,
    P_STEP_NUMBER INTEGER,
    P_STEP_DESCRIPTION VARCHAR,
    P_STATUS VARCHAR,
    P_DURATION_MS INTEGER DEFAULT NULL,
    P_ROWS_AFFECTED INTEGER DEFAULT NULL,
    P_ERROR_MESSAGE VARCHAR DEFAULT NULL
)
RETURNS VARCHAR
LANGUAGE SQL
AS
$$
BEGIN
    INSERT INTO OPS_DB.DEPLOYMENT.DEPLOYMENT_LOG (
        DEPLOYMENT_ID, 
        STEP_NUMBER, 
        STEP_DESCRIPTION, 
        STATUS,
        DURATION_MS,
        ROWS_AFFECTED,
        ERROR_MESSAGE,
        SCRIPT_NAME,
        ENVIRONMENT
    ) 
    SELECT 
        P_DEPLOYMENT_ID,
        P_STEP_NUMBER,
        P_STEP_DESCRIPTION,
        P_STATUS,
        P_DURATION_MS,
        P_ROWS_AFFECTED,
        P_ERROR_MESSAGE,
        MAX(SCRIPT_NAME),
        MAX(ENVIRONMENT)
    FROM OPS_DB.DEPLOYMENT.DEPLOYMENT_LOG
    WHERE DEPLOYMENT_ID = P_DEPLOYMENT_ID;
    
    RETURN P_STATUS || ': ' || P_STEP_DESCRIPTION;
END;
$$;

-- Procedure: Register object
CREATE OR REPLACE PROCEDURE SP_REGISTER_OBJECT(
    P_DEPLOYMENT_ID VARCHAR,
    P_ENVIRONMENT VARCHAR,
    P_OBJECT_TYPE VARCHAR,
    P_OBJECT_NAME VARCHAR,
    P_FULLY_QUALIFIED_NAME VARCHAR,
    P_PHASE_NUMBER INTEGER,
    P_COMMENT VARCHAR DEFAULT NULL,
    P_DEPENDENCIES VARCHAR DEFAULT NULL
)
RETURNS VARCHAR
LANGUAGE SQL
AS
$$
BEGIN
    MERGE INTO OPS_DB.DEPLOYMENT.OBJECT_REGISTRY AS TGT
    USING (
        SELECT 
            P_DEPLOYMENT_ID AS DEPLOYMENT_ID,
            P_ENVIRONMENT AS ENVIRONMENT,
            P_OBJECT_TYPE AS OBJECT_TYPE,
            P_OBJECT_NAME AS OBJECT_NAME,
            P_FULLY_QUALIFIED_NAME AS FULLY_QUALIFIED_NAME,
            P_PHASE_NUMBER AS PHASE_NUMBER,
            P_COMMENT AS OBJECT_COMMENT,
            P_DEPENDENCIES AS DEPENDENCIES
    ) AS SRC
    ON TGT.FULLY_QUALIFIED_NAME = SRC.FULLY_QUALIFIED_NAME 
       AND TGT.ENVIRONMENT = SRC.ENVIRONMENT
    WHEN MATCHED THEN
        UPDATE SET 
            DEPLOYMENT_ID = SRC.DEPLOYMENT_ID,
            UPDATED_AT = CURRENT_TIMESTAMP(),
            PREVIOUS_VERSION = TGT.VERSION,
            VERSION = TGT.VERSION  -- Increment logic can be added
    WHEN NOT MATCHED THEN
        INSERT (DEPLOYMENT_ID, ENVIRONMENT, OBJECT_TYPE, OBJECT_NAME, 
                FULLY_QUALIFIED_NAME, PHASE_NUMBER, OBJECT_COMMENT, DEPENDENCIES)
        VALUES (SRC.DEPLOYMENT_ID, SRC.ENVIRONMENT, SRC.OBJECT_TYPE, SRC.OBJECT_NAME,
                SRC.FULLY_QUALIFIED_NAME, SRC.PHASE_NUMBER, SRC.OBJECT_COMMENT, SRC.DEPENDENCIES);
    
    RETURN 'Registered: ' || P_FULLY_QUALIFIED_NAME;
END;
$$;

-- ============================================================================
-- STEP 5: DEPLOYMENT VIEWS
-- ============================================================================

CREATE OR REPLACE VIEW V_DEPLOYMENT_SUMMARY AS
SELECT
    DEPLOYMENT_ID,
    ENVIRONMENT,
    MIN(DEPLOYMENT_TIMESTAMP) AS STARTED_AT,
    MAX(DEPLOYMENT_TIMESTAMP) AS COMPLETED_AT,
    DATEDIFF('SECOND', MIN(DEPLOYMENT_TIMESTAMP), MAX(DEPLOYMENT_TIMESTAMP)) AS DURATION_SECONDS,
    COUNT(DISTINCT SCRIPT_NAME) AS SCRIPTS_EXECUTED,
    SUM(CASE WHEN STATUS = 'SUCCESS' THEN 1 ELSE 0 END) AS SUCCESSFUL_STEPS,
    SUM(CASE WHEN STATUS = 'FAILED' THEN 1 ELSE 0 END) AS FAILED_STEPS,
    MAX(GIT_COMMIT_HASH) AS GIT_COMMIT,
    MAX(GIT_BRANCH) AS GIT_BRANCH
FROM DEPLOYMENT_LOG
GROUP BY DEPLOYMENT_ID, ENVIRONMENT
ORDER BY STARTED_AT DESC;

CREATE OR REPLACE VIEW V_RECENT_FAILURES AS
SELECT
    DEPLOYMENT_ID,
    ENVIRONMENT,
    SCRIPT_NAME,
    STEP_DESCRIPTION,
    ERROR_CODE,
    ERROR_MESSAGE,
    DEPLOYMENT_TIMESTAMP,
    EXECUTED_BY
FROM DEPLOYMENT_LOG
WHERE STATUS = 'FAILED'
    AND DEPLOYMENT_TIMESTAMP >= DATEADD(DAY, -7, CURRENT_TIMESTAMP())
ORDER BY DEPLOYMENT_TIMESTAMP DESC;

CREATE OR REPLACE VIEW V_OBJECT_INVENTORY AS
SELECT
    ENVIRONMENT,
    OBJECT_TYPE,
    COUNT(*) AS OBJECT_COUNT,
    MAX(UPDATED_AT) AS LAST_UPDATED
FROM OBJECT_REGISTRY
WHERE STATUS = 'ACTIVE'
GROUP BY ENVIRONMENT, OBJECT_TYPE
ORDER BY ENVIRONMENT, OBJECT_TYPE;

-- ============================================================================
-- STEP 6: VALIDATION
-- ============================================================================

-- Validate deployment logger setup
SELECT 
    'DEPLOYMENT_LOGGER' AS COMPONENT,
    CASE 
        WHEN COUNT(*) >= 3 THEN 'VALIDATED'
        ELSE 'FAILED'
    END AS STATUS,
    COUNT(*) AS OBJECTS_CREATED
FROM (
    SELECT TABLE_NAME FROM OPS_DB.INFORMATION_SCHEMA.TABLES 
    WHERE TABLE_SCHEMA = 'DEPLOYMENT'
    UNION ALL
    SELECT PROCEDURE_NAME FROM OPS_DB.INFORMATION_SCHEMA.PROCEDURES 
    WHERE PROCEDURE_SCHEMA = 'DEPLOYMENT'
);

-- ============================================================================
-- END OF DEPLOYMENT LOGGER
-- ============================================================================
