-- ============================================================================
-- ENTERPRISE HEALTHCARE DATA PLATFORM - PHASE 3: COMPUTE INFRASTRUCTURE
-- ============================================================================
-- File: 04_compute_infrastructure.sql
-- Purpose: Warehouses with cost governance via resource monitors
-- Version: 2.0.0
-- Phase: 3
-- Dependencies: 03_rbac_hierarchy.sql
-- ============================================================================

!SET variable_substitution=true;

USE ROLE ACCOUNTADMIN;

-- Initialize deployment context
SET DEPLOYMENT_ID = (SELECT UUID_STRING());
SET ENV = COALESCE($ENV, 'DEV');
SET DB_PREFIX = (SELECT CASE $ENV WHEN 'DEV' THEN 'DEV_' WHEN 'QA' THEN 'QA_' ELSE '' END);

-- Environment-specific sizing
SET WH_SIZE_ETL = (SELECT CASE $ENV WHEN 'DEV' THEN 'XSMALL' WHEN 'QA' THEN 'SMALL' ELSE 'MEDIUM' END);
SET WH_SIZE_TRANSFORM = (SELECT CASE $ENV WHEN 'DEV' THEN 'XSMALL' WHEN 'QA' THEN 'SMALL' ELSE 'LARGE' END);
SET WH_SIZE_ANALYTICS = (SELECT CASE $ENV WHEN 'DEV' THEN 'XSMALL' WHEN 'QA' THEN 'SMALL' ELSE 'MEDIUM' END);
SET WH_SIZE_AI = (SELECT CASE $ENV WHEN 'DEV' THEN 'XSMALL' WHEN 'QA' THEN 'MEDIUM' ELSE 'LARGE' END);

-- Credit quotas (Cost Governance)
SET QUOTA_ACCOUNT = (SELECT CASE $ENV WHEN 'DEV' THEN 50 WHEN 'QA' THEN 100 ELSE 500 END);
SET QUOTA_ETL = (SELECT CASE $ENV WHEN 'DEV' THEN 10 WHEN 'QA' THEN 25 ELSE 100 END);
SET QUOTA_TRANSFORM = (SELECT CASE $ENV WHEN 'DEV' THEN 15 WHEN 'QA' THEN 35 ELSE 150 END);
SET QUOTA_ANALYTICS = (SELECT CASE $ENV WHEN 'DEV' THEN 10 WHEN 'QA' THEN 20 ELSE 75 END);
SET QUOTA_AI = (SELECT CASE $ENV WHEN 'DEV' THEN 20 WHEN 'QA' THEN 50 ELSE 200 END);

-- Auto-suspend (cost optimization)
SET AUTO_SUSPEND_DEV = 60;
SET AUTO_SUSPEND_PROD = 300;
SET AUTO_SUSPEND = (SELECT CASE $ENV WHEN 'PROD' THEN $AUTO_SUSPEND_PROD ELSE $AUTO_SUSPEND_DEV END);

CALL OPS_DB.DEPLOYMENT.SP_LOG_DEPLOYMENT_START(
    $DEPLOYMENT_ID, $ENV, '04_compute_infrastructure.sql', 3, $GIT_COMMIT, $GIT_BRANCH
);

-- ============================================================================
-- STEP 1: ACCOUNT-LEVEL RESOURCE MONITOR
-- ============================================================================

SET STEP_START = (SELECT CURRENT_TIMESTAMP());

CREATE OR REPLACE RESOURCE MONITOR IDENTIFIER($DB_PREFIX || 'HC_ACCOUNT_RM')
    WITH 
        CREDIT_QUOTA = $QUOTA_ACCOUNT
        FREQUENCY = MONTHLY
        START_TIMESTAMP = IMMEDIATELY
    TRIGGERS
        ON 50 PERCENT DO NOTIFY
        ON 75 PERCENT DO NOTIFY
        ON 90 PERCENT DO NOTIFY
        ON 100 PERCENT DO SUSPEND
        ON 110 PERCENT DO SUSPEND_IMMEDIATE;

-- Set at account level (only in PROD with approval)
-- ALTER ACCOUNT SET RESOURCE_MONITOR = IDENTIFIER($DB_PREFIX || 'HC_ACCOUNT_RM');

CALL OPS_DB.DEPLOYMENT.SP_LOG_STEP($DEPLOYMENT_ID, 1, 
    'Created account resource monitor (quota: ' || $QUOTA_ACCOUNT || ' credits)', 'SUCCESS',
    DATEDIFF('MILLISECOND', $STEP_START, CURRENT_TIMESTAMP()));

-- ============================================================================
-- STEP 2: ETL WAREHOUSE WITH RESOURCE MONITOR
-- ============================================================================

SET STEP_START = (SELECT CURRENT_TIMESTAMP());

-- Create resource monitor first
CREATE OR REPLACE RESOURCE MONITOR IDENTIFIER($DB_PREFIX || 'HC_ETL_WH_RM')
    WITH 
        CREDIT_QUOTA = $QUOTA_ETL
        FREQUENCY = MONTHLY
        START_TIMESTAMP = IMMEDIATELY
    TRIGGERS
        ON 75 PERCENT DO NOTIFY
        ON 90 PERCENT DO NOTIFY
        ON 100 PERCENT DO SUSPEND;

-- Create warehouse
CREATE OR REPLACE WAREHOUSE IDENTIFIER($DB_PREFIX || 'HC_ETL_WH')
    WITH
        WAREHOUSE_SIZE = $WH_SIZE_ETL
        WAREHOUSE_TYPE = 'STANDARD'
        AUTO_SUSPEND = $AUTO_SUSPEND
        AUTO_RESUME = TRUE
        INITIALLY_SUSPENDED = TRUE
        MIN_CLUSTER_COUNT = 1
        MAX_CLUSTER_COUNT = (SELECT CASE $ENV WHEN 'PROD' THEN 4 ELSE 1 END)
        SCALING_POLICY = 'STANDARD'
        RESOURCE_MONITOR = IDENTIFIER($DB_PREFIX || 'HC_ETL_WH_RM')
        COMMENT = 'ETL Warehouse - Data ingestion and loading workloads';

-- Grant to appropriate roles
GRANT USAGE ON WAREHOUSE IDENTIFIER($DB_PREFIX || 'HC_ETL_WH') 
    TO ROLE IDENTIFIER($DB_PREFIX || 'HC_DATA_ENGINEER');
GRANT USAGE ON WAREHOUSE IDENTIFIER($DB_PREFIX || 'HC_ETL_WH') 
    TO ROLE IDENTIFIER($DB_PREFIX || 'HC_SVC_ETL');
GRANT OPERATE ON WAREHOUSE IDENTIFIER($DB_PREFIX || 'HC_ETL_WH') 
    TO ROLE IDENTIFIER($DB_PREFIX || 'HC_DATA_ENGINEER');

CALL OPS_DB.DEPLOYMENT.SP_LOG_STEP($DEPLOYMENT_ID, 2, 
    'Created ETL warehouse (size: ' || $WH_SIZE_ETL || ', quota: ' || $QUOTA_ETL || ')', 'SUCCESS',
    DATEDIFF('MILLISECOND', $STEP_START, CURRENT_TIMESTAMP()));

CALL OPS_DB.DEPLOYMENT.SP_REGISTER_OBJECT($DEPLOYMENT_ID, $ENV, 'WAREHOUSE', 
    $DB_PREFIX || 'HC_ETL_WH', $DB_PREFIX || 'HC_ETL_WH', 3, 
    'ETL Data Ingestion Warehouse', '["' || $DB_PREFIX || 'HC_ETL_WH_RM"]');

-- ============================================================================
-- STEP 3: TRANSFORM WAREHOUSE WITH RESOURCE MONITOR
-- ============================================================================

SET STEP_START = (SELECT CURRENT_TIMESTAMP());

CREATE OR REPLACE RESOURCE MONITOR IDENTIFIER($DB_PREFIX || 'HC_TRANSFORM_WH_RM')
    WITH 
        CREDIT_QUOTA = $QUOTA_TRANSFORM
        FREQUENCY = MONTHLY
        START_TIMESTAMP = IMMEDIATELY
    TRIGGERS
        ON 75 PERCENT DO NOTIFY
        ON 90 PERCENT DO NOTIFY
        ON 100 PERCENT DO SUSPEND;

CREATE OR REPLACE WAREHOUSE IDENTIFIER($DB_PREFIX || 'HC_TRANSFORM_WH')
    WITH
        WAREHOUSE_SIZE = $WH_SIZE_TRANSFORM
        WAREHOUSE_TYPE = 'STANDARD'
        AUTO_SUSPEND = $AUTO_SUSPEND
        AUTO_RESUME = TRUE
        INITIALLY_SUSPENDED = TRUE
        MIN_CLUSTER_COUNT = 1
        MAX_CLUSTER_COUNT = (SELECT CASE $ENV WHEN 'PROD' THEN 6 ELSE 2 END)
        SCALING_POLICY = 'STANDARD'
        RESOURCE_MONITOR = IDENTIFIER($DB_PREFIX || 'HC_TRANSFORM_WH_RM')
        COMMENT = 'Transform Warehouse - Data transformation and processing';

GRANT USAGE ON WAREHOUSE IDENTIFIER($DB_PREFIX || 'HC_TRANSFORM_WH') 
    TO ROLE IDENTIFIER($DB_PREFIX || 'HC_DATA_ENGINEER');
GRANT OPERATE ON WAREHOUSE IDENTIFIER($DB_PREFIX || 'HC_TRANSFORM_WH') 
    TO ROLE IDENTIFIER($DB_PREFIX || 'HC_DATA_ENGINEER');

CALL OPS_DB.DEPLOYMENT.SP_LOG_STEP($DEPLOYMENT_ID, 3, 
    'Created Transform warehouse (size: ' || $WH_SIZE_TRANSFORM || ')', 'SUCCESS',
    DATEDIFF('MILLISECOND', $STEP_START, CURRENT_TIMESTAMP()));

-- ============================================================================
-- STEP 4: ANALYTICS WAREHOUSE WITH RESOURCE MONITOR
-- ============================================================================

SET STEP_START = (SELECT CURRENT_TIMESTAMP());

CREATE OR REPLACE RESOURCE MONITOR IDENTIFIER($DB_PREFIX || 'HC_ANALYTICS_WH_RM')
    WITH 
        CREDIT_QUOTA = $QUOTA_ANALYTICS
        FREQUENCY = MONTHLY
        START_TIMESTAMP = IMMEDIATELY
    TRIGGERS
        ON 75 PERCENT DO NOTIFY
        ON 90 PERCENT DO NOTIFY
        ON 100 PERCENT DO SUSPEND;

CREATE OR REPLACE WAREHOUSE IDENTIFIER($DB_PREFIX || 'HC_ANALYTICS_WH')
    WITH
        WAREHOUSE_SIZE = $WH_SIZE_ANALYTICS
        WAREHOUSE_TYPE = 'STANDARD'
        AUTO_SUSPEND = 60  -- Faster suspend for interactive queries
        AUTO_RESUME = TRUE
        INITIALLY_SUSPENDED = TRUE
        MIN_CLUSTER_COUNT = 1
        MAX_CLUSTER_COUNT = (SELECT CASE $ENV WHEN 'PROD' THEN 3 ELSE 1 END)
        SCALING_POLICY = 'ECONOMY'  -- Cost-optimized for analytics
        RESOURCE_MONITOR = IDENTIFIER($DB_PREFIX || 'HC_ANALYTICS_WH_RM')
        COMMENT = 'Analytics Warehouse - BI and reporting workloads';

GRANT USAGE ON WAREHOUSE IDENTIFIER($DB_PREFIX || 'HC_ANALYTICS_WH') 
    TO ROLE IDENTIFIER($DB_PREFIX || 'HC_DATA_ANALYST');
GRANT USAGE ON WAREHOUSE IDENTIFIER($DB_PREFIX || 'HC_ANALYTICS_WH') 
    TO ROLE IDENTIFIER($DB_PREFIX || 'HC_VIEWER');
GRANT USAGE ON WAREHOUSE IDENTIFIER($DB_PREFIX || 'HC_ANALYTICS_WH') 
    TO ROLE IDENTIFIER($DB_PREFIX || 'HC_SVC_ANALYTICS');

CALL OPS_DB.DEPLOYMENT.SP_LOG_STEP($DEPLOYMENT_ID, 4, 
    'Created Analytics warehouse (size: ' || $WH_SIZE_ANALYTICS || ')', 'SUCCESS',
    DATEDIFF('MILLISECOND', $STEP_START, CURRENT_TIMESTAMP()));

-- ============================================================================
-- STEP 5: AI/ML WAREHOUSE WITH RESOURCE MONITOR
-- ============================================================================

SET STEP_START = (SELECT CURRENT_TIMESTAMP());

CREATE OR REPLACE RESOURCE MONITOR IDENTIFIER($DB_PREFIX || 'HC_AI_WH_RM')
    WITH 
        CREDIT_QUOTA = $QUOTA_AI
        FREQUENCY = MONTHLY
        START_TIMESTAMP = IMMEDIATELY
    TRIGGERS
        ON 50 PERCENT DO NOTIFY  -- Earlier notification for expensive ML workloads
        ON 75 PERCENT DO NOTIFY
        ON 90 PERCENT DO NOTIFY
        ON 100 PERCENT DO SUSPEND;

CREATE OR REPLACE WAREHOUSE IDENTIFIER($DB_PREFIX || 'HC_AI_WH')
    WITH
        WAREHOUSE_SIZE = $WH_SIZE_AI
        WAREHOUSE_TYPE = 'STANDARD'  -- Consider 'SNOWPARK-OPTIMIZED' for ML
        AUTO_SUSPEND = $AUTO_SUSPEND_PROD  -- Longer suspend for ML jobs
        AUTO_RESUME = TRUE
        INITIALLY_SUSPENDED = TRUE
        MIN_CLUSTER_COUNT = 1
        MAX_CLUSTER_COUNT = (SELECT CASE $ENV WHEN 'PROD' THEN 8 ELSE 2 END)
        SCALING_POLICY = 'STANDARD'
        RESOURCE_MONITOR = IDENTIFIER($DB_PREFIX || 'HC_AI_WH_RM')
        COMMENT = 'AI/ML Warehouse - Machine learning and advanced analytics';

GRANT USAGE ON WAREHOUSE IDENTIFIER($DB_PREFIX || 'HC_AI_WH') 
    TO ROLE IDENTIFIER($DB_PREFIX || 'HC_DATA_SCIENTIST');
GRANT USAGE ON WAREHOUSE IDENTIFIER($DB_PREFIX || 'HC_AI_WH') 
    TO ROLE IDENTIFIER($DB_PREFIX || 'HC_SVC_ML');
GRANT OPERATE ON WAREHOUSE IDENTIFIER($DB_PREFIX || 'HC_AI_WH') 
    TO ROLE IDENTIFIER($DB_PREFIX || 'HC_DATA_SCIENTIST');

CALL OPS_DB.DEPLOYMENT.SP_LOG_STEP($DEPLOYMENT_ID, 5, 
    'Created AI/ML warehouse (size: ' || $WH_SIZE_AI || ')', 'SUCCESS',
    DATEDIFF('MILLISECOND', $STEP_START, CURRENT_TIMESTAMP()));

-- ============================================================================
-- STEP 6: COST GOVERNANCE VIEWS
-- ============================================================================

SET STEP_START = (SELECT CURRENT_TIMESTAMP());

USE DATABASE OPS_DB;
USE SCHEMA MONITORING;

-- Real-time credit usage view
CREATE OR REPLACE VIEW V_CREDIT_USAGE_REALTIME AS
SELECT
    WAREHOUSE_NAME,
    DATE_TRUNC('HOUR', START_TIME) AS USAGE_HOUR,
    SUM(CREDITS_USED) AS CREDITS_USED,
    SUM(CREDITS_USED_COMPUTE) AS CREDITS_COMPUTE,
    SUM(CREDITS_USED_CLOUD_SERVICES) AS CREDITS_CLOUD_SERVICES,
    COUNT(*) AS QUERY_COUNT
FROM SNOWFLAKE.ACCOUNT_USAGE.WAREHOUSE_METERING_HISTORY
WHERE START_TIME >= DATEADD(DAY, -7, CURRENT_TIMESTAMP())
    AND WAREHOUSE_NAME LIKE $DB_PREFIX || 'HC_%'
GROUP BY WAREHOUSE_NAME, DATE_TRUNC('HOUR', START_TIME)
ORDER BY USAGE_HOUR DESC;

-- Resource monitor status view
CREATE OR REPLACE VIEW V_RESOURCE_MONITOR_STATUS AS
SELECT
    NAME AS MONITOR_NAME,
    CREDIT_QUOTA AS MONTHLY_QUOTA,
    USED_CREDITS AS CREDITS_USED,
    REMAINING_CREDITS AS CREDITS_REMAINING,
    ROUND(100 * USED_CREDITS / NULLIF(CREDIT_QUOTA, 0), 2) AS PCT_USED,
    CASE 
        WHEN USED_CREDITS / NULLIF(CREDIT_QUOTA, 0) >= 0.9 THEN 'CRITICAL'
        WHEN USED_CREDITS / NULLIF(CREDIT_QUOTA, 0) >= 0.75 THEN 'WARNING'
        ELSE 'HEALTHY'
    END AS STATUS
FROM SNOWFLAKE.ACCOUNT_USAGE.RESOURCE_MONITORS
WHERE NAME LIKE $DB_PREFIX || 'HC_%';

-- Cost forecast view (simple linear projection)
CREATE OR REPLACE VIEW V_COST_FORECAST AS
WITH daily_usage AS (
    SELECT 
        DATE_TRUNC('DAY', START_TIME) AS USAGE_DATE,
        SUM(CREDITS_USED) AS DAILY_CREDITS
    FROM SNOWFLAKE.ACCOUNT_USAGE.WAREHOUSE_METERING_HISTORY
    WHERE START_TIME >= DATEADD(DAY, -30, CURRENT_TIMESTAMP())
        AND WAREHOUSE_NAME LIKE $DB_PREFIX || 'HC_%'
    GROUP BY DATE_TRUNC('DAY', START_TIME)
)
SELECT
    AVG(DAILY_CREDITS) AS AVG_DAILY_CREDITS,
    AVG(DAILY_CREDITS) * 30 AS PROJECTED_MONTHLY_CREDITS,
    AVG(DAILY_CREDITS) * DAY(LAST_DAY(CURRENT_DATE)) AS PROJECTED_THIS_MONTH,
    $QUOTA_ACCOUNT AS MONTHLY_BUDGET,
    ROUND(100 * (AVG(DAILY_CREDITS) * DAY(LAST_DAY(CURRENT_DATE))) / NULLIF($QUOTA_ACCOUNT, 0), 2) AS PROJECTED_PCT_OF_BUDGET
FROM daily_usage;

CALL OPS_DB.DEPLOYMENT.SP_LOG_STEP($DEPLOYMENT_ID, 6, 'Created cost governance views', 'SUCCESS',
    DATEDIFF('MILLISECOND', $STEP_START, CURRENT_TIMESTAMP()));

-- ============================================================================
-- POST-DEPLOYMENT VALIDATION
-- ============================================================================

SET STEP_START = (SELECT CURRENT_TIMESTAMP());

-- Validate warehouses
SET WH_COUNT = (SELECT COUNT(*) FROM (SHOW WAREHOUSES LIKE $DB_PREFIX || 'HC_%'));
SET RM_COUNT = (SELECT COUNT(*) FROM (SHOW RESOURCE MONITORS LIKE $DB_PREFIX || 'HC_%'));

SET VALIDATION_PASSED = (SELECT $WH_COUNT >= 4 AND $RM_COUNT >= 5);

CALL OPS_DB.DEPLOYMENT.SP_LOG_STEP($DEPLOYMENT_ID, 99, 
    'Validation: ' || $WH_COUNT || ' warehouses, ' || $RM_COUNT || ' resource monitors', 
    CASE WHEN $VALIDATION_PASSED THEN 'SUCCESS' ELSE 'FAILED' END,
    DATEDIFF('MILLISECOND', $STEP_START, CURRENT_TIMESTAMP()));

-- Output summary
SELECT 
    'COMPUTE_INFRASTRUCTURE' AS PHASE,
    $ENV AS ENVIRONMENT,
    $WH_COUNT AS WAREHOUSES_CREATED,
    $RM_COUNT AS RESOURCE_MONITORS_CREATED,
    $QUOTA_ACCOUNT AS TOTAL_MONTHLY_CREDIT_BUDGET,
    CASE WHEN $VALIDATION_PASSED THEN 'VALIDATED' ELSE 'VALIDATION_FAILED' END AS STATUS;

-- ============================================================================
-- END OF COMPUTE INFRASTRUCTURE
-- ============================================================================
