-- =============================================
-- 02_RBAC_SETUP.SQL
-- Healthcare Role-Based Access Control
-- =============================================

USE ROLE ACCOUNTADMIN;

-- Create Role Hierarchy
CREATE ROLE IF NOT EXISTS HC_ACCOUNT_ADMIN COMMENT = 'Healthcare Account Administrator';
CREATE ROLE IF NOT EXISTS HC_SECURITY_ADMIN COMMENT = 'Healthcare Security Administrator';
CREATE ROLE IF NOT EXISTS HC_DATA_ENGINEER COMMENT = 'Healthcare Data Engineer';
CREATE ROLE IF NOT EXISTS HC_ANALYST COMMENT = 'Healthcare Data Analyst';
CREATE ROLE IF NOT EXISTS HC_DATA_SCIENTIST COMMENT = 'Healthcare Data Scientist';
CREATE ROLE IF NOT EXISTS HC_VIEWER COMMENT = 'Healthcare Read-Only Viewer';

-- Role Hierarchy
GRANT ROLE HC_VIEWER TO ROLE HC_ANALYST;
GRANT ROLE HC_ANALYST TO ROLE HC_DATA_ENGINEER;
GRANT ROLE HC_DATA_ENGINEER TO ROLE HC_ACCOUNT_ADMIN;
GRANT ROLE HC_SECURITY_ADMIN TO ROLE HC_ACCOUNT_ADMIN;
GRANT ROLE HC_DATA_SCIENTIST TO ROLE HC_ACCOUNT_ADMIN;
GRANT ROLE HC_ACCOUNT_ADMIN TO ROLE ACCOUNTADMIN;

-- Grant to Current User
GRANT ROLE HC_ACCOUNT_ADMIN TO USER DEVIKAPG;
GRANT ROLE HC_DATA_ENGINEER TO USER DEVIKAPG;
GRANT ROLE HC_ANALYST TO USER DEVIKAPG;

-- Verify
SHOW ROLES LIKE 'HC_%';
