-- =============================================
-- 03_WAREHOUSE_MANAGEMENT.SQL
-- Healthcare Warehouse Configuration
-- =============================================

USE ROLE SYSADMIN;

-- ETL Warehouse
CREATE WAREHOUSE IF NOT EXISTS HC_ETL_WH
    WAREHOUSE_SIZE = 'MEDIUM'
    AUTO_SUSPEND = 60
    AUTO_RESUME = TRUE
    MIN_CLUSTER_COUNT = 1
    MAX_CLUSTER_COUNT = 1
    SCALING_POLICY = 'STANDARD'
    COMMENT = 'Healthcare ETL Processing';

-- Transform Warehouse
CREATE WAREHOUSE IF NOT EXISTS HC_TRANSFORM_WH
    WAREHOUSE_SIZE = 'LARGE'
    AUTO_SUSPEND = 120
    AUTO_RESUME = TRUE
    COMMENT = 'Healthcare Data Transformation';

-- Analytics Warehouse
CREATE WAREHOUSE IF NOT EXISTS HC_ANALYTICS_WH
    WAREHOUSE_SIZE = 'MEDIUM'
    AUTO_SUSPEND = 60
    AUTO_RESUME = TRUE
    COMMENT = 'Healthcare Analytics Queries';

-- AI/ML Warehouse
CREATE WAREHOUSE IF NOT EXISTS HC_AI_WH
    WAREHOUSE_SIZE = 'LARGE'
    AUTO_SUSPEND = 300
    AUTO_RESUME = TRUE
    COMMENT = 'Healthcare AI/ML Workloads';

-- Grant Usage
USE ROLE ACCOUNTADMIN;
GRANT USAGE ON WAREHOUSE HC_ETL_WH TO ROLE HC_DATA_ENGINEER;
GRANT USAGE ON WAREHOUSE HC_TRANSFORM_WH TO ROLE HC_DATA_ENGINEER;
GRANT USAGE ON WAREHOUSE HC_ANALYTICS_WH TO ROLE HC_ANALYST;
GRANT USAGE ON WAREHOUSE HC_AI_WH TO ROLE HC_DATA_SCIENTIST;

-- Verify
SHOW WAREHOUSES LIKE 'HC_%';
