-- =============================================
-- 04_DATABASE_STRUCTURE.SQL
-- Healthcare Database Architecture
-- =============================================

USE ROLE SYSADMIN;

-- Bronze Layer (Raw)
CREATE DATABASE IF NOT EXISTS RAW_DB COMMENT = 'Bronze Layer - Raw Data';
CREATE SCHEMA IF NOT EXISTS RAW_DB.RAW_SCHEMA;

-- Silver Layer (Transform)
CREATE DATABASE IF NOT EXISTS TRANSFORM_DB COMMENT = 'Silver Layer - Transformed Data';
CREATE SCHEMA IF NOT EXISTS TRANSFORM_DB.TRANSFORM_SCHEMA;

-- Gold Layer (Analytics)
CREATE DATABASE IF NOT EXISTS ANALYTICS_DB COMMENT = 'Gold Layer - Analytics Ready';
CREATE SCHEMA IF NOT EXISTS ANALYTICS_DB.ANALYTICS_SCHEMA;

-- Platinum Layer (AI/ML)
CREATE DATABASE IF NOT EXISTS AI_READY_DB COMMENT = 'Platinum Layer - AI/ML Ready';
CREATE SCHEMA IF NOT EXISTS AI_READY_DB.AI_SCHEMA;
CREATE SCHEMA IF NOT EXISTS AI_READY_DB.FEATURE_STORE COMMENT = 'ML Feature Store';
CREATE SCHEMA IF NOT EXISTS AI_READY_DB.SEMANTIC_MODELS COMMENT = 'Cortex Analyst Semantic Models';

-- Monitoring Database
USE ROLE ACCOUNTADMIN;
CREATE DATABASE IF NOT EXISTS MONITORING_DB COMMENT = 'Monitoring and Observability';
CREATE SCHEMA IF NOT EXISTS MONITORING_DB.MONITORING_SCHEMA;

-- DevOps Database
CREATE DATABASE IF NOT EXISTS DEVOPS_DB COMMENT = 'DevOps and CI/CD';
CREATE SCHEMA IF NOT EXISTS DEVOPS_DB.CI_CD;

-- Audit Database
CREATE DATABASE IF NOT EXISTS AUDIT_DB COMMENT = 'Audit and Compliance';
CREATE SCHEMA IF NOT EXISTS AUDIT_DB.AUDIT_SCHEMA;

-- Security Database
CREATE DATABASE IF NOT EXISTS SECURITY_DB COMMENT = 'Security Policies';
CREATE SCHEMA IF NOT EXISTS SECURITY_DB.POLICIES;

-- Grant Permissions
GRANT USAGE ON DATABASE RAW_DB TO ROLE HC_DATA_ENGINEER;
GRANT USAGE ON DATABASE TRANSFORM_DB TO ROLE HC_DATA_ENGINEER;
GRANT USAGE ON DATABASE ANALYTICS_DB TO ROLE HC_ANALYST;
GRANT USAGE ON DATABASE AI_READY_DB TO ROLE HC_DATA_SCIENTIST;

GRANT ALL ON SCHEMA RAW_DB.RAW_SCHEMA TO ROLE HC_DATA_ENGINEER;
GRANT ALL ON SCHEMA TRANSFORM_DB.TRANSFORM_SCHEMA TO ROLE HC_DATA_ENGINEER;
GRANT ALL ON SCHEMA ANALYTICS_DB.ANALYTICS_SCHEMA TO ROLE HC_ANALYST;

-- Verify
SHOW DATABASES LIKE '%_DB';
