-- =============================================
-- 05_RESOURCE_MONITORS.SQL
-- Healthcare Cost Management
-- =============================================

USE ROLE ACCOUNTADMIN;

-- ETL Warehouse Monitor
CREATE OR REPLACE RESOURCE MONITOR HC_ETL_WH_MONITOR
    WITH CREDIT_QUOTA = 100
    FREQUENCY = MONTHLY
    START_TIMESTAMP = IMMEDIATELY
    TRIGGERS
        ON 75 PERCENT DO NOTIFY
        ON 90 PERCENT DO NOTIFY
        ON 100 PERCENT DO SUSPEND;

-- Transform Warehouse Monitor
CREATE OR REPLACE RESOURCE MONITOR HC_TRANSFORM_WH_MONITOR
    WITH CREDIT_QUOTA = 150
    FREQUENCY = MONTHLY
    START_TIMESTAMP = IMMEDIATELY
    TRIGGERS
        ON 75 PERCENT DO NOTIFY
        ON 90 PERCENT DO NOTIFY
        ON 100 PERCENT DO SUSPEND;

-- Analytics Warehouse Monitor
CREATE OR REPLACE RESOURCE MONITOR HC_ANALYTICS_WH_MONITOR
    WITH CREDIT_QUOTA = 75
    FREQUENCY = MONTHLY
    START_TIMESTAMP = IMMEDIATELY
    TRIGGERS
        ON 75 PERCENT DO NOTIFY
        ON 90 PERCENT DO NOTIFY
        ON 100 PERCENT DO SUSPEND;

-- AI Warehouse Monitor
CREATE OR REPLACE RESOURCE MONITOR HC_AI_WH_MONITOR
    WITH CREDIT_QUOTA = 200
    FREQUENCY = MONTHLY
    START_TIMESTAMP = IMMEDIATELY
    TRIGGERS
        ON 75 PERCENT DO NOTIFY
        ON 90 PERCENT DO NOTIFY
        ON 100 PERCENT DO SUSPEND;

-- Account Level Monitor
CREATE OR REPLACE RESOURCE MONITOR HC_ACCOUNT_MONITOR
    WITH CREDIT_QUOTA = 500
    FREQUENCY = MONTHLY
    START_TIMESTAMP = IMMEDIATELY
    TRIGGERS
        ON 50 PERCENT DO NOTIFY
        ON 75 PERCENT DO NOTIFY
        ON 90 PERCENT DO NOTIFY
        ON 100 PERCENT DO SUSPEND;

-- Assign Monitors to Warehouses
ALTER WAREHOUSE HC_ETL_WH SET RESOURCE_MONITOR = HC_ETL_WH_MONITOR;
ALTER WAREHOUSE HC_TRANSFORM_WH SET RESOURCE_MONITOR = HC_TRANSFORM_WH_MONITOR;
ALTER WAREHOUSE HC_ANALYTICS_WH SET RESOURCE_MONITOR = HC_ANALYTICS_WH_MONITOR;
ALTER WAREHOUSE HC_AI_WH SET RESOURCE_MONITOR = HC_AI_WH_MONITOR;

-- Verify
SHOW RESOURCE MONITORS LIKE 'HC_%';
