-- =============================================
-- 10_VERIFICATION.SQL
-- Healthcare Deployment Verification
-- =============================================

USE ROLE ACCOUNTADMIN;

-- Verify Databases
SELECT 'DATABASES' AS CHECK_TYPE, COUNT(*) AS COUNT 
FROM (SHOW DATABASES LIKE '%_DB');

-- Verify Roles
SELECT 'ROLES' AS CHECK_TYPE, COUNT(*) AS COUNT 
FROM (SHOW ROLES LIKE 'HC_%');

-- Verify Warehouses
SELECT 'WAREHOUSES' AS CHECK_TYPE, COUNT(*) AS COUNT 
FROM (SHOW WAREHOUSES LIKE 'HC_%');

-- Verify Resource Monitors
SELECT 'RESOURCE_MONITORS' AS CHECK_TYPE, COUNT(*) AS COUNT 
FROM (SHOW RESOURCE MONITORS LIKE 'HC_%');

-- Verify Monitoring Views
SELECT 'MONITORING_VIEWS' AS CHECK_TYPE, COUNT(*) AS COUNT 
FROM (SHOW VIEWS IN MONITORING_DB.MONITORING_SCHEMA);

-- Verify Audit Views
SELECT 'AUDIT_VIEWS' AS CHECK_TYPE, COUNT(*) AS COUNT 
FROM (SHOW VIEWS IN AUDIT_DB.AUDIT_SCHEMA);

-- Comprehensive Verification Query
SELECT 
    'Databases' AS OBJECT_TYPE,
    (SELECT COUNT(*) FROM (SHOW DATABASES LIKE '%_DB')) AS ACTUAL_COUNT,
    8 AS EXPECTED_COUNT,
    CASE WHEN (SELECT COUNT(*) FROM (SHOW DATABASES LIKE '%_DB')) >= 8 THEN '✓ PASS' ELSE '✗ FAIL' END AS STATUS
UNION ALL
SELECT 
    'Roles',
    (SELECT COUNT(*) FROM (SHOW ROLES LIKE 'HC_%')),
    6,
    CASE WHEN (SELECT COUNT(*) FROM (SHOW ROLES LIKE 'HC_%')) >= 6 THEN '✓ PASS' ELSE '✗ FAIL' END
UNION ALL
SELECT 
    'Warehouses',
    (SELECT COUNT(*) FROM (SHOW WAREHOUSES LIKE 'HC_%')),
    4,
    CASE WHEN (SELECT COUNT(*) FROM (SHOW WAREHOUSES LIKE 'HC_%')) >= 4 THEN '✓ PASS' ELSE '✗ FAIL' END;
