-- =============================================
-- 11_MEDALLION_ARCHITECTURE.SQL
-- Healthcare Data Pipeline
-- =============================================

USE ROLE ACCOUNTADMIN;

-- =============================================
-- BRONZE LAYER (RAW_DB)
-- =============================================
USE DATABASE RAW_DB;
USE SCHEMA RAW_SCHEMA;
USE WAREHOUSE HC_ETL_WH;

-- Patient Raw Table
CREATE OR REPLACE TABLE PATIENT_RAW (
    PATIENT_ID VARCHAR(10) PRIMARY KEY,
    NAME VARCHAR(100),
    AGE INTEGER,
    GENDER VARCHAR(1),
    ADMISSION_DATE DATE,
    DIAGNOSIS VARCHAR(50)
);

-- Insert 10,000 Patient Records
INSERT INTO PATIENT_RAW
SELECT 
    'P' || LPAD(SEQ4()::STRING, 5, '0') AS PATIENT_ID,
    'Patient_' || LPAD(SEQ4()::STRING, 5, '0') AS NAME,
    18 + MOD(RANDOM(), 73) AS AGE,
    CASE WHEN MOD(RANDOM(), 2) = 0 THEN 'M' ELSE 'F' END AS GENDER,
    DATEADD(DAY, -MOD(ABS(RANDOM()), 365), CURRENT_DATE()) AS ADMISSION_DATE,
    CASE MOD(ABS(RANDOM()), 4) 
        WHEN 0 THEN 'Cardiology'
        WHEN 1 THEN 'Neurology'
        WHEN 2 THEN 'Orthopedics'
        ELSE 'General'
    END AS DIAGNOSIS
FROM TABLE(GENERATOR(ROWCOUNT => 10000));

-- ICU Events Table
CREATE OR REPLACE TABLE ICU_EVENTS (
    EVENT_ID VARCHAR(10) PRIMARY KEY,
    PATIENT_ID VARCHAR(10),
    EVENT_TYPE VARCHAR(50),
    EVENT_TIMESTAMP TIMESTAMP,
    HEART_RATE INTEGER,
    OXYGEN_LEVEL INTEGER
);

-- Insert 50,000 ICU Events
INSERT INTO ICU_EVENTS
SELECT 
    'E' || LPAD(SEQ4()::STRING, 6, '0') AS EVENT_ID,
    'P' || LPAD(MOD(ABS(RANDOM()), 10000)::STRING, 5, '0') AS PATIENT_ID,
    CASE MOD(ABS(RANDOM()), 5)
        WHEN 0 THEN 'Vitals Check'
        WHEN 1 THEN 'Medication'
        WHEN 2 THEN 'Procedure'
        WHEN 3 THEN 'Alert'
        ELSE 'Transfer'
    END AS EVENT_TYPE,
    DATEADD(HOUR, -MOD(ABS(RANDOM()), 720), CURRENT_TIMESTAMP()) AS EVENT_TIMESTAMP,
    50 + MOD(ABS(RANDOM()), 101) AS HEART_RATE,
    80 + MOD(ABS(RANDOM()), 21) AS OXYGEN_LEVEL
FROM TABLE(GENERATOR(ROWCOUNT => 50000));

-- Billing Data Table
CREATE OR REPLACE TABLE BILLING_DATA (
    BILL_ID VARCHAR(10) PRIMARY KEY,
    PATIENT_ID VARCHAR(10),
    AMOUNT DECIMAL(10,2),
    BILL_DATE DATE,
    STATUS VARCHAR(20)
);

-- Insert 20,000 Billing Records
INSERT INTO BILLING_DATA
SELECT 
    'B' || LPAD(SEQ4()::STRING, 6, '0') AS BILL_ID,
    'P' || LPAD(MOD(ABS(RANDOM()), 10000)::STRING, 5, '0') AS PATIENT_ID,
    1000 + MOD(ABS(RANDOM()), 99000) AS AMOUNT,
    DATEADD(DAY, -MOD(ABS(RANDOM()), 365), CURRENT_DATE()) AS BILL_DATE,
    CASE MOD(ABS(RANDOM()), 3)
        WHEN 0 THEN 'PAID'
        WHEN 1 THEN 'PENDING'
        ELSE 'OVERDUE'
    END AS STATUS
FROM TABLE(GENERATOR(ROWCOUNT => 20000));

-- =============================================
-- SILVER LAYER (TRANSFORM_DB)
-- =============================================
USE DATABASE TRANSFORM_DB;
USE SCHEMA TRANSFORM_SCHEMA;
USE WAREHOUSE HC_TRANSFORM_WH;

-- Clean Patient Table
CREATE OR REPLACE TABLE CLEAN_PATIENT AS
SELECT 
    PATIENT_ID,
    NAME,
    AGE,
    GENDER,
    ADMISSION_DATE,
    DIAGNOSIS,
    LEFT(PATIENT_ID, 2) || '***' AS PATIENT_ID_MASKED,
    CURRENT_TIMESTAMP() AS ETL_TIMESTAMP
FROM RAW_DB.RAW_SCHEMA.PATIENT_RAW;

-- Clean ICU Events with Critical Flag
CREATE OR REPLACE TABLE CLEAN_ICU_EVENTS AS
SELECT 
    EVENT_ID,
    PATIENT_ID,
    EVENT_TYPE,
    EVENT_TIMESTAMP,
    HEART_RATE,
    OXYGEN_LEVEL,
    CASE 
        WHEN HEART_RATE < 60 OR HEART_RATE > 100 OR OXYGEN_LEVEL < 92 THEN TRUE
        ELSE FALSE
    END AS IS_CRITICAL,
    CURRENT_TIMESTAMP() AS ETL_TIMESTAMP
FROM RAW_DB.RAW_SCHEMA.ICU_EVENTS;

-- =============================================
-- GOLD LAYER (ANALYTICS_DB)
-- =============================================
USE DATABASE ANALYTICS_DB;
USE SCHEMA ANALYTICS_SCHEMA;
USE WAREHOUSE HC_ANALYTICS_WH;

-- Patient Analytics View
CREATE OR REPLACE TABLE PATIENT_ANALYTICS AS
SELECT 
    p.PATIENT_ID,
    p.NAME,
    p.AGE,
    p.GENDER,
    p.ADMISSION_DATE,
    p.DIAGNOSIS,
    COUNT(e.EVENT_ID) AS ICU_EVENT_COUNT,
    AVG(e.HEART_RATE) AS AVG_HEART_RATE,
    AVG(e.OXYGEN_LEVEL) AS AVG_OXYGEN_LEVEL,
    SUM(CASE WHEN e.IS_CRITICAL THEN 1 ELSE 0 END) AS CRITICAL_EVENT_COUNT
FROM TRANSFORM_DB.TRANSFORM_SCHEMA.CLEAN_PATIENT p
LEFT JOIN TRANSFORM_DB.TRANSFORM_SCHEMA.CLEAN_ICU_EVENTS e ON p.PATIENT_ID = e.PATIENT_ID
GROUP BY p.PATIENT_ID, p.NAME, p.AGE, p.GENDER, p.ADMISSION_DATE, p.DIAGNOSIS;

-- Billing Analytics
CREATE OR REPLACE TABLE BILLING_ANALYTICS AS
SELECT 
    PATIENT_ID,
    COUNT(*) AS TOTAL_BILLS,
    SUM(AMOUNT) AS TOTAL_AMOUNT,
    AVG(AMOUNT) AS AVG_BILL_AMOUNT,
    SUM(CASE WHEN STATUS = 'PAID' THEN AMOUNT ELSE 0 END) AS PAID_AMOUNT,
    SUM(CASE WHEN STATUS = 'PENDING' THEN AMOUNT ELSE 0 END) AS PENDING_AMOUNT,
    SUM(CASE WHEN STATUS = 'OVERDUE' THEN AMOUNT ELSE 0 END) AS OVERDUE_AMOUNT
FROM RAW_DB.RAW_SCHEMA.BILLING_DATA
GROUP BY PATIENT_ID;

-- Verify Record Counts
SELECT 'PATIENT_RAW' AS TABLE_NAME, COUNT(*) AS RECORDS FROM RAW_DB.RAW_SCHEMA.PATIENT_RAW
UNION ALL SELECT 'ICU_EVENTS', COUNT(*) FROM RAW_DB.RAW_SCHEMA.ICU_EVENTS
UNION ALL SELECT 'BILLING_DATA', COUNT(*) FROM RAW_DB.RAW_SCHEMA.BILLING_DATA
UNION ALL SELECT 'CLEAN_PATIENT', COUNT(*) FROM TRANSFORM_DB.TRANSFORM_SCHEMA.CLEAN_PATIENT
UNION ALL SELECT 'CLEAN_ICU_EVENTS', COUNT(*) FROM TRANSFORM_DB.TRANSFORM_SCHEMA.CLEAN_ICU_EVENTS
UNION ALL SELECT 'PATIENT_ANALYTICS', COUNT(*) FROM ANALYTICS_DB.ANALYTICS_SCHEMA.PATIENT_ANALYTICS
UNION ALL SELECT 'BILLING_ANALYTICS', COUNT(*) FROM ANALYTICS_DB.ANALYTICS_SCHEMA.BILLING_ANALYTICS;
