-- ============================================================================
-- PHASE 11: MEDALLION ARCHITECTURE
-- Healthcare Enterprise Data Hub
-- Priority: HIGH - Core Data Pipeline
-- ============================================================================
-- Author: DEVIKAPG
-- Account: tyb42779
-- Prerequisites: Phase 4 (Database Structure) must be complete
-- ============================================================================

USE ROLE ACCOUNTADMIN;
USE WAREHOUSE HC_ETL_WH;

-- ============================================================================
-- BRONZE LAYER (RAW_DB) - Raw Ingested Data
-- Priority: P1 - Foundation Layer
-- ============================================================================

USE DATABASE RAW_DB;
USE SCHEMA RAW_SCHEMA;

-- 1. PATIENT_RAW (10,000 records)
CREATE OR REPLACE TABLE PATIENT_RAW AS
SELECT
    'P' || LPAD(SEQ4()+1, 5, '0') AS PATIENT_ID,
    'Patient_' || LPAD(SEQ4()+1, 5, '0') AS NAME,
    UNIFORM(18, 90, RANDOM()) AS AGE,
    CASE WHEN UNIFORM(0,1,RANDOM()) < 0.5 THEN 'M' ELSE 'F' END AS GENDER,
    DATEADD(DAY, -UNIFORM(0, 365, RANDOM()), CURRENT_DATE) AS ADMISSION_DATE,
    CASE UNIFORM(1,5,RANDOM())
        WHEN 1 THEN 'Cardiology'
        WHEN 2 THEN 'Neurology'
        WHEN 3 THEN 'Pulmonology'
        WHEN 4 THEN 'Orthopedics'
        ELSE 'General'
    END AS DIAGNOSIS,
    LPAD(UNIFORM(100000000, 999999999, RANDOM())::STRING, 9, '0') AS SSN,
    'INS-' || LPAD(UNIFORM(10000000, 99999999, RANDOM())::STRING, 8, '0') AS INSURANCE_NO,
    '(' || LPAD(UNIFORM(200, 999, RANDOM())::STRING, 3, '0') || ') ' ||
        LPAD(UNIFORM(200, 999, RANDOM())::STRING, 3, '0') || '-' ||
        LPAD(UNIFORM(1000, 9999, RANDOM())::STRING, 4, '0') AS PHONE,
    CASE UNIFORM(1,4,RANDOM())
        WHEN 1 THEN 'North'
        WHEN 2 THEN 'South'
        WHEN 3 THEN 'East'
        ELSE 'West'
    END AS HOSPITAL_REGION,
    CURRENT_TIMESTAMP AS LOAD_TIMESTAMP
FROM TABLE(GENERATOR(ROWCOUNT => 10000));

-- 2. ICU_EVENTS (50,000 records)
CREATE OR REPLACE TABLE ICU_EVENTS AS
SELECT
    'E' || LPAD(SEQ4()+1, 6, '0') AS EVENT_ID,
    'P' || LPAD(UNIFORM(1, 10000, RANDOM()), 5, '0') AS PATIENT_ID,
    CASE UNIFORM(1,4,RANDOM())
        WHEN 1 THEN 'Vitals Check'
        WHEN 2 THEN 'Medication'
        WHEN 3 THEN 'Alert'
        ELSE 'Procedure'
    END AS EVENT_TYPE,
    DATEADD(HOUR, -UNIFORM(0, 720, RANDOM()), CURRENT_TIMESTAMP) AS EVENT_TIMESTAMP,
    UNIFORM(50, 150, RANDOM()) AS HEART_RATE,
    UNIFORM(80, 100, RANDOM()) AS OXYGEN_LEVEL,
    UNIFORM(90, 180, RANDOM()) AS SYSTOLIC_BP,
    UNIFORM(60, 110, RANDOM()) AS DIASTOLIC_BP,
    UNIFORM(96, 104, RANDOM())::DECIMAL(4,1) AS TEMPERATURE
FROM TABLE(GENERATOR(ROWCOUNT => 50000));

-- 3. BILLING_DATA (20,000 records)
CREATE OR REPLACE TABLE BILLING_DATA AS
SELECT
    'B' || LPAD(SEQ4()+1, 6, '0') AS BILL_ID,
    'P' || LPAD(UNIFORM(1, 10000, RANDOM()), 5, '0') AS PATIENT_ID,
    UNIFORM(500, 150000, RANDOM())::DECIMAL(12,2) AS BILL_AMOUNT,
    DATEADD(DAY, -UNIFORM(0, 180, RANDOM()), CURRENT_DATE) AS BILL_DATE,
    CASE UNIFORM(1,3,RANDOM())
        WHEN 1 THEN 'PAID'
        WHEN 2 THEN 'PENDING'
        ELSE 'OVERDUE'
    END AS PAYMENT_STATUS,
    CASE UNIFORM(1,5,RANDOM())
        WHEN 1 THEN 'Surgery'
        WHEN 2 THEN 'Medication'
        WHEN 3 THEN 'Lab Tests'
        WHEN 4 THEN 'Room Charges'
        ELSE 'Consultation'
    END AS SERVICE_TYPE
FROM TABLE(GENERATOR(ROWCOUNT => 20000));

-- 4. DEVICE_ALERTS (5,000 records)
CREATE OR REPLACE TABLE DEVICE_ALERTS AS
SELECT
    'D' || LPAD(SEQ4()+1, 5, '0') AS DEVICE_ID,
    'P' || LPAD(UNIFORM(1, 10000, RANDOM()), 5, '0') AS PATIENT_ID,
    CASE UNIFORM(1,4,RANDOM())
        WHEN 1 THEN 'Heart Monitor'
        WHEN 2 THEN 'Oxygen Sensor'
        WHEN 3 THEN 'BP Monitor'
        ELSE 'Glucose Monitor'
    END AS DEVICE_TYPE,
    CASE UNIFORM(1,4,RANDOM())
        WHEN 1 THEN 'Low Battery'
        WHEN 2 THEN 'Disconnected'
        WHEN 3 THEN 'Reading Anomaly'
        ELSE 'Calibration Required'
    END AS ALERT_TYPE,
    DATEADD(MINUTE, -UNIFORM(0, 10080, RANDOM()), CURRENT_TIMESTAMP) AS ALERT_TIMESTAMP,
    CASE UNIFORM(1,3,RANDOM())
        WHEN 1 THEN 'LOW'
        WHEN 2 THEN 'MEDIUM'
        ELSE 'HIGH'
    END AS SEVERITY
FROM TABLE(GENERATOR(ROWCOUNT => 5000));

-- Bronze Verification
SELECT 'BRONZE LAYER' AS LAYER, 
    (SELECT COUNT(*) FROM PATIENT_RAW) AS PATIENT_RAW,
    (SELECT COUNT(*) FROM ICU_EVENTS) AS ICU_EVENTS,
    (SELECT COUNT(*) FROM BILLING_DATA) AS BILLING_DATA,
    (SELECT COUNT(*) FROM DEVICE_ALERTS) AS DEVICE_ALERTS;

-- ============================================================================
-- SILVER LAYER (TRANSFORM_DB) - Cleaned & Transformed
-- Priority: P2 - Data Quality Layer
-- ============================================================================

USE DATABASE TRANSFORM_DB;
USE SCHEMA TRANSFORM_SCHEMA;

-- 1. CLEAN_PATIENT
CREATE OR REPLACE TABLE CLEAN_PATIENT AS
SELECT
    PATIENT_ID,
    NAME,
    AGE,
    GENDER,
    ADMISSION_DATE,
    DIAGNOSIS,
    HOSPITAL_REGION,
    LEFT(PATIENT_ID, 2) || '***' AS PATIENT_ID_MASKED,
    DATEDIFF(DAY, ADMISSION_DATE, CURRENT_DATE) AS DAYS_SINCE_ADMISSION,
    CASE
        WHEN AGE < 18 THEN 'Pediatric'
        WHEN AGE BETWEEN 18 AND 64 THEN 'Adult'
        ELSE 'Senior'
    END AS AGE_GROUP,
    CURRENT_TIMESTAMP AS ETL_TIMESTAMP
FROM RAW_DB.RAW_SCHEMA.PATIENT_RAW;

-- 2. CLEAN_ICU_EVENTS
CREATE OR REPLACE TABLE CLEAN_ICU_EVENTS AS
SELECT
    EVENT_ID,
    PATIENT_ID,
    EVENT_TYPE,
    EVENT_TIMESTAMP,
    HEART_RATE,
    OXYGEN_LEVEL,
    SYSTOLIC_BP,
    DIASTOLIC_BP,
    TEMPERATURE,
    CASE 
        WHEN HEART_RATE > 100 OR HEART_RATE < 60 THEN TRUE
        WHEN OXYGEN_LEVEL < 92 THEN TRUE
        WHEN SYSTOLIC_BP > 140 OR DIASTOLIC_BP > 90 THEN TRUE
        ELSE FALSE
    END AS IS_CRITICAL,
    CASE
        WHEN HEART_RATE > 120 OR OXYGEN_LEVEL < 88 THEN 'HIGH'
        WHEN HEART_RATE > 100 OR OXYGEN_LEVEL < 92 THEN 'MEDIUM'
        ELSE 'LOW'
    END AS ALERT_LEVEL,
    CURRENT_TIMESTAMP AS ETL_TIMESTAMP
FROM RAW_DB.RAW_SCHEMA.ICU_EVENTS;

-- Silver Verification
SELECT 'SILVER LAYER' AS LAYER,
    (SELECT COUNT(*) FROM CLEAN_PATIENT) AS CLEAN_PATIENT,
    (SELECT COUNT(*) FROM CLEAN_ICU_EVENTS) AS CLEAN_ICU_EVENTS;

-- ============================================================================
-- GOLD LAYER (ANALYTICS_DB) - Aggregated Analytics
-- Priority: P2 - Business Intelligence Layer
-- ============================================================================

USE DATABASE ANALYTICS_DB;
USE SCHEMA ANALYTICS_SCHEMA;

-- 1. PATIENT_ANALYTICS
CREATE OR REPLACE TABLE PATIENT_ANALYTICS AS
SELECT
    p.PATIENT_ID,
    p.NAME,
    p.AGE,
    p.AGE_GROUP,
    p.GENDER,
    p.ADMISSION_DATE,
    p.DIAGNOSIS,
    p.HOSPITAL_REGION,
    p.DAYS_SINCE_ADMISSION,
    COUNT(i.EVENT_ID) AS ICU_EVENT_COUNT,
    SUM(CASE WHEN i.IS_CRITICAL THEN 1 ELSE 0 END) AS CRITICAL_EVENT_COUNT,
    AVG(i.HEART_RATE) AS AVG_HEART_RATE,
    AVG(i.OXYGEN_LEVEL) AS AVG_OXYGEN_LEVEL,
    AVG(i.SYSTOLIC_BP) AS AVG_SYSTOLIC_BP,
    AVG(i.DIASTOLIC_BP) AS AVG_DIASTOLIC_BP,
    MIN(i.OXYGEN_LEVEL) AS MIN_OXYGEN_LEVEL,
    MAX(i.HEART_RATE) AS MAX_HEART_RATE
FROM TRANSFORM_DB.TRANSFORM_SCHEMA.CLEAN_PATIENT p
LEFT JOIN TRANSFORM_DB.TRANSFORM_SCHEMA.CLEAN_ICU_EVENTS i ON p.PATIENT_ID = i.PATIENT_ID
GROUP BY p.PATIENT_ID, p.NAME, p.AGE, p.AGE_GROUP, p.GENDER,
         p.ADMISSION_DATE, p.DIAGNOSIS, p.HOSPITAL_REGION, p.DAYS_SINCE_ADMISSION;

-- 2. BILLING_ANALYTICS
CREATE OR REPLACE TABLE BILLING_ANALYTICS AS
SELECT
    PATIENT_ID,
    COUNT(BILL_ID) AS TOTAL_BILLS,
    SUM(BILL_AMOUNT) AS TOTAL_AMOUNT,
    AVG(BILL_AMOUNT) AS AVG_BILL_AMOUNT,
    MAX(BILL_AMOUNT) AS MAX_BILL_AMOUNT,
    SUM(CASE WHEN PAYMENT_STATUS = 'PAID' THEN BILL_AMOUNT ELSE 0 END) AS PAID_AMOUNT,
    SUM(CASE WHEN PAYMENT_STATUS = 'PENDING' THEN BILL_AMOUNT ELSE 0 END) AS PENDING_AMOUNT,
    SUM(CASE WHEN PAYMENT_STATUS = 'OVERDUE' THEN BILL_AMOUNT ELSE 0 END) AS OVERDUE_AMOUNT,
    SUM(CASE WHEN PAYMENT_STATUS = 'PAID' THEN 1 ELSE 0 END) AS PAID_COUNT,
    SUM(CASE WHEN PAYMENT_STATUS = 'PENDING' THEN 1 ELSE 0 END) AS PENDING_COUNT,
    SUM(CASE WHEN PAYMENT_STATUS = 'OVERDUE' THEN 1 ELSE 0 END) AS OVERDUE_COUNT
FROM RAW_DB.RAW_SCHEMA.BILLING_DATA
GROUP BY PATIENT_ID;

-- Gold Verification
SELECT 'GOLD LAYER' AS LAYER,
    (SELECT COUNT(*) FROM PATIENT_ANALYTICS) AS PATIENT_ANALYTICS,
    (SELECT COUNT(*) FROM BILLING_ANALYTICS) AS BILLING_ANALYTICS;

-- ============================================================================
-- FINAL VERIFICATION - MEDALLION FLOW
-- ============================================================================

SELECT 'BRONZE' AS LAYER, 'PATIENT_RAW' AS TABLE_NAME, COUNT(*) AS ROWS FROM RAW_DB.RAW_SCHEMA.PATIENT_RAW
UNION ALL SELECT 'BRONZE', 'ICU_EVENTS', COUNT(*) FROM RAW_DB.RAW_SCHEMA.ICU_EVENTS
UNION ALL SELECT 'BRONZE', 'BILLING_DATA', COUNT(*) FROM RAW_DB.RAW_SCHEMA.BILLING_DATA
UNION ALL SELECT 'BRONZE', 'DEVICE_ALERTS', COUNT(*) FROM RAW_DB.RAW_SCHEMA.DEVICE_ALERTS
UNION ALL SELECT 'SILVER', 'CLEAN_PATIENT', COUNT(*) FROM TRANSFORM_DB.TRANSFORM_SCHEMA.CLEAN_PATIENT
UNION ALL SELECT 'SILVER', 'CLEAN_ICU_EVENTS', COUNT(*) FROM TRANSFORM_DB.TRANSFORM_SCHEMA.CLEAN_ICU_EVENTS
UNION ALL SELECT 'GOLD', 'PATIENT_ANALYTICS', COUNT(*) FROM ANALYTICS_DB.ANALYTICS_SCHEMA.PATIENT_ANALYTICS
UNION ALL SELECT 'GOLD', 'BILLING_ANALYTICS', COUNT(*) FROM ANALYTICS_DB.ANALYTICS_SCHEMA.BILLING_ANALYTICS
ORDER BY LAYER, TABLE_NAME;

-- ============================================================================
-- PHASE 11: MEDALLION ARCHITECTURE - COMPLETE
-- ============================================================================
-- Total Records: 163,608
--   Bronze: 85,000 (4 tables)
--   Silver: 60,000 (2 tables)
--   Gold: 18,608 (2 tables)
-- ============================================================================
