-- ============================================================================
-- DATA QUALITY VALIDATION FRAMEWORK
-- Healthcare Enterprise Data Hub - All Medallion Layers
-- 163K+ Records Quality Checks
-- ============================================================================

USE ROLE ACCOUNTADMIN;
USE WAREHOUSE COMPUTE_WH;

-- ============================================================================
-- CREATE DATA QUALITY DATABASE & SCHEMA
-- ============================================================================

CREATE DATABASE IF NOT EXISTS DATA_QUALITY_DB;
CREATE SCHEMA IF NOT EXISTS DATA_QUALITY_DB.DQ_SCHEMA;
USE DATABASE DATA_QUALITY_DB;
USE SCHEMA DQ_SCHEMA;

-- ============================================================================
-- DQ RESULTS TABLE - Store all validation results
-- ============================================================================

CREATE OR REPLACE TABLE DQ_VALIDATION_RESULTS (
    VALIDATION_ID STRING DEFAULT UUID_STRING(),
    VALIDATION_TIMESTAMP TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    LAYER STRING,
    TABLE_NAME STRING,
    CHECK_TYPE STRING,
    CHECK_NAME STRING,
    TOTAL_RECORDS NUMBER,
    FAILED_RECORDS NUMBER,
    PASS_RATE DECIMAL(5,2),
    STATUS STRING,
    DETAILS STRING
);

-- ============================================================================
-- ██████╗ ██████╗  ██████╗ ███╗   ██╗███████╗███████╗
-- ██╔══██╗██╔══██╗██╔═══██╗████╗  ██║╚══███╔╝██╔════╝
-- ██████╔╝██████╔╝██║   ██║██╔██╗ ██║  ███╔╝ █████╗  
-- ██╔══██╗██╔══██╗██║   ██║██║╚██╗██║ ███╔╝  ██╔══╝  
-- ██████╔╝██║  ██║╚██████╔╝██║ ╚████║███████╗███████╗
-- ╚═════╝ ╚═╝  ╚═╝ ╚═════╝ ╚═╝  ╚═══╝╚══════╝╚══════╝
-- BRONZE LAYER VALIDATIONS (RAW_DB)
-- ============================================================================

-- ----------------------------------------------------------------------------
-- B1: PATIENT_RAW - Null Value Checks
-- ----------------------------------------------------------------------------
INSERT INTO DQ_VALIDATION_RESULTS (LAYER, TABLE_NAME, CHECK_TYPE, CHECK_NAME, TOTAL_RECORDS, FAILED_RECORDS, PASS_RATE, STATUS, DETAILS)
SELECT
    'BRONZE' AS LAYER,
    'PATIENT_RAW' AS TABLE_NAME,
    'NULL_CHECK' AS CHECK_TYPE,
    'Patient ID Not Null' AS CHECK_NAME,
    COUNT(*) AS TOTAL_RECORDS,
    SUM(CASE WHEN PATIENT_ID IS NULL THEN 1 ELSE 0 END) AS FAILED_RECORDS,
    ROUND(100.0 - (SUM(CASE WHEN PATIENT_ID IS NULL THEN 1 ELSE 0 END) * 100.0 / COUNT(*)), 2) AS PASS_RATE,
    CASE WHEN SUM(CASE WHEN PATIENT_ID IS NULL THEN 1 ELSE 0 END) = 0 THEN 'PASS' ELSE 'FAIL' END AS STATUS,
    'Primary key null check' AS DETAILS
FROM RAW_DB.RAW_SCHEMA.PATIENT_RAW;

INSERT INTO DQ_VALIDATION_RESULTS (LAYER, TABLE_NAME, CHECK_TYPE, CHECK_NAME, TOTAL_RECORDS, FAILED_RECORDS, PASS_RATE, STATUS, DETAILS)
SELECT
    'BRONZE', 'PATIENT_RAW', 'NULL_CHECK', 'Name Not Null',
    COUNT(*),
    SUM(CASE WHEN NAME IS NULL THEN 1 ELSE 0 END),
    ROUND(100.0 - (SUM(CASE WHEN NAME IS NULL THEN 1 ELSE 0 END) * 100.0 / NULLIF(COUNT(*), 0)), 2),
    CASE WHEN SUM(CASE WHEN NAME IS NULL THEN 1 ELSE 0 END) = 0 THEN 'PASS' ELSE 'FAIL' END,
    'Patient name null check'
FROM RAW_DB.RAW_SCHEMA.PATIENT_RAW;

INSERT INTO DQ_VALIDATION_RESULTS (LAYER, TABLE_NAME, CHECK_TYPE, CHECK_NAME, TOTAL_RECORDS, FAILED_RECORDS, PASS_RATE, STATUS, DETAILS)
SELECT
    'BRONZE', 'PATIENT_RAW', 'NULL_CHECK', 'Age Not Null',
    COUNT(*),
    SUM(CASE WHEN AGE IS NULL THEN 1 ELSE 0 END),
    ROUND(100.0 - (SUM(CASE WHEN AGE IS NULL THEN 1 ELSE 0 END) * 100.0 / NULLIF(COUNT(*), 0)), 2),
    CASE WHEN SUM(CASE WHEN AGE IS NULL THEN 1 ELSE 0 END) = 0 THEN 'PASS' ELSE 'FAIL' END,
    'Patient age null check'
FROM RAW_DB.RAW_SCHEMA.PATIENT_RAW;

INSERT INTO DQ_VALIDATION_RESULTS (LAYER, TABLE_NAME, CHECK_TYPE, CHECK_NAME, TOTAL_RECORDS, FAILED_RECORDS, PASS_RATE, STATUS, DETAILS)
SELECT
    'BRONZE', 'PATIENT_RAW', 'NULL_CHECK', 'Diagnosis Not Null',
    COUNT(*),
    SUM(CASE WHEN DIAGNOSIS IS NULL THEN 1 ELSE 0 END),
    ROUND(100.0 - (SUM(CASE WHEN DIAGNOSIS IS NULL THEN 1 ELSE 0 END) * 100.0 / NULLIF(COUNT(*), 0)), 2),
    CASE WHEN SUM(CASE WHEN DIAGNOSIS IS NULL THEN 1 ELSE 0 END) = 0 THEN 'PASS' ELSE 'FAIL' END,
    'Diagnosis null check'
FROM RAW_DB.RAW_SCHEMA.PATIENT_RAW;

-- ----------------------------------------------------------------------------
-- B2: PATIENT_RAW - Duplicate Checks
-- ----------------------------------------------------------------------------
INSERT INTO DQ_VALIDATION_RESULTS (LAYER, TABLE_NAME, CHECK_TYPE, CHECK_NAME, TOTAL_RECORDS, FAILED_RECORDS, PASS_RATE, STATUS, DETAILS)
SELECT
    'BRONZE', 'PATIENT_RAW', 'DUPLICATE_CHECK', 'Unique Patient ID',
    COUNT(*),
    COUNT(*) - COUNT(DISTINCT PATIENT_ID),
    ROUND(100.0 * COUNT(DISTINCT PATIENT_ID) / NULLIF(COUNT(*), 0), 2),
    CASE WHEN COUNT(*) = COUNT(DISTINCT PATIENT_ID) THEN 'PASS' ELSE 'FAIL' END,
    'Duplicate patient ID check'
FROM RAW_DB.RAW_SCHEMA.PATIENT_RAW;

-- ----------------------------------------------------------------------------
-- B3: PATIENT_RAW - Schema/Data Type Validation
-- ----------------------------------------------------------------------------
INSERT INTO DQ_VALIDATION_RESULTS (LAYER, TABLE_NAME, CHECK_TYPE, CHECK_NAME, TOTAL_RECORDS, FAILED_RECORDS, PASS_RATE, STATUS, DETAILS)
SELECT
    'BRONZE', 'PATIENT_RAW', 'SCHEMA_CHECK', 'Age Range Valid (0-120)',
    COUNT(*),
    SUM(CASE WHEN AGE < 0 OR AGE > 120 THEN 1 ELSE 0 END),
    ROUND(100.0 - (SUM(CASE WHEN AGE < 0 OR AGE > 120 THEN 1 ELSE 0 END) * 100.0 / NULLIF(COUNT(*), 0)), 2),
    CASE WHEN SUM(CASE WHEN AGE < 0 OR AGE > 120 THEN 1 ELSE 0 END) = 0 THEN 'PASS' ELSE 'FAIL' END,
    'Valid age range check'
FROM RAW_DB.RAW_SCHEMA.PATIENT_RAW;

INSERT INTO DQ_VALIDATION_RESULTS (LAYER, TABLE_NAME, CHECK_TYPE, CHECK_NAME, TOTAL_RECORDS, FAILED_RECORDS, PASS_RATE, STATUS, DETAILS)
SELECT
    'BRONZE', 'PATIENT_RAW', 'SCHEMA_CHECK', 'Valid Gender Values',
    COUNT(*),
    SUM(CASE WHEN GENDER NOT IN ('M', 'F') THEN 1 ELSE 0 END),
    ROUND(100.0 - (SUM(CASE WHEN GENDER NOT IN ('M', 'F') THEN 1 ELSE 0 END) * 100.0 / NULLIF(COUNT(*), 0)), 2),
    CASE WHEN SUM(CASE WHEN GENDER NOT IN ('M', 'F') THEN 1 ELSE 0 END) = 0 THEN 'PASS' ELSE 'FAIL' END,
    'Gender value validation'
FROM RAW_DB.RAW_SCHEMA.PATIENT_RAW;

INSERT INTO DQ_VALIDATION_RESULTS (LAYER, TABLE_NAME, CHECK_TYPE, CHECK_NAME, TOTAL_RECORDS, FAILED_RECORDS, PASS_RATE, STATUS, DETAILS)
SELECT
    'BRONZE', 'PATIENT_RAW', 'SCHEMA_CHECK', 'Valid Diagnosis Values',
    COUNT(*),
    SUM(CASE WHEN DIAGNOSIS NOT IN ('Cardiology', 'Neurology', 'Pulmonology', 'Orthopedics', 'General') THEN 1 ELSE 0 END),
    ROUND(100.0 - (SUM(CASE WHEN DIAGNOSIS NOT IN ('Cardiology', 'Neurology', 'Pulmonology', 'Orthopedics', 'General') THEN 1 ELSE 0 END) * 100.0 / NULLIF(COUNT(*), 0)), 2),
    CASE WHEN SUM(CASE WHEN DIAGNOSIS NOT IN ('Cardiology', 'Neurology', 'Pulmonology', 'Orthopedics', 'General') THEN 1 ELSE 0 END) = 0 THEN 'PASS' ELSE 'FAIL' END,
    'Diagnosis enum validation'
FROM RAW_DB.RAW_SCHEMA.PATIENT_RAW;

INSERT INTO DQ_VALIDATION_RESULTS (LAYER, TABLE_NAME, CHECK_TYPE, CHECK_NAME, TOTAL_RECORDS, FAILED_RECORDS, PASS_RATE, STATUS, DETAILS)
SELECT
    'BRONZE', 'PATIENT_RAW', 'SCHEMA_CHECK', 'Valid Region Values',
    COUNT(*),
    SUM(CASE WHEN HOSPITAL_REGION NOT IN ('North', 'South', 'East', 'West') THEN 1 ELSE 0 END),
    ROUND(100.0 - (SUM(CASE WHEN HOSPITAL_REGION NOT IN ('North', 'South', 'East', 'West') THEN 1 ELSE 0 END) * 100.0 / NULLIF(COUNT(*), 0)), 2),
    CASE WHEN SUM(CASE WHEN HOSPITAL_REGION NOT IN ('North', 'South', 'East', 'West') THEN 1 ELSE 0 END) = 0 THEN 'PASS' ELSE 'FAIL' END,
    'Region enum validation'
FROM RAW_DB.RAW_SCHEMA.PATIENT_RAW;

INSERT INTO DQ_VALIDATION_RESULTS (LAYER, TABLE_NAME, CHECK_TYPE, CHECK_NAME, TOTAL_RECORDS, FAILED_RECORDS, PASS_RATE, STATUS, DETAILS)
SELECT
    'BRONZE', 'PATIENT_RAW', 'SCHEMA_CHECK', 'Admission Date Not Future',
    COUNT(*),
    SUM(CASE WHEN ADMISSION_DATE > CURRENT_DATE THEN 1 ELSE 0 END),
    ROUND(100.0 - (SUM(CASE WHEN ADMISSION_DATE > CURRENT_DATE THEN 1 ELSE 0 END) * 100.0 / NULLIF(COUNT(*), 0)), 2),
    CASE WHEN SUM(CASE WHEN ADMISSION_DATE > CURRENT_DATE THEN 1 ELSE 0 END) = 0 THEN 'PASS' ELSE 'FAIL' END,
    'Future date validation'
FROM RAW_DB.RAW_SCHEMA.PATIENT_RAW;

-- ----------------------------------------------------------------------------
-- B4: ICU_EVENTS - Null & Duplicate Checks
-- ----------------------------------------------------------------------------
INSERT INTO DQ_VALIDATION_RESULTS (LAYER, TABLE_NAME, CHECK_TYPE, CHECK_NAME, TOTAL_RECORDS, FAILED_RECORDS, PASS_RATE, STATUS, DETAILS)
SELECT
    'BRONZE', 'ICU_EVENTS', 'NULL_CHECK', 'Event ID Not Null',
    COUNT(*),
    SUM(CASE WHEN EVENT_ID IS NULL THEN 1 ELSE 0 END),
    ROUND(100.0 - (SUM(CASE WHEN EVENT_ID IS NULL THEN 1 ELSE 0 END) * 100.0 / NULLIF(COUNT(*), 0)), 2),
    CASE WHEN SUM(CASE WHEN EVENT_ID IS NULL THEN 1 ELSE 0 END) = 0 THEN 'PASS' ELSE 'FAIL' END,
    'Event ID null check'
FROM RAW_DB.RAW_SCHEMA.ICU_EVENTS;

INSERT INTO DQ_VALIDATION_RESULTS (LAYER, TABLE_NAME, CHECK_TYPE, CHECK_NAME, TOTAL_RECORDS, FAILED_RECORDS, PASS_RATE, STATUS, DETAILS)
SELECT
    'BRONZE', 'ICU_EVENTS', 'NULL_CHECK', 'Patient ID Not Null',
    COUNT(*),
    SUM(CASE WHEN PATIENT_ID IS NULL THEN 1 ELSE 0 END),
    ROUND(100.0 - (SUM(CASE WHEN PATIENT_ID IS NULL THEN 1 ELSE 0 END) * 100.0 / NULLIF(COUNT(*), 0)), 2),
    CASE WHEN SUM(CASE WHEN PATIENT_ID IS NULL THEN 1 ELSE 0 END) = 0 THEN 'PASS' ELSE 'FAIL' END,
    'Patient ID null check'
FROM RAW_DB.RAW_SCHEMA.ICU_EVENTS;

INSERT INTO DQ_VALIDATION_RESULTS (LAYER, TABLE_NAME, CHECK_TYPE, CHECK_NAME, TOTAL_RECORDS, FAILED_RECORDS, PASS_RATE, STATUS, DETAILS)
SELECT
    'BRONZE', 'ICU_EVENTS', 'DUPLICATE_CHECK', 'Unique Event ID',
    COUNT(*),
    COUNT(*) - COUNT(DISTINCT EVENT_ID),
    ROUND(100.0 * COUNT(DISTINCT EVENT_ID) / NULLIF(COUNT(*), 0), 2),
    CASE WHEN COUNT(*) = COUNT(DISTINCT EVENT_ID) THEN 'PASS' ELSE 'FAIL' END,
    'Duplicate event ID check'
FROM RAW_DB.RAW_SCHEMA.ICU_EVENTS;

INSERT INTO DQ_VALIDATION_RESULTS (LAYER, TABLE_NAME, CHECK_TYPE, CHECK_NAME, TOTAL_RECORDS, FAILED_RECORDS, PASS_RATE, STATUS, DETAILS)
SELECT
    'BRONZE', 'ICU_EVENTS', 'SCHEMA_CHECK', 'Heart Rate Valid (30-200)',
    COUNT(*),
    SUM(CASE WHEN HEART_RATE < 30 OR HEART_RATE > 200 THEN 1 ELSE 0 END),
    ROUND(100.0 - (SUM(CASE WHEN HEART_RATE < 30 OR HEART_RATE > 200 THEN 1 ELSE 0 END) * 100.0 / NULLIF(COUNT(*), 0)), 2),
    CASE WHEN SUM(CASE WHEN HEART_RATE < 30 OR HEART_RATE > 200 THEN 1 ELSE 0 END) = 0 THEN 'PASS' ELSE 'FAIL' END,
    'Heart rate range validation'
FROM RAW_DB.RAW_SCHEMA.ICU_EVENTS;

INSERT INTO DQ_VALIDATION_RESULTS (LAYER, TABLE_NAME, CHECK_TYPE, CHECK_NAME, TOTAL_RECORDS, FAILED_RECORDS, PASS_RATE, STATUS, DETAILS)
SELECT
    'BRONZE', 'ICU_EVENTS', 'SCHEMA_CHECK', 'Oxygen Level Valid (0-100)',
    COUNT(*),
    SUM(CASE WHEN OXYGEN_LEVEL < 0 OR OXYGEN_LEVEL > 100 THEN 1 ELSE 0 END),
    ROUND(100.0 - (SUM(CASE WHEN OXYGEN_LEVEL < 0 OR OXYGEN_LEVEL > 100 THEN 1 ELSE 0 END) * 100.0 / NULLIF(COUNT(*), 0)), 2),
    CASE WHEN SUM(CASE WHEN OXYGEN_LEVEL < 0 OR OXYGEN_LEVEL > 100 THEN 1 ELSE 0 END) = 0 THEN 'PASS' ELSE 'FAIL' END,
    'Oxygen level range validation'
FROM RAW_DB.RAW_SCHEMA.ICU_EVENTS;

-- ----------------------------------------------------------------------------
-- B5: BILLING_DATA - Null, Duplicate & Schema Checks
-- ----------------------------------------------------------------------------
INSERT INTO DQ_VALIDATION_RESULTS (LAYER, TABLE_NAME, CHECK_TYPE, CHECK_NAME, TOTAL_RECORDS, FAILED_RECORDS, PASS_RATE, STATUS, DETAILS)
SELECT
    'BRONZE', 'BILLING_DATA', 'NULL_CHECK', 'Bill ID Not Null',
    COUNT(*),
    SUM(CASE WHEN BILL_ID IS NULL THEN 1 ELSE 0 END),
    ROUND(100.0 - (SUM(CASE WHEN BILL_ID IS NULL THEN 1 ELSE 0 END) * 100.0 / NULLIF(COUNT(*), 0)), 2),
    CASE WHEN SUM(CASE WHEN BILL_ID IS NULL THEN 1 ELSE 0 END) = 0 THEN 'PASS' ELSE 'FAIL' END,
    'Bill ID null check'
FROM RAW_DB.RAW_SCHEMA.BILLING_DATA;

INSERT INTO DQ_VALIDATION_RESULTS (LAYER, TABLE_NAME, CHECK_TYPE, CHECK_NAME, TOTAL_RECORDS, FAILED_RECORDS, PASS_RATE, STATUS, DETAILS)
SELECT
    'BRONZE', 'BILLING_DATA', 'DUPLICATE_CHECK', 'Unique Bill ID',
    COUNT(*),
    COUNT(*) - COUNT(DISTINCT BILL_ID),
    ROUND(100.0 * COUNT(DISTINCT BILL_ID) / NULLIF(COUNT(*), 0), 2),
    CASE WHEN COUNT(*) = COUNT(DISTINCT BILL_ID) THEN 'PASS' ELSE 'FAIL' END,
    'Duplicate bill ID check'
FROM RAW_DB.RAW_SCHEMA.BILLING_DATA;

INSERT INTO DQ_VALIDATION_RESULTS (LAYER, TABLE_NAME, CHECK_TYPE, CHECK_NAME, TOTAL_RECORDS, FAILED_RECORDS, PASS_RATE, STATUS, DETAILS)
SELECT
    'BRONZE', 'BILLING_DATA', 'SCHEMA_CHECK', 'Bill Amount Positive',
    COUNT(*),
    SUM(CASE WHEN BILL_AMOUNT <= 0 THEN 1 ELSE 0 END),
    ROUND(100.0 - (SUM(CASE WHEN BILL_AMOUNT <= 0 THEN 1 ELSE 0 END) * 100.0 / NULLIF(COUNT(*), 0)), 2),
    CASE WHEN SUM(CASE WHEN BILL_AMOUNT <= 0 THEN 1 ELSE 0 END) = 0 THEN 'PASS' ELSE 'FAIL' END,
    'Positive amount validation'
FROM RAW_DB.RAW_SCHEMA.BILLING_DATA;

INSERT INTO DQ_VALIDATION_RESULTS (LAYER, TABLE_NAME, CHECK_TYPE, CHECK_NAME, TOTAL_RECORDS, FAILED_RECORDS, PASS_RATE, STATUS, DETAILS)
SELECT
    'BRONZE', 'BILLING_DATA', 'SCHEMA_CHECK', 'Valid Payment Status',
    COUNT(*),
    SUM(CASE WHEN PAYMENT_STATUS NOT IN ('PAID', 'PENDING', 'OVERDUE') THEN 1 ELSE 0 END),
    ROUND(100.0 - (SUM(CASE WHEN PAYMENT_STATUS NOT IN ('PAID', 'PENDING', 'OVERDUE') THEN 1 ELSE 0 END) * 100.0 / NULLIF(COUNT(*), 0)), 2),
    CASE WHEN SUM(CASE WHEN PAYMENT_STATUS NOT IN ('PAID', 'PENDING', 'OVERDUE') THEN 1 ELSE 0 END) = 0 THEN 'PASS' ELSE 'FAIL' END,
    'Payment status enum validation'
FROM RAW_DB.RAW_SCHEMA.BILLING_DATA;

-- ----------------------------------------------------------------------------
-- B6: DEVICE_ALERTS - Null, Duplicate & Schema Checks
-- ----------------------------------------------------------------------------
INSERT INTO DQ_VALIDATION_RESULTS (LAYER, TABLE_NAME, CHECK_TYPE, CHECK_NAME, TOTAL_RECORDS, FAILED_RECORDS, PASS_RATE, STATUS, DETAILS)
SELECT
    'BRONZE', 'DEVICE_ALERTS', 'NULL_CHECK', 'Device ID Not Null',
    COUNT(*),
    SUM(CASE WHEN DEVICE_ID IS NULL THEN 1 ELSE 0 END),
    ROUND(100.0 - (SUM(CASE WHEN DEVICE_ID IS NULL THEN 1 ELSE 0 END) * 100.0 / NULLIF(COUNT(*), 0)), 2),
    CASE WHEN SUM(CASE WHEN DEVICE_ID IS NULL THEN 1 ELSE 0 END) = 0 THEN 'PASS' ELSE 'FAIL' END,
    'Device ID null check'
FROM RAW_DB.RAW_SCHEMA.DEVICE_ALERTS;

INSERT INTO DQ_VALIDATION_RESULTS (LAYER, TABLE_NAME, CHECK_TYPE, CHECK_NAME, TOTAL_RECORDS, FAILED_RECORDS, PASS_RATE, STATUS, DETAILS)
SELECT
    'BRONZE', 'DEVICE_ALERTS', 'SCHEMA_CHECK', 'Valid Severity Values',
    COUNT(*),
    SUM(CASE WHEN SEVERITY NOT IN ('LOW', 'MEDIUM', 'HIGH') THEN 1 ELSE 0 END),
    ROUND(100.0 - (SUM(CASE WHEN SEVERITY NOT IN ('LOW', 'MEDIUM', 'HIGH') THEN 1 ELSE 0 END) * 100.0 / NULLIF(COUNT(*), 0)), 2),
    CASE WHEN SUM(CASE WHEN SEVERITY NOT IN ('LOW', 'MEDIUM', 'HIGH') THEN 1 ELSE 0 END) = 0 THEN 'PASS' ELSE 'FAIL' END,
    'Severity enum validation'
FROM RAW_DB.RAW_SCHEMA.DEVICE_ALERTS;

-- ============================================================================
-- ███████╗██╗██╗    ██╗   ██╗███████╗██████╗ 
-- ██╔════╝██║██║    ██║   ██║██╔════╝██╔══██╗
-- ███████╗██║██║    ██║   ██║█████╗  ██████╔╝
-- ╚════██║██║██║    ╚██╗ ██╔╝██╔══╝  ██╔══██╗
-- ███████║██║███████╗╚████╔╝ ███████╗██║  ██║
-- ╚══════╝╚═╝╚══════╝ ╚═══╝  ╚══════╝╚═╝  ╚═╝
-- SILVER LAYER VALIDATIONS (TRANSFORM_DB)
-- ============================================================================

-- ----------------------------------------------------------------------------
-- S1: CLEAN_PATIENT - Null Checks
-- ----------------------------------------------------------------------------
INSERT INTO DQ_VALIDATION_RESULTS (LAYER, TABLE_NAME, CHECK_TYPE, CHECK_NAME, TOTAL_RECORDS, FAILED_RECORDS, PASS_RATE, STATUS, DETAILS)
SELECT
    'SILVER', 'CLEAN_PATIENT', 'NULL_CHECK', 'Patient ID Not Null',
    COUNT(*),
    SUM(CASE WHEN PATIENT_ID IS NULL THEN 1 ELSE 0 END),
    ROUND(100.0 - (SUM(CASE WHEN PATIENT_ID IS NULL THEN 1 ELSE 0 END) * 100.0 / NULLIF(COUNT(*), 0)), 2),
    CASE WHEN SUM(CASE WHEN PATIENT_ID IS NULL THEN 1 ELSE 0 END) = 0 THEN 'PASS' ELSE 'FAIL' END,
    'Primary key null check'
FROM TRANSFORM_DB.TRANSFORM_SCHEMA.CLEAN_PATIENT;

INSERT INTO DQ_VALIDATION_RESULTS (LAYER, TABLE_NAME, CHECK_TYPE, CHECK_NAME, TOTAL_RECORDS, FAILED_RECORDS, PASS_RATE, STATUS, DETAILS)
SELECT
    'SILVER', 'CLEAN_PATIENT', 'NULL_CHECK', 'Age Group Not Null',
    COUNT(*),
    SUM(CASE WHEN AGE_GROUP IS NULL THEN 1 ELSE 0 END),
    ROUND(100.0 - (SUM(CASE WHEN AGE_GROUP IS NULL THEN 1 ELSE 0 END) * 100.0 / NULLIF(COUNT(*), 0)), 2),
    CASE WHEN SUM(CASE WHEN AGE_GROUP IS NULL THEN 1 ELSE 0 END) = 0 THEN 'PASS' ELSE 'FAIL' END,
    'Derived column null check'
FROM TRANSFORM_DB.TRANSFORM_SCHEMA.CLEAN_PATIENT;

-- ----------------------------------------------------------------------------
-- S2: CLEAN_PATIENT - Duplicate Checks
-- ----------------------------------------------------------------------------
INSERT INTO DQ_VALIDATION_RESULTS (LAYER, TABLE_NAME, CHECK_TYPE, CHECK_NAME, TOTAL_RECORDS, FAILED_RECORDS, PASS_RATE, STATUS, DETAILS)
SELECT
    'SILVER', 'CLEAN_PATIENT', 'DUPLICATE_CHECK', 'Unique Patient ID',
    COUNT(*),
    COUNT(*) - COUNT(DISTINCT PATIENT_ID),
    ROUND(100.0 * COUNT(DISTINCT PATIENT_ID) / NULLIF(COUNT(*), 0), 2),
    CASE WHEN COUNT(*) = COUNT(DISTINCT PATIENT_ID) THEN 'PASS' ELSE 'FAIL' END,
    'Duplicate patient ID check'
FROM TRANSFORM_DB.TRANSFORM_SCHEMA.CLEAN_PATIENT;

-- ----------------------------------------------------------------------------
-- S3: CLEAN_PATIENT - Schema Validation
-- ----------------------------------------------------------------------------
INSERT INTO DQ_VALIDATION_RESULTS (LAYER, TABLE_NAME, CHECK_TYPE, CHECK_NAME, TOTAL_RECORDS, FAILED_RECORDS, PASS_RATE, STATUS, DETAILS)
SELECT
    'SILVER', 'CLEAN_PATIENT', 'SCHEMA_CHECK', 'Valid Age Group Values',
    COUNT(*),
    SUM(CASE WHEN AGE_GROUP NOT IN ('Pediatric', 'Adult', 'Senior') THEN 1 ELSE 0 END),
    ROUND(100.0 - (SUM(CASE WHEN AGE_GROUP NOT IN ('Pediatric', 'Adult', 'Senior') THEN 1 ELSE 0 END) * 100.0 / NULLIF(COUNT(*), 0)), 2),
    CASE WHEN SUM(CASE WHEN AGE_GROUP NOT IN ('Pediatric', 'Adult', 'Senior') THEN 1 ELSE 0 END) = 0 THEN 'PASS' ELSE 'FAIL' END,
    'Age group enum validation'
FROM TRANSFORM_DB.TRANSFORM_SCHEMA.CLEAN_PATIENT;

INSERT INTO DQ_VALIDATION_RESULTS (LAYER, TABLE_NAME, CHECK_TYPE, CHECK_NAME, TOTAL_RECORDS, FAILED_RECORDS, PASS_RATE, STATUS, DETAILS)
SELECT
    'SILVER', 'CLEAN_PATIENT', 'SCHEMA_CHECK', 'Days Since Admission Non-Negative',
    COUNT(*),
    SUM(CASE WHEN DAYS_SINCE_ADMISSION < 0 THEN 1 ELSE 0 END),
    ROUND(100.0 - (SUM(CASE WHEN DAYS_SINCE_ADMISSION < 0 THEN 1 ELSE 0 END) * 100.0 / NULLIF(COUNT(*), 0)), 2),
    CASE WHEN SUM(CASE WHEN DAYS_SINCE_ADMISSION < 0 THEN 1 ELSE 0 END) = 0 THEN 'PASS' ELSE 'FAIL' END,
    'Non-negative days validation'
FROM TRANSFORM_DB.TRANSFORM_SCHEMA.CLEAN_PATIENT;

-- ----------------------------------------------------------------------------
-- S4: CLEAN_PATIENT - Referential Integrity (Bronze to Silver)
-- ----------------------------------------------------------------------------
INSERT INTO DQ_VALIDATION_RESULTS (LAYER, TABLE_NAME, CHECK_TYPE, CHECK_NAME, TOTAL_RECORDS, FAILED_RECORDS, PASS_RATE, STATUS, DETAILS)
SELECT
    'SILVER', 'CLEAN_PATIENT', 'REFERENTIAL_INTEGRITY', 'Record Count Match Bronze',
    (SELECT COUNT(*) FROM TRANSFORM_DB.TRANSFORM_SCHEMA.CLEAN_PATIENT) AS SILVER_COUNT,
    ABS((SELECT COUNT(*) FROM TRANSFORM_DB.TRANSFORM_SCHEMA.CLEAN_PATIENT) - 
        (SELECT COUNT(*) FROM RAW_DB.RAW_SCHEMA.PATIENT_RAW)) AS DIFF,
    CASE WHEN (SELECT COUNT(*) FROM TRANSFORM_DB.TRANSFORM_SCHEMA.CLEAN_PATIENT) = 
              (SELECT COUNT(*) FROM RAW_DB.RAW_SCHEMA.PATIENT_RAW) THEN 100.00 ELSE 0.00 END,
    CASE WHEN (SELECT COUNT(*) FROM TRANSFORM_DB.TRANSFORM_SCHEMA.CLEAN_PATIENT) = 
              (SELECT COUNT(*) FROM RAW_DB.RAW_SCHEMA.PATIENT_RAW) THEN 'PASS' ELSE 'FAIL' END,
    'Bronze to Silver record count validation';

-- ----------------------------------------------------------------------------
-- S5: CLEAN_ICU_EVENTS - Null & Schema Checks
-- ----------------------------------------------------------------------------
INSERT INTO DQ_VALIDATION_RESULTS (LAYER, TABLE_NAME, CHECK_TYPE, CHECK_NAME, TOTAL_RECORDS, FAILED_RECORDS, PASS_RATE, STATUS, DETAILS)
SELECT
    'SILVER', 'CLEAN_ICU_EVENTS', 'NULL_CHECK', 'Event ID Not Null',
    COUNT(*),
    SUM(CASE WHEN EVENT_ID IS NULL THEN 1 ELSE 0 END),
    ROUND(100.0 - (SUM(CASE WHEN EVENT_ID IS NULL THEN 1 ELSE 0 END) * 100.0 / NULLIF(COUNT(*), 0)), 2),
    CASE WHEN SUM(CASE WHEN EVENT_ID IS NULL THEN 1 ELSE 0 END) = 0 THEN 'PASS' ELSE 'FAIL' END,
    'Event ID null check'
FROM TRANSFORM_DB.TRANSFORM_SCHEMA.CLEAN_ICU_EVENTS;

INSERT INTO DQ_VALIDATION_RESULTS (LAYER, TABLE_NAME, CHECK_TYPE, CHECK_NAME, TOTAL_RECORDS, FAILED_RECORDS, PASS_RATE, STATUS, DETAILS)
SELECT
    'SILVER', 'CLEAN_ICU_EVENTS', 'SCHEMA_CHECK', 'Valid Alert Level',
    COUNT(*),
    SUM(CASE WHEN ALERT_LEVEL NOT IN ('LOW', 'MEDIUM', 'HIGH') THEN 1 ELSE 0 END),
    ROUND(100.0 - (SUM(CASE WHEN ALERT_LEVEL NOT IN ('LOW', 'MEDIUM', 'HIGH') THEN 1 ELSE 0 END) * 100.0 / NULLIF(COUNT(*), 0)), 2),
    CASE WHEN SUM(CASE WHEN ALERT_LEVEL NOT IN ('LOW', 'MEDIUM', 'HIGH') THEN 1 ELSE 0 END) = 0 THEN 'PASS' ELSE 'FAIL' END,
    'Alert level enum validation'
FROM TRANSFORM_DB.TRANSFORM_SCHEMA.CLEAN_ICU_EVENTS;

INSERT INTO DQ_VALIDATION_RESULTS (LAYER, TABLE_NAME, CHECK_TYPE, CHECK_NAME, TOTAL_RECORDS, FAILED_RECORDS, PASS_RATE, STATUS, DETAILS)
SELECT
    'SILVER', 'CLEAN_ICU_EVENTS', 'SCHEMA_CHECK', 'Is Critical Boolean Valid',
    COUNT(*),
    SUM(CASE WHEN IS_CRITICAL NOT IN (TRUE, FALSE) THEN 1 ELSE 0 END),
    ROUND(100.0 - (SUM(CASE WHEN IS_CRITICAL NOT IN (TRUE, FALSE) THEN 1 ELSE 0 END) * 100.0 / NULLIF(COUNT(*), 0)), 2),
    CASE WHEN SUM(CASE WHEN IS_CRITICAL NOT IN (TRUE, FALSE) THEN 1 ELSE 0 END) = 0 THEN 'PASS' ELSE 'FAIL' END,
    'Boolean field validation'
FROM TRANSFORM_DB.TRANSFORM_SCHEMA.CLEAN_ICU_EVENTS;

-- ============================================================================
--  ██████╗  ██████╗ ██╗     ██████╗ 
-- ██╔════╝ ██╔═══██╗██║     ██╔══██╗
-- ██║  ███╗██║   ██║██║     ██║  ██║
-- ██║   ██║██║   ██║██║     ██║  ██║
-- ╚██████╔╝╚██████╔╝███████╗██████╔╝
--  ╚═════╝  ╚═════╝ ╚══════╝╚═════╝ 
-- GOLD LAYER VALIDATIONS (ANALYTICS_DB)
-- ============================================================================

-- ----------------------------------------------------------------------------
-- G1: PATIENT_ANALYTICS - Null Checks
-- ----------------------------------------------------------------------------
INSERT INTO DQ_VALIDATION_RESULTS (LAYER, TABLE_NAME, CHECK_TYPE, CHECK_NAME, TOTAL_RECORDS, FAILED_RECORDS, PASS_RATE, STATUS, DETAILS)
SELECT
    'GOLD', 'PATIENT_ANALYTICS', 'NULL_CHECK', 'Patient ID Not Null',
    COUNT(*),
    SUM(CASE WHEN PATIENT_ID IS NULL THEN 1 ELSE 0 END),
    ROUND(100.0 - (SUM(CASE WHEN PATIENT_ID IS NULL THEN 1 ELSE 0 END) * 100.0 / NULLIF(COUNT(*), 0)), 2),
    CASE WHEN SUM(CASE WHEN PATIENT_ID IS NULL THEN 1 ELSE 0 END) = 0 THEN 'PASS' ELSE 'FAIL' END,
    'Primary key null check'
FROM ANALYTICS_DB.ANALYTICS_SCHEMA.PATIENT_ANALYTICS;

INSERT INTO DQ_VALIDATION_RESULTS (LAYER, TABLE_NAME, CHECK_TYPE, CHECK_NAME, TOTAL_RECORDS, FAILED_RECORDS, PASS_RATE, STATUS, DETAILS)
SELECT
    'GOLD', 'PATIENT_ANALYTICS', 'NULL_CHECK', 'ICU Event Count Not Null',
    COUNT(*),
    SUM(CASE WHEN TOTAL_ICU_EVENTS IS NULL THEN 1 ELSE 0 END),
    ROUND(100.0 - (SUM(CASE WHEN TOTAL_ICU_EVENTS IS NULL THEN 1 ELSE 0 END) * 100.0 / NULLIF(COUNT(*), 0)), 2),
    CASE WHEN SUM(CASE WHEN TOTAL_ICU_EVENTS IS NULL THEN 1 ELSE 0 END) = 0 THEN 'PASS' ELSE 'FAIL' END,
    'Aggregated column null check'
FROM ANALYTICS_DB.ANALYTICS_SCHEMA.PATIENT_ANALYTICS;

-- ----------------------------------------------------------------------------
-- G2: PATIENT_ANALYTICS - Duplicate Checks
-- ----------------------------------------------------------------------------
INSERT INTO DQ_VALIDATION_RESULTS (LAYER, TABLE_NAME, CHECK_TYPE, CHECK_NAME, TOTAL_RECORDS, FAILED_RECORDS, PASS_RATE, STATUS, DETAILS)
SELECT
    'GOLD', 'PATIENT_ANALYTICS', 'DUPLICATE_CHECK', 'Unique Patient ID',
    COUNT(*),
    COUNT(*) - COUNT(DISTINCT PATIENT_ID),
    ROUND(100.0 * COUNT(DISTINCT PATIENT_ID) / NULLIF(COUNT(*), 0), 2),
    CASE WHEN COUNT(*) = COUNT(DISTINCT PATIENT_ID) THEN 'PASS' ELSE 'FAIL' END,
    'One row per patient validation'
FROM ANALYTICS_DB.ANALYTICS_SCHEMA.PATIENT_ANALYTICS;

-- ----------------------------------------------------------------------------
-- G3: PATIENT_ANALYTICS - Schema/Aggregation Validation
-- ----------------------------------------------------------------------------
INSERT INTO DQ_VALIDATION_RESULTS (LAYER, TABLE_NAME, CHECK_TYPE, CHECK_NAME, TOTAL_RECORDS, FAILED_RECORDS, PASS_RATE, STATUS, DETAILS)
SELECT
    'GOLD', 'PATIENT_ANALYTICS', 'SCHEMA_CHECK', 'ICU Event Count Non-Negative',
    COUNT(*),
    SUM(CASE WHEN TOTAL_ICU_EVENTS < 0 THEN 1 ELSE 0 END),
    ROUND(100.0 - (SUM(CASE WHEN TOTAL_ICU_EVENTS < 0 THEN 1 ELSE 0 END) * 100.0 / NULLIF(COUNT(*), 0)), 2),
    CASE WHEN SUM(CASE WHEN TOTAL_ICU_EVENTS < 0 THEN 1 ELSE 0 END) = 0 THEN 'PASS' ELSE 'FAIL' END,
    'Non-negative count validation'
FROM ANALYTICS_DB.ANALYTICS_SCHEMA.PATIENT_ANALYTICS;

INSERT INTO DQ_VALIDATION_RESULTS (LAYER, TABLE_NAME, CHECK_TYPE, CHECK_NAME, TOTAL_RECORDS, FAILED_RECORDS, PASS_RATE, STATUS, DETAILS)
SELECT
    'GOLD', 'PATIENT_ANALYTICS', 'SCHEMA_CHECK', 'Avg Heart Rate Valid Range',
    COUNT(*),
    SUM(CASE WHEN AVG_HEART_RATE IS NOT NULL AND (AVG_HEART_RATE < 30 OR AVG_HEART_RATE > 200) THEN 1 ELSE 0 END),
    ROUND(100.0 - (SUM(CASE WHEN AVG_HEART_RATE IS NOT NULL AND (AVG_HEART_RATE < 30 OR AVG_HEART_RATE > 200) THEN 1 ELSE 0 END) * 100.0 / NULLIF(COUNT(*), 0)), 2),
    CASE WHEN SUM(CASE WHEN AVG_HEART_RATE IS NOT NULL AND (AVG_HEART_RATE < 30 OR AVG_HEART_RATE > 200) THEN 1 ELSE 0 END) = 0 THEN 'PASS' ELSE 'FAIL' END,
    'Average heart rate range validation'
FROM ANALYTICS_DB.ANALYTICS_SCHEMA.PATIENT_ANALYTICS;

INSERT INTO DQ_VALIDATION_RESULTS (LAYER, TABLE_NAME, CHECK_TYPE, CHECK_NAME, TOTAL_RECORDS, FAILED_RECORDS, PASS_RATE, STATUS, DETAILS)
SELECT
    'GOLD', 'PATIENT_ANALYTICS', 'SCHEMA_CHECK', 'Critical Events <= Total Events',
    COUNT(*),
    SUM(CASE WHEN CRITICAL_EVENTS > TOTAL_ICU_EVENTS THEN 1 ELSE 0 END),
    ROUND(100.0 - (SUM(CASE WHEN CRITICAL_EVENTS > TOTAL_ICU_EVENTS THEN 1 ELSE 0 END) * 100.0 / NULLIF(COUNT(*), 0)), 2),
    CASE WHEN SUM(CASE WHEN CRITICAL_EVENTS > TOTAL_ICU_EVENTS THEN 1 ELSE 0 END) = 0 THEN 'PASS' ELSE 'FAIL' END,
    'Logical consistency validation'
FROM ANALYTICS_DB.ANALYTICS_SCHEMA.PATIENT_ANALYTICS;

-- ----------------------------------------------------------------------------
-- G4: BILLING_ANALYTICS - Null & Schema Checks
-- ----------------------------------------------------------------------------
INSERT INTO DQ_VALIDATION_RESULTS (LAYER, TABLE_NAME, CHECK_TYPE, CHECK_NAME, TOTAL_RECORDS, FAILED_RECORDS, PASS_RATE, STATUS, DETAILS)
SELECT
    'GOLD', 'BILLING_ANALYTICS', 'NULL_CHECK', 'Patient ID Not Null',
    COUNT(*),
    SUM(CASE WHEN PATIENT_ID IS NULL THEN 1 ELSE 0 END),
    ROUND(100.0 - (SUM(CASE WHEN PATIENT_ID IS NULL THEN 1 ELSE 0 END) * 100.0 / NULLIF(COUNT(*), 0)), 2),
    CASE WHEN SUM(CASE WHEN PATIENT_ID IS NULL THEN 1 ELSE 0 END) = 0 THEN 'PASS' ELSE 'FAIL' END,
    'Primary key null check'
FROM ANALYTICS_DB.ANALYTICS_SCHEMA.BILLING_ANALYTICS;

INSERT INTO DQ_VALIDATION_RESULTS (LAYER, TABLE_NAME, CHECK_TYPE, CHECK_NAME, TOTAL_RECORDS, FAILED_RECORDS, PASS_RATE, STATUS, DETAILS)
SELECT
    'GOLD', 'BILLING_ANALYTICS', 'DUPLICATE_CHECK', 'Unique Patient ID',
    COUNT(*),
    COUNT(*) - COUNT(DISTINCT PATIENT_ID),
    ROUND(100.0 * COUNT(DISTINCT PATIENT_ID) / NULLIF(COUNT(*), 0), 2),
    CASE WHEN COUNT(*) = COUNT(DISTINCT PATIENT_ID) THEN 'PASS' ELSE 'FAIL' END,
    'One row per patient validation'
FROM ANALYTICS_DB.ANALYTICS_SCHEMA.BILLING_ANALYTICS;

INSERT INTO DQ_VALIDATION_RESULTS (LAYER, TABLE_NAME, CHECK_TYPE, CHECK_NAME, TOTAL_RECORDS, FAILED_RECORDS, PASS_RATE, STATUS, DETAILS)
SELECT
    'GOLD', 'BILLING_ANALYTICS', 'SCHEMA_CHECK', 'Total = Paid + Pending + Overdue',
    COUNT(*),
    SUM(CASE WHEN ABS(TOTAL_AMOUNT - (PAID_AMOUNT + PENDING_AMOUNT + OVERDUE_AMOUNT)) > 0.01 THEN 1 ELSE 0 END),
    ROUND(100.0 - (SUM(CASE WHEN ABS(TOTAL_AMOUNT - (PAID_AMOUNT + PENDING_AMOUNT + OVERDUE_AMOUNT)) > 0.01 THEN 1 ELSE 0 END) * 100.0 / NULLIF(COUNT(*), 0)), 2),
    CASE WHEN SUM(CASE WHEN ABS(TOTAL_AMOUNT - (PAID_AMOUNT + PENDING_AMOUNT + OVERDUE_AMOUNT)) > 0.01 THEN 1 ELSE 0 END) = 0 THEN 'PASS' ELSE 'FAIL' END,
    'Amount reconciliation validation'
FROM ANALYTICS_DB.ANALYTICS_SCHEMA.BILLING_ANALYTICS;

-- ============================================================================
-- ██████╗ ██╗      █████╗ ████████╗██╗███╗   ██╗██╗   ██╗███╗   ███╗
-- ██╔══██╗██║     ██╔══██╗╚══██╔══╝██║████╗  ██║██║   ██║████╗ ████║
-- ██████╔╝██║     ███████║   ██║   ██║██╔██╗ ██║██║   ██║██╔████╔██║
-- ██╔═══╝ ██║     ██╔══██║   ██║   ██║██║╚██╗██║██║   ██║██║╚██╔╝██║
-- ██║     ███████╗██║  ██║   ██║   ██║██║ ╚████║╚██████╔╝██║ ╚═╝ ██║
-- ╚═╝     ╚══════╝╚═╝  ╚═╝   ╚═╝   ╚═╝╚═╝  ╚═══╝ ╚═════╝ ╚═╝     ╚═╝
-- PLATINUM LAYER VALIDATIONS (AI_READY_DB)
-- ============================================================================

-- ----------------------------------------------------------------------------
-- P1: ICU_FEATURE_STORE - Null Checks
-- ----------------------------------------------------------------------------
INSERT INTO DQ_VALIDATION_RESULTS (LAYER, TABLE_NAME, CHECK_TYPE, CHECK_NAME, TOTAL_RECORDS, FAILED_RECORDS, PASS_RATE, STATUS, DETAILS)
SELECT
    'PLATINUM', 'ICU_FEATURE_STORE', 'NULL_CHECK', 'Patient ID Not Null',
    COUNT(*),
    SUM(CASE WHEN PATIENT_ID IS NULL THEN 1 ELSE 0 END),
    ROUND(100.0 - (SUM(CASE WHEN PATIENT_ID IS NULL THEN 1 ELSE 0 END) * 100.0 / NULLIF(COUNT(*), 0)), 2),
    CASE WHEN SUM(CASE WHEN PATIENT_ID IS NULL THEN 1 ELSE 0 END) = 0 THEN 'PASS' ELSE 'FAIL' END,
    'Primary key null check'
FROM AI_READY_DB.AI_SCHEMA.ICU_FEATURE_STORE;

INSERT INTO DQ_VALIDATION_RESULTS (LAYER, TABLE_NAME, CHECK_TYPE, CHECK_NAME, TOTAL_RECORDS, FAILED_RECORDS, PASS_RATE, STATUS, DETAILS)
SELECT
    'PLATINUM', 'ICU_FEATURE_STORE', 'NULL_CHECK', 'Risk Score Not Null',
    COUNT(*),
    SUM(CASE WHEN RISK_SCORE IS NULL THEN 1 ELSE 0 END),
    ROUND(100.0 - (SUM(CASE WHEN RISK_SCORE IS NULL THEN 1 ELSE 0 END) * 100.0 / NULLIF(COUNT(*), 0)), 2),
    CASE WHEN SUM(CASE WHEN RISK_SCORE IS NULL THEN 1 ELSE 0 END) = 0 THEN 'PASS' ELSE 'FAIL' END,
    'ML feature null check'
FROM AI_READY_DB.AI_SCHEMA.ICU_FEATURE_STORE;

-- ----------------------------------------------------------------------------
-- P2: ICU_FEATURE_STORE - Duplicate Checks
-- ----------------------------------------------------------------------------
INSERT INTO DQ_VALIDATION_RESULTS (LAYER, TABLE_NAME, CHECK_TYPE, CHECK_NAME, TOTAL_RECORDS, FAILED_RECORDS, PASS_RATE, STATUS, DETAILS)
SELECT
    'PLATINUM', 'ICU_FEATURE_STORE', 'DUPLICATE_CHECK', 'Unique Patient ID',
    COUNT(*),
    COUNT(*) - COUNT(DISTINCT PATIENT_ID),
    ROUND(100.0 * COUNT(DISTINCT PATIENT_ID) / NULLIF(COUNT(*), 0), 2),
    CASE WHEN COUNT(*) = COUNT(DISTINCT PATIENT_ID) THEN 'PASS' ELSE 'FAIL' END,
    'One feature row per patient'
FROM AI_READY_DB.AI_SCHEMA.ICU_FEATURE_STORE;

-- ----------------------------------------------------------------------------
-- P3: ICU_FEATURE_STORE - Schema/Feature Validation
-- ----------------------------------------------------------------------------
INSERT INTO DQ_VALIDATION_RESULTS (LAYER, TABLE_NAME, CHECK_TYPE, CHECK_NAME, TOTAL_RECORDS, FAILED_RECORDS, PASS_RATE, STATUS, DETAILS)
SELECT
    'PLATINUM', 'ICU_FEATURE_STORE', 'SCHEMA_CHECK', 'Risk Score Valid Range (0-5)',
    COUNT(*),
    SUM(CASE WHEN RISK_SCORE < 0 OR RISK_SCORE > 5 THEN 1 ELSE 0 END),
    ROUND(100.0 - (SUM(CASE WHEN RISK_SCORE < 0 OR RISK_SCORE > 5 THEN 1 ELSE 0 END) * 100.0 / NULLIF(COUNT(*), 0)), 2),
    CASE WHEN SUM(CASE WHEN RISK_SCORE < 0 OR RISK_SCORE > 5 THEN 1 ELSE 0 END) = 0 THEN 'PASS' ELSE 'FAIL' END,
    'Risk score range validation'
FROM AI_READY_DB.AI_SCHEMA.ICU_FEATURE_STORE;

INSERT INTO DQ_VALIDATION_RESULTS (LAYER, TABLE_NAME, CHECK_TYPE, CHECK_NAME, TOTAL_RECORDS, FAILED_RECORDS, PASS_RATE, STATUS, DETAILS)
SELECT
    'PLATINUM', 'ICU_FEATURE_STORE', 'SCHEMA_CHECK', 'Valid Risk Category',
    COUNT(*),
    SUM(CASE WHEN RISK_CATEGORY NOT IN ('LOW', 'MEDIUM', 'HIGH', 'CRITICAL') THEN 1 ELSE 0 END),
    ROUND(100.0 - (SUM(CASE WHEN RISK_CATEGORY NOT IN ('LOW', 'MEDIUM', 'HIGH', 'CRITICAL') THEN 1 ELSE 0 END) * 100.0 / NULLIF(COUNT(*), 0)), 2),
    CASE WHEN SUM(CASE WHEN RISK_CATEGORY NOT IN ('LOW', 'MEDIUM', 'HIGH', 'CRITICAL') THEN 1 ELSE 0 END) = 0 THEN 'PASS' ELSE 'FAIL' END,
    'Risk category enum validation'
FROM AI_READY_DB.AI_SCHEMA.ICU_FEATURE_STORE;

INSERT INTO DQ_VALIDATION_RESULTS (LAYER, TABLE_NAME, CHECK_TYPE, CHECK_NAME, TOTAL_RECORDS, FAILED_RECORDS, PASS_RATE, STATUS, DETAILS)
SELECT
    'PLATINUM', 'ICU_FEATURE_STORE', 'SCHEMA_CHECK', 'Binary Risk Flags Valid (0/1)',
    COUNT(*),
    SUM(CASE WHEN RISK_AGE NOT IN (0, 1) OR RISK_LOW_OXYGEN NOT IN (0, 1) OR RISK_HIGH_HR NOT IN (0, 1) THEN 1 ELSE 0 END),
    ROUND(100.0 - (SUM(CASE WHEN RISK_AGE NOT IN (0, 1) OR RISK_LOW_OXYGEN NOT IN (0, 1) OR RISK_HIGH_HR NOT IN (0, 1) THEN 1 ELSE 0 END) * 100.0 / NULLIF(COUNT(*), 0)), 2),
    CASE WHEN SUM(CASE WHEN RISK_AGE NOT IN (0, 1) OR RISK_LOW_OXYGEN NOT IN (0, 1) OR RISK_HIGH_HR NOT IN (0, 1) THEN 1 ELSE 0 END) = 0 THEN 'PASS' ELSE 'FAIL' END,
    'Binary flag validation'
FROM AI_READY_DB.AI_SCHEMA.ICU_FEATURE_STORE;

INSERT INTO DQ_VALIDATION_RESULTS (LAYER, TABLE_NAME, CHECK_TYPE, CHECK_NAME, TOTAL_RECORDS, FAILED_RECORDS, PASS_RATE, STATUS, DETAILS)
SELECT
    'PLATINUM', 'ICU_FEATURE_STORE', 'SCHEMA_CHECK', 'Risk Score = Sum of Flags',
    COUNT(*),
    SUM(CASE WHEN RISK_SCORE != (RISK_AGE + RISK_LOW_OXYGEN + RISK_HIGH_HR + RISK_CRITICAL_EVENTS + RISK_HIGH_BP) THEN 1 ELSE 0 END),
    ROUND(100.0 - (SUM(CASE WHEN RISK_SCORE != (RISK_AGE + RISK_LOW_OXYGEN + RISK_HIGH_HR + RISK_CRITICAL_EVENTS + RISK_HIGH_BP) THEN 1 ELSE 0 END) * 100.0 / NULLIF(COUNT(*), 0)), 2),
    CASE WHEN SUM(CASE WHEN RISK_SCORE != (RISK_AGE + RISK_LOW_OXYGEN + RISK_HIGH_HR + RISK_CRITICAL_EVENTS + RISK_HIGH_BP) THEN 1 ELSE 0 END) = 0 THEN 'PASS' ELSE 'FAIL' END,
    'Calculated field validation'
FROM AI_READY_DB.AI_SCHEMA.ICU_FEATURE_STORE;

-- ----------------------------------------------------------------------------
-- P4: PATIENT_EMBEDDINGS - Null & Schema Checks
-- ----------------------------------------------------------------------------
INSERT INTO DQ_VALIDATION_RESULTS (LAYER, TABLE_NAME, CHECK_TYPE, CHECK_NAME, TOTAL_RECORDS, FAILED_RECORDS, PASS_RATE, STATUS, DETAILS)
SELECT
    'PLATINUM', 'PATIENT_EMBEDDINGS', 'NULL_CHECK', 'Patient ID Not Null',
    COUNT(*),
    SUM(CASE WHEN PATIENT_ID IS NULL THEN 1 ELSE 0 END),
    ROUND(100.0 - (SUM(CASE WHEN PATIENT_ID IS NULL THEN 1 ELSE 0 END) * 100.0 / NULLIF(COUNT(*), 0)), 2),
    CASE WHEN SUM(CASE WHEN PATIENT_ID IS NULL THEN 1 ELSE 0 END) = 0 THEN 'PASS' ELSE 'FAIL' END,
    'Primary key null check'
FROM AI_READY_DB.FEATURE_STORE.PATIENT_EMBEDDINGS;

INSERT INTO DQ_VALIDATION_RESULTS (LAYER, TABLE_NAME, CHECK_TYPE, CHECK_NAME, TOTAL_RECORDS, FAILED_RECORDS, PASS_RATE, STATUS, DETAILS)
SELECT
    'PLATINUM', 'PATIENT_EMBEDDINGS', 'NULL_CHECK', 'Embedding Vector Not Null',
    COUNT(*),
    SUM(CASE WHEN EMBEDDING_VECTOR IS NULL THEN 1 ELSE 0 END),
    ROUND(100.0 - (SUM(CASE WHEN EMBEDDING_VECTOR IS NULL THEN 1 ELSE 0 END) * 100.0 / NULLIF(COUNT(*), 0)), 2),
    CASE WHEN SUM(CASE WHEN EMBEDDING_VECTOR IS NULL THEN 1 ELSE 0 END) = 0 THEN 'PASS' ELSE 'FAIL' END,
    'Embedding vector null check'
FROM AI_READY_DB.FEATURE_STORE.PATIENT_EMBEDDINGS;

INSERT INTO DQ_VALIDATION_RESULTS (LAYER, TABLE_NAME, CHECK_TYPE, CHECK_NAME, TOTAL_RECORDS, FAILED_RECORDS, PASS_RATE, STATUS, DETAILS)
SELECT
    'PLATINUM', 'PATIENT_EMBEDDINGS', 'SCHEMA_CHECK', 'Embedding Vector Dimension',
    COUNT(*),
    SUM(CASE WHEN ARRAY_SIZE(EMBEDDING_VECTOR) != 8 THEN 1 ELSE 0 END),
    ROUND(100.0 - (SUM(CASE WHEN ARRAY_SIZE(EMBEDDING_VECTOR) != 8 THEN 1 ELSE 0 END) * 100.0 / NULLIF(COUNT(*), 0)), 2),
    CASE WHEN SUM(CASE WHEN ARRAY_SIZE(EMBEDDING_VECTOR) != 8 THEN 1 ELSE 0 END) = 0 THEN 'PASS' ELSE 'FAIL' END,
    'Expected 8-dimensional vector'
FROM AI_READY_DB.FEATURE_STORE.PATIENT_EMBEDDINGS;

-- ============================================================================
-- CROSS-LAYER REFERENTIAL INTEGRITY CHECKS
-- ============================================================================

-- Bronze to Silver Patient Count
INSERT INTO DQ_VALIDATION_RESULTS (LAYER, TABLE_NAME, CHECK_TYPE, CHECK_NAME, TOTAL_RECORDS, FAILED_RECORDS, PASS_RATE, STATUS, DETAILS)
SELECT
    'CROSS-LAYER', 'BRONZE_TO_SILVER', 'REFERENTIAL_INTEGRITY', 'Patient Count Match',
    (SELECT COUNT(*) FROM RAW_DB.RAW_SCHEMA.PATIENT_RAW),
    ABS((SELECT COUNT(*) FROM RAW_DB.RAW_SCHEMA.PATIENT_RAW) - (SELECT COUNT(*) FROM TRANSFORM_DB.TRANSFORM_SCHEMA.CLEAN_PATIENT)),
    CASE WHEN (SELECT COUNT(*) FROM RAW_DB.RAW_SCHEMA.PATIENT_RAW) = (SELECT COUNT(*) FROM TRANSFORM_DB.TRANSFORM_SCHEMA.CLEAN_PATIENT) THEN 100.00 ELSE 0.00 END,
    CASE WHEN (SELECT COUNT(*) FROM RAW_DB.RAW_SCHEMA.PATIENT_RAW) = (SELECT COUNT(*) FROM TRANSFORM_DB.TRANSFORM_SCHEMA.CLEAN_PATIENT) THEN 'PASS' ELSE 'FAIL' END,
    'Bronze to Silver patient count validation';

-- Silver to Gold Patient Count
INSERT INTO DQ_VALIDATION_RESULTS (LAYER, TABLE_NAME, CHECK_TYPE, CHECK_NAME, TOTAL_RECORDS, FAILED_RECORDS, PASS_RATE, STATUS, DETAILS)
SELECT
    'CROSS-LAYER', 'SILVER_TO_GOLD', 'REFERENTIAL_INTEGRITY', 'Patient Count Match',
    (SELECT COUNT(*) FROM TRANSFORM_DB.TRANSFORM_SCHEMA.CLEAN_PATIENT),
    ABS((SELECT COUNT(*) FROM TRANSFORM_DB.TRANSFORM_SCHEMA.CLEAN_PATIENT) - (SELECT COUNT(*) FROM ANALYTICS_DB.ANALYTICS_SCHEMA.PATIENT_ANALYTICS)),
    CASE WHEN (SELECT COUNT(*) FROM TRANSFORM_DB.TRANSFORM_SCHEMA.CLEAN_PATIENT) = (SELECT COUNT(*) FROM ANALYTICS_DB.ANALYTICS_SCHEMA.PATIENT_ANALYTICS) THEN 100.00 ELSE 0.00 END,
    CASE WHEN (SELECT COUNT(*) FROM TRANSFORM_DB.TRANSFORM_SCHEMA.CLEAN_PATIENT) = (SELECT COUNT(*) FROM ANALYTICS_DB.ANALYTICS_SCHEMA.PATIENT_ANALYTICS) THEN 'PASS' ELSE 'FAIL' END,
    'Silver to Gold patient count validation';

-- Gold to Platinum Patient Count
INSERT INTO DQ_VALIDATION_RESULTS (LAYER, TABLE_NAME, CHECK_TYPE, CHECK_NAME, TOTAL_RECORDS, FAILED_RECORDS, PASS_RATE, STATUS, DETAILS)
SELECT
    'CROSS-LAYER', 'GOLD_TO_PLATINUM', 'REFERENTIAL_INTEGRITY', 'Patient Count Match',
    (SELECT COUNT(*) FROM ANALYTICS_DB.ANALYTICS_SCHEMA.PATIENT_ANALYTICS),
    ABS((SELECT COUNT(*) FROM ANALYTICS_DB.ANALYTICS_SCHEMA.PATIENT_ANALYTICS) - (SELECT COUNT(*) FROM AI_READY_DB.AI_SCHEMA.ICU_FEATURE_STORE)),
    CASE WHEN (SELECT COUNT(*) FROM ANALYTICS_DB.ANALYTICS_SCHEMA.PATIENT_ANALYTICS) = (SELECT COUNT(*) FROM AI_READY_DB.AI_SCHEMA.ICU_FEATURE_STORE) THEN 100.00 ELSE 0.00 END,
    CASE WHEN (SELECT COUNT(*) FROM ANALYTICS_DB.ANALYTICS_SCHEMA.PATIENT_ANALYTICS) = (SELECT COUNT(*) FROM AI_READY_DB.AI_SCHEMA.ICU_FEATURE_STORE) THEN 'PASS' ELSE 'FAIL' END,
    'Gold to Platinum patient count validation';

-- ============================================================================
-- DQ SUMMARY VIEWS
-- ============================================================================

-- Summary by Layer
CREATE OR REPLACE VIEW V_DQ_SUMMARY_BY_LAYER AS
SELECT
    LAYER,
    COUNT(*) AS TOTAL_CHECKS,
    SUM(CASE WHEN STATUS = 'PASS' THEN 1 ELSE 0 END) AS PASSED,
    SUM(CASE WHEN STATUS = 'FAIL' THEN 1 ELSE 0 END) AS FAILED,
    ROUND(100.0 * SUM(CASE WHEN STATUS = 'PASS' THEN 1 ELSE 0 END) / COUNT(*), 2) AS PASS_RATE
FROM DQ_VALIDATION_RESULTS
GROUP BY LAYER
ORDER BY 
    CASE LAYER 
        WHEN 'BRONZE' THEN 1 
        WHEN 'SILVER' THEN 2 
        WHEN 'GOLD' THEN 3 
        WHEN 'PLATINUM' THEN 4 
        ELSE 5 
    END;

-- Summary by Check Type
CREATE OR REPLACE VIEW V_DQ_SUMMARY_BY_CHECK_TYPE AS
SELECT
    CHECK_TYPE,
    COUNT(*) AS TOTAL_CHECKS,
    SUM(CASE WHEN STATUS = 'PASS' THEN 1 ELSE 0 END) AS PASSED,
    SUM(CASE WHEN STATUS = 'FAIL' THEN 1 ELSE 0 END) AS FAILED,
    ROUND(100.0 * SUM(CASE WHEN STATUS = 'PASS' THEN 1 ELSE 0 END) / COUNT(*), 2) AS PASS_RATE
FROM DQ_VALIDATION_RESULTS
GROUP BY CHECK_TYPE;

-- Failed Checks Detail
CREATE OR REPLACE VIEW V_DQ_FAILED_CHECKS AS
SELECT *
FROM DQ_VALIDATION_RESULTS
WHERE STATUS = 'FAIL'
ORDER BY VALIDATION_TIMESTAMP DESC;

-- ============================================================================
-- FINAL DQ REPORT
-- ============================================================================

SELECT '========================================' AS REPORT;
SELECT 'DATA QUALITY VALIDATION REPORT' AS REPORT;
SELECT '========================================' AS REPORT;

-- Overall Summary
SELECT 
    'OVERALL SUMMARY' AS SECTION,
    COUNT(*) AS TOTAL_CHECKS,
    SUM(CASE WHEN STATUS = 'PASS' THEN 1 ELSE 0 END) AS PASSED,
    SUM(CASE WHEN STATUS = 'FAIL' THEN 1 ELSE 0 END) AS FAILED,
    ROUND(100.0 * SUM(CASE WHEN STATUS = 'PASS' THEN 1 ELSE 0 END) / COUNT(*), 2) AS OVERALL_PASS_RATE
FROM DQ_VALIDATION_RESULTS;

-- By Layer
SELECT * FROM V_DQ_SUMMARY_BY_LAYER;

-- By Check Type
SELECT * FROM V_DQ_SUMMARY_BY_CHECK_TYPE;

-- Failed Checks (if any)
SELECT * FROM V_DQ_FAILED_CHECKS;

-- ============================================================================
-- END OF DATA QUALITY VALIDATION FRAMEWORK
-- ============================================================================
