-- ============================================================================
-- HEALTHCARE ENTERPRISE DATA HUB - MASTER DEPLOYMENT SCRIPT
-- ============================================================================
-- Author: DEVIKAPG
-- Account: tyb42779
-- Industry: Healthcare & Life Sciences (HCLS)
-- ============================================================================
-- This single file contains ALL 15 phases for complete deployment
-- Execute sections in order using ACCOUNTADMIN role
-- ============================================================================

-- ============================================================================
-- PHASE 1: ACCOUNT ADMINISTRATION
-- Objectives: Network policies, security settings
-- ============================================================================

USE ROLE ACCOUNTADMIN;

-- 1.1 Security Database (Required for policies)
CREATE DATABASE IF NOT EXISTS SECURITY_DB COMMENT = 'Security policies and governance';
CREATE SCHEMA IF NOT EXISTS SECURITY_DB.SECURITY_SCHEMA;
CREATE SCHEMA IF NOT EXISTS SECURITY_DB.POLICIES;

-- 1.2 Network Policy (Allow all for trial - restrict in production)
CREATE OR REPLACE NETWORK POLICY SECURITY_DB.POLICIES.healthcare_network_policy
    ALLOWED_IP_LIST = ('0.0.0.0/0')
    COMMENT = 'Healthcare network access policy';

-- 1.3 Password Policy
CREATE OR REPLACE PASSWORD POLICY SECURITY_DB.POLICIES.healthcare_password_policy
    PASSWORD_MIN_LENGTH = 12
    PASSWORD_MAX_LENGTH = 64
    PASSWORD_MIN_UPPER_CASE_CHARS = 1
    PASSWORD_MIN_LOWER_CASE_CHARS = 1
    PASSWORD_MIN_NUMERIC_CHARS = 1
    PASSWORD_MIN_SPECIAL_CHARS = 1
    COMMENT = 'Healthcare password requirements';

-- 1.4 Session Policy
CREATE OR REPLACE SESSION POLICY SECURITY_DB.POLICIES.healthcare_session_policy
    SESSION_IDLE_TIMEOUT_MINS = 30
    SESSION_UI_IDLE_TIMEOUT_MINS = 30
    COMMENT = 'Healthcare session timeout policy';

-- Phase 1 Verification
SELECT 'PHASE 1: ACCOUNT ADMINISTRATION' AS PHASE, 'COMPLETE' AS STATUS;

-- ============================================================================
-- PHASE 2: RBAC SETUP
-- Objectives: 5+ roles with hierarchy
-- ============================================================================

-- 2.1 Create Roles (6 roles)
CREATE ROLE IF NOT EXISTS HC_ACCOUNT_ADMIN COMMENT = 'Healthcare Account Administrator';
CREATE ROLE IF NOT EXISTS HC_SECURITY_ADMIN COMMENT = 'Healthcare Security Administrator';
CREATE ROLE IF NOT EXISTS HC_DATA_ENGINEER COMMENT = 'Healthcare Data Engineer';
CREATE ROLE IF NOT EXISTS HC_ANALYST COMMENT = 'Healthcare Data Analyst';
CREATE ROLE IF NOT EXISTS HC_DATA_SCIENTIST COMMENT = 'Healthcare Data Scientist';
CREATE ROLE IF NOT EXISTS HC_VIEWER COMMENT = 'Healthcare Read-Only Viewer';

-- 2.2 Role Hierarchy
GRANT ROLE HC_ACCOUNT_ADMIN TO ROLE ACCOUNTADMIN;
GRANT ROLE HC_SECURITY_ADMIN TO ROLE HC_ACCOUNT_ADMIN;
GRANT ROLE HC_DATA_ENGINEER TO ROLE HC_ACCOUNT_ADMIN;
GRANT ROLE HC_DATA_SCIENTIST TO ROLE HC_ACCOUNT_ADMIN;
GRANT ROLE HC_ANALYST TO ROLE HC_DATA_ENGINEER;
GRANT ROLE HC_VIEWER TO ROLE HC_ANALYST;

-- 2.3 Grant to current user
GRANT ROLE HC_ACCOUNT_ADMIN TO USER DEVIKAPG;

-- Phase 2 Verification
SELECT 'PHASE 2: RBAC SETUP' AS PHASE, 'COMPLETE' AS STATUS;
SHOW ROLES LIKE 'HC_%';

-- ============================================================================
-- PHASE 3: WAREHOUSE MANAGEMENT
-- Objectives: 4 workload-specific warehouses
-- ============================================================================

-- 3.1 ETL Warehouse (Data Ingestion)
CREATE WAREHOUSE IF NOT EXISTS HC_ETL_WH
    WAREHOUSE_SIZE = 'XSMALL'
    AUTO_SUSPEND = 60
    AUTO_RESUME = TRUE
    INITIALLY_SUSPENDED = TRUE
    COMMENT = 'ETL and data ingestion workloads';

-- 3.2 Transform Warehouse (Data Processing)
CREATE WAREHOUSE IF NOT EXISTS HC_TRANSFORM_WH
    WAREHOUSE_SIZE = 'XSMALL'
    AUTO_SUSPEND = 120
    AUTO_RESUME = TRUE
    INITIALLY_SUSPENDED = TRUE
    COMMENT = 'Data transformation workloads';

-- 3.3 Analytics Warehouse (Reporting/BI)
CREATE WAREHOUSE IF NOT EXISTS HC_ANALYTICS_WH
    WAREHOUSE_SIZE = 'XSMALL'
    AUTO_SUSPEND = 60
    AUTO_RESUME = TRUE
    INITIALLY_SUSPENDED = TRUE
    COMMENT = 'Analytics and BI workloads';

-- 3.4 AI Warehouse (ML/AI Workloads)
CREATE WAREHOUSE IF NOT EXISTS HC_AI_WH
    WAREHOUSE_SIZE = 'XSMALL'
    AUTO_SUSPEND = 300
    AUTO_RESUME = TRUE
    INITIALLY_SUSPENDED = TRUE
    COMMENT = 'ML and AI workloads';

-- 3.5 Warehouse Grants to Roles
GRANT USAGE ON WAREHOUSE HC_ETL_WH TO ROLE HC_DATA_ENGINEER;
GRANT USAGE ON WAREHOUSE HC_TRANSFORM_WH TO ROLE HC_DATA_ENGINEER;
GRANT USAGE ON WAREHOUSE HC_ANALYTICS_WH TO ROLE HC_ANALYST;
GRANT USAGE ON WAREHOUSE HC_AI_WH TO ROLE HC_DATA_SCIENTIST;
GRANT ALL ON WAREHOUSE HC_AI_WH TO ROLE HC_ACCOUNT_ADMIN;

-- Phase 3 Verification
SELECT 'PHASE 3: WAREHOUSE MANAGEMENT' AS PHASE, 'COMPLETE' AS STATUS;
SHOW WAREHOUSES LIKE 'HC_%';

-- ============================================================================
-- PHASE 4: DATABASE STRUCTURE
-- Objectives: RAW/STAGING, TRANSFORM, ANALYTICS, AI_READY databases
-- ============================================================================

-- 4.1 Medallion Databases
CREATE DATABASE IF NOT EXISTS RAW_DB COMMENT = 'Bronze Layer - Raw ingested data';
CREATE DATABASE IF NOT EXISTS TRANSFORM_DB COMMENT = 'Silver Layer - Cleaned data';
CREATE DATABASE IF NOT EXISTS ANALYTICS_DB COMMENT = 'Gold Layer - Aggregated analytics';
CREATE DATABASE IF NOT EXISTS AI_READY_DB COMMENT = 'Platinum Layer - ML/AI features';

-- 4.2 Support Databases
CREATE DATABASE IF NOT EXISTS MONITORING_DB COMMENT = 'Performance monitoring';
CREATE DATABASE IF NOT EXISTS AUDIT_DB COMMENT = 'Audit trail and compliance';
CREATE DATABASE IF NOT EXISTS DEVOPS_DB COMMENT = 'CI/CD deployment tracking';

-- 4.3 Schemas
CREATE SCHEMA IF NOT EXISTS RAW_DB.RAW_SCHEMA;
CREATE SCHEMA IF NOT EXISTS RAW_DB.STAGING_SCHEMA;
CREATE SCHEMA IF NOT EXISTS TRANSFORM_DB.TRANSFORM_SCHEMA;
CREATE SCHEMA IF NOT EXISTS ANALYTICS_DB.ANALYTICS_SCHEMA;
CREATE SCHEMA IF NOT EXISTS AI_READY_DB.AI_SCHEMA;
CREATE SCHEMA IF NOT EXISTS AI_READY_DB.FEATURE_STORE;
CREATE SCHEMA IF NOT EXISTS AI_READY_DB.SEMANTIC_MODELS;
CREATE SCHEMA IF NOT EXISTS MONITORING_DB.MONITORING_SCHEMA;
CREATE SCHEMA IF NOT EXISTS AUDIT_DB.AUDIT_SCHEMA;
CREATE SCHEMA IF NOT EXISTS DEVOPS_DB.CI_CD;

-- 4.4 Database Grants
GRANT USAGE ON DATABASE RAW_DB TO ROLE HC_DATA_ENGINEER;
GRANT USAGE ON DATABASE TRANSFORM_DB TO ROLE HC_DATA_ENGINEER;
GRANT USAGE ON DATABASE ANALYTICS_DB TO ROLE HC_ANALYST;
GRANT USAGE ON DATABASE AI_READY_DB TO ROLE HC_DATA_SCIENTIST;
GRANT USAGE ON DATABASE SECURITY_DB TO ROLE HC_SECURITY_ADMIN;
GRANT ALL PRIVILEGES ON SCHEMA SECURITY_DB.SECURITY_SCHEMA TO ROLE HC_SECURITY_ADMIN;

-- Phase 4 Verification
SELECT 'PHASE 4: DATABASE STRUCTURE' AS PHASE, 'COMPLETE' AS STATUS;
SHOW DATABASES LIKE '%_DB';

-- ============================================================================
-- PHASE 5: RESOURCE MONITORS
-- Objectives: Account + per-warehouse monitors
-- ============================================================================

-- 5.1 Account-Level Monitor
CREATE OR REPLACE RESOURCE MONITOR HC_ACCOUNT_MONITOR
    WITH CREDIT_QUOTA = 100
    TRIGGERS
        ON 50 PERCENT DO NOTIFY
        ON 75 PERCENT DO NOTIFY
        ON 90 PERCENT DO NOTIFY
        ON 100 PERCENT DO SUSPEND;

-- 5.2 ETL Warehouse Monitor
CREATE OR REPLACE RESOURCE MONITOR HC_ETL_WH_MONITOR
    WITH CREDIT_QUOTA = 25
    TRIGGERS
        ON 75 PERCENT DO NOTIFY
        ON 100 PERCENT DO SUSPEND;
ALTER WAREHOUSE HC_ETL_WH SET RESOURCE_MONITOR = HC_ETL_WH_MONITOR;

-- 5.3 Transform Warehouse Monitor
CREATE OR REPLACE RESOURCE MONITOR HC_TRANSFORM_WH_MONITOR
    WITH CREDIT_QUOTA = 35
    TRIGGERS
        ON 75 PERCENT DO NOTIFY
        ON 100 PERCENT DO SUSPEND;
ALTER WAREHOUSE HC_TRANSFORM_WH SET RESOURCE_MONITOR = HC_TRANSFORM_WH_MONITOR;

-- 5.4 Analytics Warehouse Monitor
CREATE OR REPLACE RESOURCE MONITOR HC_ANALYTICS_WH_MONITOR
    WITH CREDIT_QUOTA = 20
    TRIGGERS
        ON 75 PERCENT DO NOTIFY
        ON 100 PERCENT DO SUSPEND;
ALTER WAREHOUSE HC_ANALYTICS_WH SET RESOURCE_MONITOR = HC_ANALYTICS_WH_MONITOR;

-- 5.5 AI Warehouse Monitor
CREATE OR REPLACE RESOURCE MONITOR HC_AI_WH_MONITOR
    WITH CREDIT_QUOTA = 50
    TRIGGERS
        ON 75 PERCENT DO NOTIFY
        ON 100 PERCENT DO SUSPEND;
ALTER WAREHOUSE HC_AI_WH SET RESOURCE_MONITOR = HC_AI_WH_MONITOR;

-- Phase 5 Verification
SELECT 'PHASE 5: RESOURCE MONITORS' AS PHASE, 'COMPLETE' AS STATUS;
SHOW RESOURCE MONITORS LIKE 'HC_%';

-- ============================================================================
-- PHASE 6: MONITORING (10+ Consumption Insight Views)
-- ============================================================================

USE DATABASE MONITORING_DB;
USE SCHEMA MONITORING_SCHEMA;

-- 6.1 Query Performance View
CREATE OR REPLACE VIEW V_QUERY_PERFORMANCE AS
SELECT
    QUERY_ID, USER_NAME, ROLE_NAME, WAREHOUSE_NAME,
    EXECUTION_STATUS, ERROR_CODE, ERROR_MESSAGE,
    START_TIME, END_TIME, TOTAL_ELAPSED_TIME,
    BYTES_SCANNED, ROWS_PRODUCED, COMPILATION_TIME,
    CREDITS_USED_CLOUD_SERVICES
FROM SNOWFLAKE.ACCOUNT_USAGE.QUERY_HISTORY
WHERE START_TIME >= DATEADD(DAY, -30, CURRENT_DATE);

-- 6.2 Warehouse Credit Usage View
CREATE OR REPLACE VIEW V_WAREHOUSE_CREDIT_USAGE AS
SELECT
    WAREHOUSE_NAME,
    DATE_TRUNC('DAY', START_TIME) AS USAGE_DATE,
    SUM(CREDITS_USED) AS TOTAL_CREDITS,
    SUM(CREDITS_USED_COMPUTE) AS COMPUTE_CREDITS,
    SUM(CREDITS_USED_CLOUD_SERVICES) AS CLOUD_CREDITS
FROM SNOWFLAKE.ACCOUNT_USAGE.WAREHOUSE_METERING_HISTORY
WHERE START_TIME >= DATEADD(DAY, -30, CURRENT_DATE)
GROUP BY WAREHOUSE_NAME, DATE_TRUNC('DAY', START_TIME);

-- 6.3 Daily Credit Summary View
CREATE OR REPLACE VIEW V_DAILY_CREDIT_SUMMARY AS
SELECT
    DATE_TRUNC('DAY', START_TIME) AS USAGE_DATE,
    SUM(CREDITS_USED) AS TOTAL_CREDITS,
    COUNT(DISTINCT WAREHOUSE_NAME) AS WAREHOUSES_USED
FROM SNOWFLAKE.ACCOUNT_USAGE.WAREHOUSE_METERING_HISTORY
WHERE START_TIME >= DATEADD(DAY, -30, CURRENT_DATE)
GROUP BY DATE_TRUNC('DAY', START_TIME);

-- 6.4 Login History View
CREATE OR REPLACE VIEW V_LOGIN_HISTORY AS
SELECT
    EVENT_TIMESTAMP, USER_NAME, CLIENT_IP,
    REPORTED_CLIENT_TYPE, FIRST_AUTHENTICATION_FACTOR,
    IS_SUCCESS, ERROR_CODE, ERROR_MESSAGE
FROM SNOWFLAKE.ACCOUNT_USAGE.LOGIN_HISTORY
WHERE EVENT_TIMESTAMP >= DATEADD(DAY, -30, CURRENT_DATE);

-- 6.5 Failed Logins View
CREATE OR REPLACE VIEW V_FAILED_LOGINS AS
SELECT *
FROM SNOWFLAKE.ACCOUNT_USAGE.LOGIN_HISTORY
WHERE IS_SUCCESS = 'NO'
    AND EVENT_TIMESTAMP >= DATEADD(DAY, -7, CURRENT_DATE);

-- 6.6 Long Running Queries View
CREATE OR REPLACE VIEW V_LONG_RUNNING_QUERIES AS
SELECT *
FROM SNOWFLAKE.ACCOUNT_USAGE.QUERY_HISTORY
WHERE TOTAL_ELAPSED_TIME > 300000  -- 5 minutes
    AND START_TIME >= DATEADD(DAY, -7, CURRENT_DATE);

-- 6.7 Blocked/Failed Queries View
CREATE OR REPLACE VIEW V_FAILED_QUERIES AS
SELECT *
FROM SNOWFLAKE.ACCOUNT_USAGE.QUERY_HISTORY
WHERE ERROR_CODE IS NOT NULL
    AND START_TIME >= DATEADD(DAY, -7, CURRENT_DATE);

-- 6.8 Storage Usage View
CREATE OR REPLACE VIEW V_STORAGE_USAGE AS
SELECT
    USAGE_DATE,
    DATABASE_NAME,
    AVERAGE_DATABASE_BYTES / (1024*1024*1024) AS SIZE_GB,
    AVERAGE_FAILSAFE_BYTES / (1024*1024*1024) AS FAILSAFE_GB
FROM SNOWFLAKE.ACCOUNT_USAGE.DATABASE_STORAGE_USAGE_HISTORY
WHERE USAGE_DATE >= DATEADD(DAY, -30, CURRENT_DATE);

-- 6.9 Warehouse Load History View
CREATE OR REPLACE VIEW V_WAREHOUSE_LOAD AS
SELECT
    WAREHOUSE_NAME, START_TIME, END_TIME,
    AVG_RUNNING, AVG_QUEUED_LOAD, AVG_BLOCKED
FROM SNOWFLAKE.ACCOUNT_USAGE.WAREHOUSE_LOAD_HISTORY
WHERE START_TIME >= DATEADD(DAY, -7, CURRENT_DATE);

-- 6.10 User Query Stats View
CREATE OR REPLACE VIEW V_USER_QUERY_STATS AS
SELECT
    USER_NAME,
    COUNT(*) AS TOTAL_QUERIES,
    SUM(CASE WHEN EXECUTION_STATUS = 'SUCCESS' THEN 1 ELSE 0 END) AS SUCCESSFUL,
    SUM(CASE WHEN EXECUTION_STATUS != 'SUCCESS' THEN 1 ELSE 0 END) AS FAILED,
    AVG(TOTAL_ELAPSED_TIME) AS AVG_DURATION_MS,
    SUM(CREDITS_USED_CLOUD_SERVICES) AS TOTAL_CREDITS
FROM SNOWFLAKE.ACCOUNT_USAGE.QUERY_HISTORY
WHERE START_TIME >= DATEADD(DAY, -30, CURRENT_DATE)
GROUP BY USER_NAME;

-- 6.11 Data Transfer View
CREATE OR REPLACE VIEW V_DATA_TRANSFER AS
SELECT
    DATE_TRUNC('DAY', START_TIME) AS TRANSFER_DATE,
    SOURCE_CLOUD, SOURCE_REGION,
    TARGET_CLOUD, TARGET_REGION,
    SUM(BYTES_TRANSFERRED) / (1024*1024*1024) AS GB_TRANSFERRED
FROM SNOWFLAKE.ACCOUNT_USAGE.DATA_TRANSFER_HISTORY
WHERE START_TIME >= DATEADD(DAY, -30, CURRENT_DATE)
GROUP BY DATE_TRUNC('DAY', START_TIME), SOURCE_CLOUD, SOURCE_REGION, TARGET_CLOUD, TARGET_REGION;

-- 6.12 Materialized View Refresh View
CREATE OR REPLACE VIEW V_MV_REFRESH_HISTORY AS
SELECT
    DATABASE_NAME, SCHEMA_NAME, TABLE_NAME,
    START_TIME, END_TIME, CREDITS_USED,
    NUM_ROWS_INSERTED, NUM_ROWS_DELETED
FROM SNOWFLAKE.ACCOUNT_USAGE.MATERIALIZED_VIEW_REFRESH_HISTORY
WHERE START_TIME >= DATEADD(DAY, -30, CURRENT_DATE);

-- Phase 6 Verification
SELECT 'PHASE 6: MONITORING VIEWS' AS PHASE, 'COMPLETE' AS STATUS;
SHOW VIEWS IN SCHEMA MONITORING_DB.MONITORING_SCHEMA;

-- ============================================================================
-- PHASE 7: ALERTS (10+ Cost and Queue Alerts)
-- ============================================================================

USE DATABASE MONITORING_DB;
USE SCHEMA MONITORING_SCHEMA;

-- 7.1 High Credit Usage Alert
CREATE OR REPLACE ALERT HC_ALERT_HIGH_CREDITS
    WAREHOUSE = HC_ANALYTICS_WH
    SCHEDULE = 'USING CRON 0 8 * * * UTC'
    IF (EXISTS(
        SELECT 1 FROM SNOWFLAKE.ACCOUNT_USAGE.WAREHOUSE_METERING_HISTORY
        WHERE START_TIME >= DATEADD(DAY, -1, CURRENT_DATE)
        HAVING SUM(CREDITS_USED) > 20
    ))
    THEN CALL SYSTEM$SEND_EMAIL('healthcare_alerts', 'High Credit Usage', 'Daily credits exceeded 20');

-- 7.2 Failed Login Alert
CREATE OR REPLACE ALERT HC_ALERT_FAILED_LOGINS
    WAREHOUSE = HC_ANALYTICS_WH
    SCHEDULE = 'USING CRON */30 * * * * UTC'
    IF (EXISTS(
        SELECT 1 FROM SNOWFLAKE.ACCOUNT_USAGE.LOGIN_HISTORY
        WHERE IS_SUCCESS = 'NO' AND EVENT_TIMESTAMP >= DATEADD(HOUR, -1, CURRENT_TIMESTAMP)
        HAVING COUNT(*) > 5
    ))
    THEN CALL SYSTEM$SEND_EMAIL('healthcare_alerts', 'Failed Login Alert', 'Multiple failed logins detected');

-- 7.3 Long Running Query Alert
CREATE OR REPLACE ALERT HC_ALERT_LONG_QUERY
    WAREHOUSE = HC_ANALYTICS_WH
    SCHEDULE = 'USING CRON */15 * * * * UTC'
    IF (EXISTS(
        SELECT 1 FROM SNOWFLAKE.ACCOUNT_USAGE.QUERY_HISTORY
        WHERE TOTAL_ELAPSED_TIME > 1800000 AND START_TIME >= DATEADD(HOUR, -1, CURRENT_TIMESTAMP)
    ))
    THEN CALL SYSTEM$SEND_EMAIL('healthcare_alerts', 'Long Query Alert', 'Query running > 30 minutes');

-- 7.4 Warehouse Queue Alert
CREATE OR REPLACE ALERT HC_ALERT_QUEUE_TIME
    WAREHOUSE = HC_ANALYTICS_WH
    SCHEDULE = 'USING CRON */10 * * * * UTC'
    IF (EXISTS(
        SELECT 1 FROM SNOWFLAKE.ACCOUNT_USAGE.WAREHOUSE_LOAD_HISTORY
        WHERE AVG_QUEUED_LOAD > 5 AND START_TIME >= DATEADD(HOUR, -1, CURRENT_TIMESTAMP)
    ))
    THEN CALL SYSTEM$SEND_EMAIL('healthcare_alerts', 'Queue Alert', 'High warehouse queue detected');

-- 7.5 Storage Growth Alert
CREATE OR REPLACE ALERT HC_ALERT_STORAGE_GROWTH
    WAREHOUSE = HC_ANALYTICS_WH
    SCHEDULE = 'USING CRON 0 6 * * * UTC'
    IF (EXISTS(
        SELECT 1 FROM SNOWFLAKE.ACCOUNT_USAGE.DATABASE_STORAGE_USAGE_HISTORY
        WHERE USAGE_DATE = CURRENT_DATE() AND AVERAGE_DATABASE_BYTES > 10737418240  -- 10GB
    ))
    THEN CALL SYSTEM$SEND_EMAIL('healthcare_alerts', 'Storage Alert', 'Database exceeds 10GB');

-- 7.6 ICU Critical Patient Alert
CREATE OR REPLACE ALERT HC_ALERT_ICU_CRITICAL
    WAREHOUSE = HC_AI_WH
    SCHEDULE = 'USING CRON */5 * * * * UTC'
    IF (EXISTS(
        SELECT 1 FROM AI_READY_DB.AI_SCHEMA.ICU_FEATURE_STORE WHERE RISK_SCORE >= 3
    ))
    THEN CALL SYSTEM$SEND_EMAIL('healthcare_alerts', 'ICU Critical', 'High-risk patients detected');

-- 7.7 Billing Overdue Alert
CREATE OR REPLACE ALERT HC_ALERT_BILLING_OVERDUE
    WAREHOUSE = HC_ANALYTICS_WH
    SCHEDULE = 'USING CRON 0 9 * * * UTC'
    IF (EXISTS(
        SELECT 1 FROM RAW_DB.RAW_SCHEMA.BILLING_DATA
        WHERE PAYMENT_STATUS = 'OVERDUE' HAVING COUNT(*) > 100
    ))
    THEN CALL SYSTEM$SEND_EMAIL('healthcare_alerts', 'Billing Alert', '100+ overdue bills');

-- 7.8 Device High Severity Alert
CREATE OR REPLACE ALERT HC_ALERT_DEVICE_SEVERITY
    WAREHOUSE = HC_AI_WH
    SCHEDULE = 'USING CRON */5 * * * * UTC'
    IF (EXISTS(
        SELECT 1 FROM RAW_DB.RAW_SCHEMA.DEVICE_ALERTS
        WHERE SEVERITY = 'HIGH' AND ALERT_TIMESTAMP >= DATEADD(MINUTE, -10, CURRENT_TIMESTAMP)
    ))
    THEN CALL SYSTEM$SEND_EMAIL('healthcare_alerts', 'Device Alert', 'High severity device alert');

-- 7.9 ETL Failure Alert
CREATE OR REPLACE ALERT HC_ALERT_ETL_FAILURE
    WAREHOUSE = HC_ETL_WH
    SCHEDULE = 'USING CRON */30 * * * * UTC'
    IF (EXISTS(
        SELECT 1 FROM SNOWFLAKE.ACCOUNT_USAGE.QUERY_HISTORY
        WHERE QUERY_TEXT ILIKE '%COPY INTO%' AND ERROR_CODE IS NOT NULL
        AND START_TIME >= DATEADD(HOUR, -1, CURRENT_TIMESTAMP)
    ))
    THEN CALL SYSTEM$SEND_EMAIL('healthcare_alerts', 'ETL Failure', 'Data load failed');

-- 7.10 Concurrent Query Alert
CREATE OR REPLACE ALERT HC_ALERT_CONCURRENT_QUERIES
    WAREHOUSE = HC_ANALYTICS_WH
    SCHEDULE = 'USING CRON */10 * * * * UTC'
    IF (EXISTS(
        SELECT 1 FROM SNOWFLAKE.ACCOUNT_USAGE.WAREHOUSE_LOAD_HISTORY
        WHERE AVG_RUNNING > 10 AND START_TIME >= DATEADD(HOUR, -1, CURRENT_TIMESTAMP)
    ))
    THEN CALL SYSTEM$SEND_EMAIL('healthcare_alerts', 'Concurrency Alert', 'High concurrent queries');

-- Phase 7 Verification
SELECT 'PHASE 7: ALERTS' AS PHASE, 'COMPLETE' AS STATUS;
SHOW ALERTS IN ACCOUNT;

-- ============================================================================
-- PHASE 8: DATA GOVERNANCE (Snowflake Horizon)
-- Objectives: Tags, 3 masking policies, row access
-- ============================================================================

USE ROLE ACCOUNTADMIN;
USE DATABASE SECURITY_DB;
USE SCHEMA SECURITY_SCHEMA;

-- 8.1 Classification Tags
CREATE OR REPLACE TAG DATA_CLASSIFICATION
    ALLOWED_VALUES 'PUBLIC', 'INTERNAL', 'CONFIDENTIAL', 'RESTRICTED'
    COMMENT = 'Data classification levels';

CREATE OR REPLACE TAG PII_TYPE
    ALLOWED_VALUES 'SSN', 'PHONE', 'EMAIL', 'ADDRESS', 'DOB', 'NAME'
    COMMENT = 'PII data type classification';

CREATE OR REPLACE TAG PHI_TYPE
    ALLOWED_VALUES 'DIAGNOSIS', 'TREATMENT', 'MEDICATION', 'VITALS'
    COMMENT = 'PHI data type classification';

-- 8.2 Masking Policy 1: SSN
CREATE OR REPLACE MASKING POLICY MASK_SSN
    AS (val STRING) RETURNS STRING ->
    CASE
        WHEN CURRENT_ROLE() IN ('ACCOUNTADMIN', 'HC_SECURITY_ADMIN') THEN val
        WHEN CURRENT_ROLE() IN ('HC_ACCOUNT_ADMIN') THEN '***-**-' || RIGHT(val, 4)
        ELSE '***-**-****'
    END
    COMMENT = 'SSN masking policy';

-- 8.3 Masking Policy 2: Phone
CREATE OR REPLACE MASKING POLICY MASK_PHONE
    AS (val STRING) RETURNS STRING ->
    CASE
        WHEN CURRENT_ROLE() IN ('ACCOUNTADMIN', 'HC_SECURITY_ADMIN') THEN val
        WHEN CURRENT_ROLE() IN ('HC_ACCOUNT_ADMIN', 'HC_DATA_ENGINEER') THEN '(***) ***-' || RIGHT(val, 4)
        ELSE '(***) ***-****'
    END
    COMMENT = 'Phone number masking policy';

-- 8.4 Masking Policy 3: Insurance Number
CREATE OR REPLACE MASKING POLICY MASK_INSURANCE
    AS (val STRING) RETURNS STRING ->
    CASE
        WHEN CURRENT_ROLE() IN ('ACCOUNTADMIN', 'HC_SECURITY_ADMIN') THEN val
        ELSE 'INS-****-' || RIGHT(val, 4)
    END
    COMMENT = 'Insurance number masking policy';

-- 8.5 Row Access Policy
CREATE OR REPLACE ROW ACCESS POLICY REGION_ACCESS_POLICY
    AS (hospital_region STRING) RETURNS BOOLEAN ->
    CASE
        WHEN CURRENT_ROLE() IN ('ACCOUNTADMIN', 'HC_SECURITY_ADMIN', 'HC_ACCOUNT_ADMIN') THEN TRUE
        WHEN CURRENT_ROLE() = 'HC_ANALYST' AND hospital_region IN ('North', 'South') THEN TRUE
        WHEN CURRENT_ROLE() = 'HC_VIEWER' AND hospital_region = 'North' THEN TRUE
        ELSE TRUE  -- Allow all for demo; customize per requirements
    END
    COMMENT = 'Region-based row access policy';

-- Phase 8 Verification
SELECT 'PHASE 8: DATA GOVERNANCE' AS PHASE, 'COMPLETE' AS STATUS;
SHOW TAGS IN SCHEMA SECURITY_DB.SECURITY_SCHEMA;
SHOW MASKING POLICIES IN SCHEMA SECURITY_DB.SECURITY_SCHEMA;
SHOW ROW ACCESS POLICIES IN SCHEMA SECURITY_DB.SECURITY_SCHEMA;

-- ============================================================================
-- PHASE 9: AUDIT LAYER
-- Objectives: Login, grants, user tracking views
-- ============================================================================

USE DATABASE AUDIT_DB;
USE SCHEMA AUDIT_SCHEMA;

-- 9.1 Login History Audit
CREATE OR REPLACE VIEW V_AUDIT_LOGIN_HISTORY AS
SELECT
    EVENT_TIMESTAMP, USER_NAME, CLIENT_IP,
    REPORTED_CLIENT_TYPE, IS_SUCCESS,
    ERROR_CODE, ERROR_MESSAGE,
    FIRST_AUTHENTICATION_FACTOR, SECOND_AUTHENTICATION_FACTOR
FROM SNOWFLAKE.ACCOUNT_USAGE.LOGIN_HISTORY
ORDER BY EVENT_TIMESTAMP DESC;

-- 9.2 Role Grants Audit
CREATE OR REPLACE VIEW V_AUDIT_ROLE_GRANTS AS
SELECT
    CREATED_ON, MODIFIED_ON, PRIVILEGE, GRANTED_ON,
    NAME, TABLE_CATALOG, TABLE_SCHEMA,
    GRANTED_TO, GRANTEE_NAME, GRANT_OPTION, GRANTED_BY
FROM SNOWFLAKE.ACCOUNT_USAGE.GRANTS_TO_ROLES
ORDER BY CREATED_ON DESC;

-- 9.3 User Grants Audit
CREATE OR REPLACE VIEW V_AUDIT_USER_GRANTS AS
SELECT
    CREATED_ON, ROLE, GRANTED_TO, GRANTEE_NAME, GRANTED_BY
FROM SNOWFLAKE.ACCOUNT_USAGE.GRANTS_TO_USERS
ORDER BY CREATED_ON DESC;

-- 9.4 User Management Audit
CREATE OR REPLACE VIEW V_AUDIT_USERS AS
SELECT
    NAME, CREATED_ON, DELETED_ON, LOGIN_NAME,
    DISPLAY_NAME, EMAIL, DEFAULT_ROLE,
    DEFAULT_WAREHOUSE, DISABLED, LOCKED_UNTIL_TIME,
    LAST_SUCCESS_LOGIN, EXPIRES_AT
FROM SNOWFLAKE.ACCOUNT_USAGE.USERS
ORDER BY CREATED_ON DESC;

-- 9.5 Access History Audit
CREATE OR REPLACE VIEW V_AUDIT_ACCESS_HISTORY AS
SELECT
    QUERY_START_TIME, USER_NAME, QUERY_ID,
    DIRECT_OBJECTS_ACCESSED, BASE_OBJECTS_ACCESSED, OBJECTS_MODIFIED
FROM SNOWFLAKE.ACCOUNT_USAGE.ACCESS_HISTORY
WHERE QUERY_START_TIME >= DATEADD(DAY, -30, CURRENT_DATE)
ORDER BY QUERY_START_TIME DESC;

-- 9.6 Copy/Load History Audit
CREATE OR REPLACE VIEW V_AUDIT_COPY_HISTORY AS
SELECT
    FILE_NAME, STAGE_LOCATION, LAST_LOAD_TIME,
    ROW_COUNT, ROW_PARSED, FILE_SIZE,
    FIRST_ERROR_MESSAGE, STATUS,
    TABLE_CATALOG_NAME, TABLE_SCHEMA_NAME, TABLE_NAME
FROM SNOWFLAKE.ACCOUNT_USAGE.COPY_HISTORY
WHERE LAST_LOAD_TIME >= DATEADD(DAY, -30, CURRENT_DATE)
ORDER BY LAST_LOAD_TIME DESC;

-- Phase 9 Verification
SELECT 'PHASE 9: AUDIT LAYER' AS PHASE, 'COMPLETE' AS STATUS;
SHOW VIEWS IN SCHEMA AUDIT_DB.AUDIT_SCHEMA;

-- ============================================================================
-- PHASE 10: VERIFICATION (Test Cases)
-- ============================================================================

USE ROLE ACCOUNTADMIN;

-- Test Case 1: Verify all databases exist
SELECT 'TC01: Databases' AS TEST, COUNT(*) AS COUNT,
    CASE WHEN COUNT(*) >= 7 THEN 'PASS' ELSE 'FAIL' END AS RESULT
FROM (SHOW DATABASES LIKE '%_DB');

-- Test Case 2: Verify all roles exist
SELECT 'TC02: Roles' AS TEST, COUNT(*) AS COUNT,
    CASE WHEN COUNT(*) >= 6 THEN 'PASS' ELSE 'FAIL' END AS RESULT
FROM (SHOW ROLES LIKE 'HC_%');

-- Test Case 3: Verify all warehouses exist
SELECT 'TC03: Warehouses' AS TEST, COUNT(*) AS COUNT,
    CASE WHEN COUNT(*) >= 4 THEN 'PASS' ELSE 'FAIL' END AS RESULT
FROM (SHOW WAREHOUSES LIKE 'HC_%');

-- Test Case 4: Verify resource monitors
SELECT 'TC04: Resource Monitors' AS TEST, COUNT(*) AS COUNT,
    CASE WHEN COUNT(*) >= 5 THEN 'PASS' ELSE 'FAIL' END AS RESULT
FROM (SHOW RESOURCE MONITORS LIKE 'HC_%');

-- Test Case 5: Verify monitoring views
SELECT 'TC05: Monitoring Views' AS TEST, COUNT(*) AS COUNT,
    CASE WHEN COUNT(*) >= 10 THEN 'PASS' ELSE 'FAIL' END AS RESULT
FROM (SHOW VIEWS IN SCHEMA MONITORING_DB.MONITORING_SCHEMA);

-- Test Case 6: Verify governance objects
SELECT 'TC06: Masking Policies' AS TEST, COUNT(*) AS COUNT,
    CASE WHEN COUNT(*) >= 3 THEN 'PASS' ELSE 'FAIL' END AS RESULT
FROM (SHOW MASKING POLICIES IN SCHEMA SECURITY_DB.SECURITY_SCHEMA);

-- Test Case 7: Verify audit views
SELECT 'TC07: Audit Views' AS TEST, COUNT(*) AS COUNT,
    CASE WHEN COUNT(*) >= 6 THEN 'PASS' ELSE 'FAIL' END AS RESULT
FROM (SHOW VIEWS IN SCHEMA AUDIT_DB.AUDIT_SCHEMA);

-- Phase 10 Verification
SELECT 'PHASE 10: VERIFICATION' AS PHASE, 'COMPLETE' AS STATUS;

-- ============================================================================
-- PHASE 11: MEDALLION ARCHITECTURE
-- Objectives: RAW_DB, TRANSFORM_DB, ANALYTICS_DB, AI_READY_DB with data
-- ============================================================================

USE ROLE ACCOUNTADMIN;

-- 11.1 BRONZE LAYER - RAW_DB
USE DATABASE RAW_DB;
USE SCHEMA RAW_SCHEMA;

-- Patient Raw Data (10,000 records)
CREATE OR REPLACE TABLE PATIENT_RAW AS
SELECT
    'P' || LPAD(SEQ4()+1, 5, '0') AS PATIENT_ID,
    'Patient_' || LPAD(SEQ4()+1, 5, '0') AS NAME,
    UNIFORM(18, 90, RANDOM()) AS AGE,
    CASE WHEN UNIFORM(0,1,RANDOM()) < 0.5 THEN 'M' ELSE 'F' END AS GENDER,
    DATEADD(DAY, -UNIFORM(0, 365, RANDOM()), CURRENT_DATE) AS ADMISSION_DATE,
    CASE UNIFORM(1,5,RANDOM())
        WHEN 1 THEN 'Cardiology'
        WHEN 2 THEN 'Neurology'
        WHEN 3 THEN 'Pulmonology'
        WHEN 4 THEN 'Orthopedics'
        ELSE 'General'
    END AS DIAGNOSIS,
    LPAD(UNIFORM(100000000, 999999999, RANDOM())::STRING, 9, '0') AS SSN,
    'INS-' || LPAD(UNIFORM(10000000, 99999999, RANDOM())::STRING, 8, '0') AS INSURANCE_NO,
    '(' || LPAD(UNIFORM(200, 999, RANDOM())::STRING, 3, '0') || ') ' ||
        LPAD(UNIFORM(200, 999, RANDOM())::STRING, 3, '0') || '-' ||
        LPAD(UNIFORM(1000, 9999, RANDOM())::STRING, 4, '0') AS PHONE,
    CASE UNIFORM(1,4,RANDOM())
        WHEN 1 THEN 'North'
        WHEN 2 THEN 'South'
        WHEN 3 THEN 'East'
        ELSE 'West'
    END AS HOSPITAL_REGION,
    CURRENT_TIMESTAMP AS LOAD_TIMESTAMP
FROM TABLE(GENERATOR(ROWCOUNT => 10000));

-- ICU Events (50,000 records)
CREATE OR REPLACE TABLE ICU_EVENTS AS
SELECT
    'E' || LPAD(SEQ4()+1, 6, '0') AS EVENT_ID,
    'P' || LPAD(UNIFORM(1, 10000, RANDOM()), 5, '0') AS PATIENT_ID,
    CASE UNIFORM(1,4,RANDOM())
        WHEN 1 THEN 'Vitals Check'
        WHEN 2 THEN 'Medication'
        WHEN 3 THEN 'Alert'
        ELSE 'Procedure'
    END AS EVENT_TYPE,
    DATEADD(HOUR, -UNIFORM(0, 720, RANDOM()), CURRENT_TIMESTAMP) AS EVENT_TIMESTAMP,
    UNIFORM(50, 150, RANDOM()) AS HEART_RATE,
    UNIFORM(80, 100, RANDOM()) AS OXYGEN_LEVEL,
    UNIFORM(90, 180, RANDOM()) AS SYSTOLIC_BP,
    UNIFORM(60, 110, RANDOM()) AS DIASTOLIC_BP,
    UNIFORM(96, 104, RANDOM())::DECIMAL(4,1) AS TEMPERATURE
FROM TABLE(GENERATOR(ROWCOUNT => 50000));

-- Billing Data (20,000 records)
CREATE OR REPLACE TABLE BILLING_DATA AS
SELECT
    'B' || LPAD(SEQ4()+1, 6, '0') AS BILL_ID,
    'P' || LPAD(UNIFORM(1, 10000, RANDOM()), 5, '0') AS PATIENT_ID,
    UNIFORM(500, 150000, RANDOM())::DECIMAL(12,2) AS BILL_AMOUNT,
    DATEADD(DAY, -UNIFORM(0, 180, RANDOM()), CURRENT_DATE) AS BILL_DATE,
    CASE UNIFORM(1,3,RANDOM())
        WHEN 1 THEN 'PAID'
        WHEN 2 THEN 'PENDING'
        ELSE 'OVERDUE'
    END AS PAYMENT_STATUS,
    CASE UNIFORM(1,5,RANDOM())
        WHEN 1 THEN 'Surgery'
        WHEN 2 THEN 'Medication'
        WHEN 3 THEN 'Lab Tests'
        WHEN 4 THEN 'Room Charges'
        ELSE 'Consultation'
    END AS SERVICE_TYPE
FROM TABLE(GENERATOR(ROWCOUNT => 20000));

-- Device Alerts (5,000 records)
CREATE OR REPLACE TABLE DEVICE_ALERTS AS
SELECT
    'D' || LPAD(SEQ4()+1, 5, '0') AS DEVICE_ID,
    'P' || LPAD(UNIFORM(1, 10000, RANDOM()), 5, '0') AS PATIENT_ID,
    CASE UNIFORM(1,4,RANDOM())
        WHEN 1 THEN 'Heart Monitor'
        WHEN 2 THEN 'Oxygen Sensor'
        WHEN 3 THEN 'BP Monitor'
        ELSE 'Glucose Monitor'
    END AS DEVICE_TYPE,
    CASE UNIFORM(1,4,RANDOM())
        WHEN 1 THEN 'Low Battery'
        WHEN 2 THEN 'Disconnected'
        WHEN 3 THEN 'Reading Anomaly'
        ELSE 'Calibration Required'
    END AS ALERT_TYPE,
    DATEADD(MINUTE, -UNIFORM(0, 10080, RANDOM()), CURRENT_TIMESTAMP) AS ALERT_TIMESTAMP,
    CASE UNIFORM(1,3,RANDOM())
        WHEN 1 THEN 'LOW'
        WHEN 2 THEN 'MEDIUM'
        ELSE 'HIGH'
    END AS SEVERITY
FROM TABLE(GENERATOR(ROWCOUNT => 5000));

-- 11.2 Apply Governance Policies to Bronze
ALTER TABLE RAW_DB.RAW_SCHEMA.PATIENT_RAW
    MODIFY COLUMN SSN SET MASKING POLICY SECURITY_DB.SECURITY_SCHEMA.MASK_SSN;
ALTER TABLE RAW_DB.RAW_SCHEMA.PATIENT_RAW
    MODIFY COLUMN PHONE SET MASKING POLICY SECURITY_DB.SECURITY_SCHEMA.MASK_PHONE;
ALTER TABLE RAW_DB.RAW_SCHEMA.PATIENT_RAW
    MODIFY COLUMN INSURANCE_NO SET MASKING POLICY SECURITY_DB.SECURITY_SCHEMA.MASK_INSURANCE;
ALTER TABLE RAW_DB.RAW_SCHEMA.PATIENT_RAW
    ADD ROW ACCESS POLICY SECURITY_DB.SECURITY_SCHEMA.REGION_ACCESS_POLICY ON (HOSPITAL_REGION);

-- 11.3 SILVER LAYER - TRANSFORM_DB
USE DATABASE TRANSFORM_DB;
USE SCHEMA TRANSFORM_SCHEMA;

-- Cleaned Patient Data
CREATE OR REPLACE TABLE CLEAN_PATIENT AS
SELECT
    PATIENT_ID, NAME, AGE, GENDER, ADMISSION_DATE, DIAGNOSIS,
    LEFT(PATIENT_ID, 2) || '***' AS PATIENT_ID_MASKED,
    HOSPITAL_REGION,
    DATEDIFF(DAY, ADMISSION_DATE, CURRENT_DATE) AS DAYS_SINCE_ADMISSION,
    CASE
        WHEN AGE < 18 THEN 'Pediatric'
        WHEN AGE BETWEEN 18 AND 64 THEN 'Adult'
        ELSE 'Senior'
    END AS AGE_GROUP,
    CURRENT_TIMESTAMP AS ETL_TIMESTAMP
FROM RAW_DB.RAW_SCHEMA.PATIENT_RAW;

-- Cleaned ICU Events with Critical Flag
CREATE OR REPLACE TABLE CLEAN_ICU_EVENTS AS
SELECT
    EVENT_ID, PATIENT_ID, EVENT_TYPE, EVENT_TIMESTAMP,
    HEART_RATE, OXYGEN_LEVEL, SYSTOLIC_BP, DIASTOLIC_BP, TEMPERATURE,
    CASE 
        WHEN HEART_RATE > 100 OR HEART_RATE < 60 THEN TRUE
        WHEN OXYGEN_LEVEL < 92 THEN TRUE
        WHEN SYSTOLIC_BP > 140 OR DIASTOLIC_BP > 90 THEN TRUE
        ELSE FALSE
    END AS IS_CRITICAL,
    CASE
        WHEN HEART_RATE > 120 OR OXYGEN_LEVEL < 88 THEN 'HIGH'
        WHEN HEART_RATE > 100 OR OXYGEN_LEVEL < 92 THEN 'MEDIUM'
        ELSE 'LOW'
    END AS ALERT_LEVEL,
    CURRENT_TIMESTAMP AS ETL_TIMESTAMP
FROM RAW_DB.RAW_SCHEMA.ICU_EVENTS;

-- 11.4 GOLD LAYER - ANALYTICS_DB
USE DATABASE ANALYTICS_DB;
USE SCHEMA ANALYTICS_SCHEMA;

-- Patient Analytics Aggregation
CREATE OR REPLACE TABLE PATIENT_ANALYTICS AS
SELECT
    p.PATIENT_ID, p.NAME, p.AGE, p.AGE_GROUP, p.GENDER,
    p.ADMISSION_DATE, p.DIAGNOSIS, p.HOSPITAL_REGION,
    p.DAYS_SINCE_ADMISSION,
    COUNT(i.EVENT_ID) AS TOTAL_ICU_EVENTS,
    SUM(CASE WHEN i.IS_CRITICAL THEN 1 ELSE 0 END) AS CRITICAL_EVENTS,
    AVG(i.HEART_RATE) AS AVG_HEART_RATE,
    AVG(i.OXYGEN_LEVEL) AS AVG_OXYGEN_LEVEL,
    AVG(i.SYSTOLIC_BP) AS AVG_SYSTOLIC_BP,
    AVG(i.DIASTOLIC_BP) AS AVG_DIASTOLIC_BP,
    MIN(i.OXYGEN_LEVEL) AS MIN_OXYGEN_LEVEL,
    MAX(i.HEART_RATE) AS MAX_HEART_RATE
FROM TRANSFORM_DB.TRANSFORM_SCHEMA.CLEAN_PATIENT p
LEFT JOIN TRANSFORM_DB.TRANSFORM_SCHEMA.CLEAN_ICU_EVENTS i ON p.PATIENT_ID = i.PATIENT_ID
GROUP BY p.PATIENT_ID, p.NAME, p.AGE, p.AGE_GROUP, p.GENDER,
         p.ADMISSION_DATE, p.DIAGNOSIS, p.HOSPITAL_REGION, p.DAYS_SINCE_ADMISSION;

-- Billing Analytics Aggregation
CREATE OR REPLACE TABLE BILLING_ANALYTICS AS
SELECT
    PATIENT_ID,
    COUNT(BILL_ID) AS TOTAL_BILLS,
    SUM(BILL_AMOUNT) AS TOTAL_AMOUNT,
    AVG(BILL_AMOUNT) AS AVG_BILL_AMOUNT,
    MAX(BILL_AMOUNT) AS MAX_BILL_AMOUNT,
    SUM(CASE WHEN PAYMENT_STATUS = 'PAID' THEN BILL_AMOUNT ELSE 0 END) AS PAID_AMOUNT,
    SUM(CASE WHEN PAYMENT_STATUS = 'PENDING' THEN BILL_AMOUNT ELSE 0 END) AS PENDING_AMOUNT,
    SUM(CASE WHEN PAYMENT_STATUS = 'OVERDUE' THEN BILL_AMOUNT ELSE 0 END) AS OVERDUE_AMOUNT,
    SUM(CASE WHEN PAYMENT_STATUS = 'PAID' THEN 1 ELSE 0 END) AS PAID_COUNT,
    SUM(CASE WHEN PAYMENT_STATUS = 'PENDING' THEN 1 ELSE 0 END) AS PENDING_COUNT,
    SUM(CASE WHEN PAYMENT_STATUS = 'OVERDUE' THEN 1 ELSE 0 END) AS OVERDUE_COUNT
FROM RAW_DB.RAW_SCHEMA.BILLING_DATA
GROUP BY PATIENT_ID;

-- Phase 11 Verification
SELECT 'PHASE 11: MEDALLION ARCHITECTURE' AS PHASE, 'COMPLETE' AS STATUS;

-- ============================================================================
-- PHASE 12: INDUSTRY - HEALTHCARE (HCLS)
-- Already implemented throughout all phases
-- ============================================================================

SELECT 'PHASE 12: INDUSTRY (HEALTHCARE)' AS PHASE, 'COMPLETE' AS STATUS;

-- ============================================================================
-- PHASE 13: AI-READY LAYER
-- Objectives: Feature store, semantic models, embeddings
-- ============================================================================

USE DATABASE AI_READY_DB;
USE SCHEMA AI_SCHEMA;

-- 13.1 ICU Feature Store (ML-ready features)
CREATE OR REPLACE TABLE ICU_FEATURE_STORE AS
SELECT
    p.PATIENT_ID,
    p.AGE,
    p.AGE_GROUP,
    p.GENDER,
    p.DIAGNOSIS,
    p.HOSPITAL_REGION,
    p.DAYS_SINCE_ADMISSION,
    p.TOTAL_ICU_EVENTS,
    p.CRITICAL_EVENTS,
    p.AVG_HEART_RATE,
    p.AVG_OXYGEN_LEVEL,
    p.AVG_SYSTOLIC_BP,
    p.AVG_DIASTOLIC_BP,
    p.MIN_OXYGEN_LEVEL,
    p.MAX_HEART_RATE,
    COALESCE(b.TOTAL_AMOUNT, 0) AS TOTAL_BILLING,
    COALESCE(b.PAID_AMOUNT, 0) AS PAID_AMOUNT,
    COALESCE(b.OVERDUE_AMOUNT, 0) AS OVERDUE_AMOUNT,
    -- Binary Risk Flags
    CASE WHEN p.AGE > 65 THEN 1 ELSE 0 END AS RISK_AGE,
    CASE WHEN p.AVG_OXYGEN_LEVEL < 92 THEN 1 ELSE 0 END AS RISK_LOW_OXYGEN,
    CASE WHEN p.AVG_HEART_RATE > 100 THEN 1 ELSE 0 END AS RISK_HIGH_HR,
    CASE WHEN p.CRITICAL_EVENTS > 5 THEN 1 ELSE 0 END AS RISK_CRITICAL_EVENTS,
    CASE WHEN p.AVG_SYSTOLIC_BP > 140 THEN 1 ELSE 0 END AS RISK_HIGH_BP,
    CASE WHEN p.DAYS_SINCE_ADMISSION > 14 THEN 1 ELSE 0 END AS RISK_LONG_STAY,
    CASE WHEN COALESCE(b.OVERDUE_AMOUNT, 0) > 10000 THEN 1 ELSE 0 END AS RISK_BILLING,
    -- Composite Risk Score
    (CASE WHEN p.AGE > 65 THEN 1 ELSE 0 END +
     CASE WHEN p.AVG_OXYGEN_LEVEL < 92 THEN 1 ELSE 0 END +
     CASE WHEN p.AVG_HEART_RATE > 100 THEN 1 ELSE 0 END +
     CASE WHEN p.CRITICAL_EVENTS > 5 THEN 1 ELSE 0 END +
     CASE WHEN p.AVG_SYSTOLIC_BP > 140 THEN 1 ELSE 0 END) AS RISK_SCORE,
    -- Risk Category
    CASE
        WHEN (CASE WHEN p.AGE > 65 THEN 1 ELSE 0 END +
              CASE WHEN p.AVG_OXYGEN_LEVEL < 92 THEN 1 ELSE 0 END +
              CASE WHEN p.AVG_HEART_RATE > 100 THEN 1 ELSE 0 END +
              CASE WHEN p.CRITICAL_EVENTS > 5 THEN 1 ELSE 0 END) >= 3 THEN 'CRITICAL'
        WHEN (CASE WHEN p.AGE > 65 THEN 1 ELSE 0 END +
              CASE WHEN p.AVG_OXYGEN_LEVEL < 92 THEN 1 ELSE 0 END +
              CASE WHEN p.AVG_HEART_RATE > 100 THEN 1 ELSE 0 END) >= 2 THEN 'HIGH'
        WHEN (CASE WHEN p.AGE > 65 THEN 1 ELSE 0 END +
              CASE WHEN p.AVG_OXYGEN_LEVEL < 92 THEN 1 ELSE 0 END) >= 1 THEN 'MEDIUM'
        ELSE 'LOW'
    END AS RISK_CATEGORY,
    CURRENT_TIMESTAMP AS FEATURE_TIMESTAMP
FROM ANALYTICS_DB.ANALYTICS_SCHEMA.PATIENT_ANALYTICS p
LEFT JOIN ANALYTICS_DB.ANALYTICS_SCHEMA.BILLING_ANALYTICS b ON p.PATIENT_ID = b.PATIENT_ID;

-- 13.2 Patient Notes for Embeddings
USE SCHEMA FEATURE_STORE;

CREATE OR REPLACE TABLE PATIENT_NOTES AS
SELECT
    PATIENT_ID,
    DIAGNOSIS,
    CASE DIAGNOSIS
        WHEN 'Cardiology' THEN 'Patient presents with cardiac symptoms including chest pain and irregular heartbeat. Requires continuous ECG monitoring.'
        WHEN 'Neurology' THEN 'Patient shows neurological symptoms including headache and dizziness. MRI scan recommended.'
        WHEN 'Pulmonology' THEN 'Patient has respiratory issues with shortness of breath and low oxygen saturation. Oxygen therapy initiated.'
        WHEN 'Orthopedics' THEN 'Patient admitted with musculoskeletal injury. Physical therapy and pain management prescribed.'
        ELSE 'Patient admitted for general evaluation and observation. Routine tests ordered.'
    END AS CLINICAL_NOTES,
    CURRENT_TIMESTAMP AS CREATED_AT
FROM ANALYTICS_DB.ANALYTICS_SCHEMA.PATIENT_ANALYTICS;

-- 13.3 Synthetic Embeddings (Placeholder for Cortex embeddings)
CREATE OR REPLACE TABLE PATIENT_EMBEDDINGS AS
SELECT
    PATIENT_ID,
    DIAGNOSIS,
    CLINICAL_NOTES,
    -- Synthetic embedding (768-dimensional would use SNOWFLAKE.CORTEX.EMBED_TEXT_768)
    ARRAY_CONSTRUCT(
        UNIFORM(0::FLOAT, 1::FLOAT, RANDOM()),
        UNIFORM(0::FLOAT, 1::FLOAT, RANDOM()),
        UNIFORM(0::FLOAT, 1::FLOAT, RANDOM()),
        UNIFORM(0::FLOAT, 1::FLOAT, RANDOM()),
        UNIFORM(0::FLOAT, 1::FLOAT, RANDOM()),
        UNIFORM(0::FLOAT, 1::FLOAT, RANDOM()),
        UNIFORM(0::FLOAT, 1::FLOAT, RANDOM()),
        UNIFORM(0::FLOAT, 1::FLOAT, RANDOM())
    ) AS EMBEDDING_VECTOR,
    CURRENT_TIMESTAMP AS EMBEDDING_TIMESTAMP
FROM PATIENT_NOTES;

-- 13.4 Semantic Model View (for Cortex Analyst)
USE SCHEMA SEMANTIC_MODELS;

CREATE OR REPLACE VIEW V_PATIENT_SEMANTIC AS
SELECT
    f.PATIENT_ID AS "Patient ID",
    f.AGE AS "Age",
    f.AGE_GROUP AS "Age Group",
    f.GENDER AS "Gender",
    f.DIAGNOSIS AS "Diagnosis",
    f.HOSPITAL_REGION AS "Hospital Region",
    f.DAYS_SINCE_ADMISSION AS "Days Since Admission",
    f.TOTAL_ICU_EVENTS AS "Total ICU Events",
    f.CRITICAL_EVENTS AS "Critical Events",
    f.AVG_HEART_RATE AS "Average Heart Rate",
    f.AVG_OXYGEN_LEVEL AS "Average Oxygen Level",
    f.RISK_SCORE AS "Risk Score",
    f.RISK_CATEGORY AS "Risk Category",
    f.TOTAL_BILLING AS "Total Billing Amount",
    f.PAID_AMOUNT AS "Paid Amount",
    f.OVERDUE_AMOUNT AS "Overdue Amount"
FROM AI_READY_DB.AI_SCHEMA.ICU_FEATURE_STORE f;

-- Phase 13 Verification
SELECT 'PHASE 13: AI-READY LAYER' AS PHASE, 'COMPLETE' AS STATUS;

-- ============================================================================
-- PHASE 14: CI/CD FRAMEWORK (GitHub/Azure DevOps)
-- ============================================================================

USE DATABASE DEVOPS_DB;
USE SCHEMA CI_CD;

-- 14.1 Deployment Log Table
CREATE OR REPLACE TABLE DEPLOYMENT_LOG (
    DEPLOYMENT_ID STRING NOT NULL,
    DEPLOYMENT_TIMESTAMP TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    EXECUTED_BY STRING DEFAULT CURRENT_USER(),
    ROLE_USED STRING DEFAULT CURRENT_ROLE(),
    SCRIPT_NAME STRING,
    PHASE_NUMBER NUMBER,
    STATUS STRING,
    ERROR_MESSAGE STRING,
    DURATION_MS NUMBER,
    ENVIRONMENT STRING DEFAULT 'PRODUCTION',
    GIT_COMMIT_HASH STRING,
    AZURE_DEVOPS_WORK_ITEM STRING
);

-- 14.2 Script Registry Table
CREATE OR REPLACE TABLE SCRIPT_REGISTRY (
    SCRIPT_ID STRING NOT NULL,
    SCRIPT_NAME STRING NOT NULL,
    SCRIPT_VERSION STRING DEFAULT '1.0.0',
    PHASE_NUMBER NUMBER,
    DEPLOYED_ON TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    DEPLOYED_BY STRING DEFAULT CURRENT_USER(),
    CHECKSUM STRING,
    DESCRIPTION STRING
);

-- 14.3 Deployment Procedure
CREATE OR REPLACE PROCEDURE SP_DEPLOY_SQL(
    P_DEPLOYMENT_ID STRING,
    P_SCRIPT_NAME STRING,
    P_PHASE_NUMBER NUMBER,
    P_SQL_SCRIPT STRING
)
RETURNS STRING
LANGUAGE JAVASCRIPT
EXECUTE AS CALLER
AS
$$
var start_time = Date.now();
try {
    var stmt = snowflake.createStatement({sqlText: P_SQL_SCRIPT});
    stmt.execute();
    var duration = Date.now() - start_time;
    
    var log_stmt = snowflake.createStatement({
        sqlText: "INSERT INTO DEVOPS_DB.CI_CD.DEPLOYMENT_LOG (DEPLOYMENT_ID, SCRIPT_NAME, PHASE_NUMBER, STATUS, DURATION_MS) VALUES (?, ?, ?, 'SUCCESS', ?)",
        binds: [P_DEPLOYMENT_ID, P_SCRIPT_NAME, P_PHASE_NUMBER, duration]
    });
    log_stmt.execute();
    
    var reg_stmt = snowflake.createStatement({
        sqlText: "INSERT INTO DEVOPS_DB.CI_CD.SCRIPT_REGISTRY (SCRIPT_ID, SCRIPT_NAME, PHASE_NUMBER) VALUES (?, ?, ?)",
        binds: [P_DEPLOYMENT_ID, P_SCRIPT_NAME, P_PHASE_NUMBER]
    });
    reg_stmt.execute();
    
    return 'SUCCESS: ' + duration + 'ms';
} catch(err) {
    var duration = Date.now() - start_time;
    var err_stmt = snowflake.createStatement({
        sqlText: "INSERT INTO DEVOPS_DB.CI_CD.DEPLOYMENT_LOG (DEPLOYMENT_ID, SCRIPT_NAME, PHASE_NUMBER, STATUS, ERROR_MESSAGE, DURATION_MS) VALUES (?, ?, ?, 'FAILED', ?, ?)",
        binds: [P_DEPLOYMENT_ID, P_SCRIPT_NAME, P_PHASE_NUMBER, err.message, duration]
    });
    err_stmt.execute();
    return 'FAILED: ' + err.message;
}
$$;

-- 14.4 Deployment Summary View
CREATE OR REPLACE VIEW V_DEPLOYMENT_SUMMARY AS
SELECT
    DATE_TRUNC('DAY', DEPLOYMENT_TIMESTAMP) AS DEPLOY_DATE,
    PHASE_NUMBER,
    COUNT(*) AS TOTAL_DEPLOYMENTS,
    SUM(CASE WHEN STATUS = 'SUCCESS' THEN 1 ELSE 0 END) AS SUCCESSFUL,
    SUM(CASE WHEN STATUS = 'FAILED' THEN 1 ELSE 0 END) AS FAILED,
    AVG(DURATION_MS) AS AVG_DURATION_MS
FROM DEPLOYMENT_LOG
GROUP BY DATE_TRUNC('DAY', DEPLOYMENT_TIMESTAMP), PHASE_NUMBER
ORDER BY DEPLOY_DATE DESC, PHASE_NUMBER;

-- 14.5 Log Initial Deployment
INSERT INTO DEPLOYMENT_LOG (DEPLOYMENT_ID, SCRIPT_NAME, PHASE_NUMBER, STATUS, DURATION_MS)
VALUES ('INITIAL_DEPLOY_' || TO_VARCHAR(CURRENT_TIMESTAMP, 'YYYYMMDDHH24MISS'), 'master_deployment.sql', 0, 'SUCCESS', 0);

-- Phase 14 Verification
SELECT 'PHASE 14: CI/CD FRAMEWORK' AS PHASE, 'COMPLETE' AS STATUS;

-- ============================================================================
-- PHASE 15: AZURE DEVOPS INTEGRATION
-- See azure-devops/ folder for pipeline and work item templates
-- ============================================================================

SELECT 'PHASE 15: AZURE DEVOPS' AS PHASE, 'CONFIGURED' AS STATUS;

-- ============================================================================
-- FINAL VERIFICATION - ALL PHASES
-- ============================================================================

-- Data Summary
SELECT 'BRONZE - PATIENT_RAW' AS LAYER, COUNT(*) AS ROW_COUNT FROM RAW_DB.RAW_SCHEMA.PATIENT_RAW
UNION ALL SELECT 'BRONZE - ICU_EVENTS', COUNT(*) FROM RAW_DB.RAW_SCHEMA.ICU_EVENTS
UNION ALL SELECT 'BRONZE - BILLING_DATA', COUNT(*) FROM RAW_DB.RAW_SCHEMA.BILLING_DATA
UNION ALL SELECT 'BRONZE - DEVICE_ALERTS', COUNT(*) FROM RAW_DB.RAW_SCHEMA.DEVICE_ALERTS
UNION ALL SELECT 'SILVER - CLEAN_PATIENT', COUNT(*) FROM TRANSFORM_DB.TRANSFORM_SCHEMA.CLEAN_PATIENT
UNION ALL SELECT 'SILVER - CLEAN_ICU_EVENTS', COUNT(*) FROM TRANSFORM_DB.TRANSFORM_SCHEMA.CLEAN_ICU_EVENTS
UNION ALL SELECT 'GOLD - PATIENT_ANALYTICS', COUNT(*) FROM ANALYTICS_DB.ANALYTICS_SCHEMA.PATIENT_ANALYTICS
UNION ALL SELECT 'GOLD - BILLING_ANALYTICS', COUNT(*) FROM ANALYTICS_DB.ANALYTICS_SCHEMA.BILLING_ANALYTICS
UNION ALL SELECT 'PLATINUM - ICU_FEATURE_STORE', COUNT(*) FROM AI_READY_DB.AI_SCHEMA.ICU_FEATURE_STORE
UNION ALL SELECT 'PLATINUM - PATIENT_EMBEDDINGS', COUNT(*) FROM AI_READY_DB.FEATURE_STORE.PATIENT_EMBEDDINGS;

-- Final Status
SELECT 
    'HEALTHCARE ENTERPRISE DATA HUB' AS PROJECT,
    '15 PHASES COMPLETE' AS STATUS,
    CURRENT_TIMESTAMP AS COMPLETED_AT,
    CURRENT_USER() AS DEPLOYED_BY,
    CURRENT_ACCOUNT() AS ACCOUNT;

-- ============================================================================
-- END OF MASTER DEPLOYMENT SCRIPT
-- ============================================================================
