-- =============================================
-- MASTER_DEPLOYMENT.SQL
-- Execute all scripts in order
-- =============================================

-- Run scripts in sequence:
-- 1. 01_account_administration.sql
-- 2. 02_rbac_setup.sql
-- 3. 03_warehouse_management.sql
-- 4. 04_database_structure.sql
-- 5. 05_resource_monitors.sql
-- 6. 06_monitoring_views.sql
-- 7. 07_alerts.sql
-- 8. 08_data_governance.sql
-- 9. 09_audit_layer.sql
-- 10. 10_verification.sql
-- 11. 11_medallion_architecture.sql
-- 12. 12_healthcare_industry.sql
-- 13. 13_ai_ready_layer.sql

-- Note: Execute each script individually in Snowsight
-- or use CI/CD pipeline for automated deployment
